import json
import yaml
from pathlib import Path
import sys

def quote(s):
    # Escape quotes for Zelph string literals
    return '"' + str(s).replace('"', '\\"') + '"'

def compile_wikidata(data):
    facts = []
    for entity in data.get("entities", []):
        ref = entity["canonical_ref"]
        # Zelph syntax doesn't like colons in symbols sometimes unless quoted, but we can emit them as atoms if zelph supports it, 
        # or replace colons with underscores for safe atoms.
        safe_ref = ref.replace(":", "_")
        facts.append(f"(actor {safe_ref})")
        facts.append(f"(canonical_label {safe_ref} {quote(entity['canonical_label'])})")
        facts.append(f"(wikidata_id {safe_ref} {entity['external_id']})")
    return facts

def compile_au_linkage(data):
    facts = []
    for item in data.get("items", []):
        seed_id = item["seed_id"].replace(":", "_")
        facts.append(f"(action_lane {seed_id})")
        facts.append(f"(lane_kind {seed_id} {item['linkage_kind']})")
        
        for court in item.get("court_refs", []):
            safe_court = court.replace(":", "_")
            facts.append(f"(court_authority {seed_id} {safe_court})")
            
        for inst in item.get("institution_refs", []):
            safe_inst = inst.replace(":", "_")
            facts.append(f"(institution_authority {seed_id} {safe_inst})")
            
        for tag in item.get("lane_tags", []):
            facts.append(f"(has_tag {seed_id} {tag})")
    return facts

def compile_wrong_types(data):
    facts = []
    for catalog in data.get("catalogs", []):
        sys_code = catalog["legal_system_code"].replace(".", "_")
        for wrong in catalog.get("wrong_types", []):
            code = wrong["code"]
            facts.append(f"(wrong_type {code})")
            facts.append(f"(wrong_system {code} {sys_code})")
            for interest in wrong.get("protected_interest_codes", []):
                facts.append(f"(protects_interest {code} {interest})")
            for src in wrong.get("sources", []):
                # We just pull the string out
                facts.append(f"(wrong_source {code} {quote(src['citation'])})")
    return facts

def main():
    if len(sys.argv) < 3:
        print("Usage: compile_ontology.py <ontology_dir> <output.zlp>")
        sys.exit(1)
        
    ontology_dir = Path(sys.argv[1])
    output_file = Path(sys.argv[2])
    
    all_facts = [
        "% AUTOGENERATED ZELPH FACTS FROM SENSIBLAW ONTOLOGY",
        ""
    ]
    
    # 1. Wikidata bodies
    wd_path = ontology_dir / "wikidata_bridge_bodies_gwb_v1.json"
    if wd_path.exists():
        all_facts.append("% --- Wikidata Bridge Bodies ---")
        with open(wd_path, "r") as f:
            all_facts.extend(compile_wikidata(json.load(f)))
        all_facts.append("")
        
    # 2. AU Semantic Linkage
    au_path = ontology_dir / "au_semantic_linkage_seed_v1.json"
    if au_path.exists():
        all_facts.append("% --- AU Semantic Linkage ---")
        with open(au_path, "r") as f:
            all_facts.extend(compile_au_linkage(json.load(f)))
        all_facts.append("")
        
    # 3. Wrong Types
    wt_path = ontology_dir / "wrong_type_catalog_seed.yaml"
    if wt_path.exists():
        all_facts.append("% --- Wrong Type Catalog ---")
        with open(wt_path, "r") as f:
            all_facts.extend(compile_wrong_types(yaml.safe_load(f)))
        all_facts.append("")
        
    with open(output_file, "w") as f:
        f.write("\n".join(all_facts))
        
    print(f"Successfully compiled flat ontology datasets into {output_file}")

if __name__ == "__main__":
    main()
