import sqlite3
import sys
from pathlib import Path

def quote(s):
    if not s:
        return '""'
    return '"' + str(s).replace('"', '\\"') + '"'

def make_atom_name(row_id):
    return f"db_atom_{row_id}"

def main():
    if len(sys.argv) < 3:
        print("Usage: python compile_db.py <db_path> <output.zlp>")
        sys.exit(1)
        
    db_path = Path(sys.argv[1])
    output_file = Path(sys.argv[2])
    
    if not db_path.exists():
        print(f"Error: Database {db_path} not found.")
        sys.exit(1)
        
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    facts = [
        "# AUTOGENERATED ZELPH FACTS FROM SENSIBLAW INGEST DB",
        ""
    ]
    
    # Extract rule atoms
    try:
        cursor.execute("SELECT doc_id, stable_id, party, role, modality, action, scope FROM rule_atoms LIMIT 500")
        rows = cursor.fetchall()
        for idx, row in enumerate(rows):
            uid = make_atom_name(idx)
            facts.append(f'{uid} "from document" doc_{row["doc_id"]}')
            facts.append(f'{uid} "stable id" {quote(row["stable_id"])}')
            
            if row["party"]:
                facts.append(f'{uid} "has party" {quote(row["party"])}')
            if row["role"]:
                facts.append(f'{uid} "has role" {quote(row["role"])}')
            if row["modality"]:
                facts.append(f'{uid} "has modality" {quote(row["modality"])}')
            if row["action"]:
                facts.append(f'{uid} "has action" {quote(row["action"])}')
            if row["scope"]:
                facts.append(f'{uid} "has scope" {quote(row["scope"])}')
    except sqlite3.OperationalError as e:
        print(f"Query error: {e}")
    
    with open(output_file, "w") as f:
        f.write("\n".join(facts))
        f.write("\n\n")
        f.write("# DB rules inference script\n\n")
        f.write("# Anything with modality 'modality.must' is an obligation on the party\n")
        f.write('(A "has modality" "modality.must", A "has party" P) => (P "has obligation" A)\n\n')
        f.write("# Anything with modality 'modality.may' is a permission\n")
        f.write('(A "has modality" "modality.may", A "has party" P) => (P "has permission" A)\n\n')
        f.write("# Queries -- Evaluated and printed live\n")
        f.write('P "has obligation" A\n')
        f.write('P "has permission" A\n')
        
    print(f"Successfully exported {len(rows)} SensibLaw DB atoms to {output_file}")

if __name__ == "__main__":
    main()
