BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Numeric corpus vocabulary. Text crosses this boundary once; all parser and
-- PNF execution joins use compact integer ids. Fixed-width BYTEA digests are
-- retained for deterministic identity without hexadecimal hot-path encoding.
CREATE TABLE IF NOT EXISTS execution.semantic_symbol_kind (
    kind_id SMALLINT PRIMARY KEY,
    kind_name TEXT NOT NULL UNIQUE
);

INSERT INTO execution.semantic_symbol_kind (kind_id, kind_name)
VALUES
    (1, 'orth'),
    (2, 'lemma'),
    (3, 'pos'),
    (4, 'tag'),
    (5, 'dependency'),
    (6, 'morph_feature'),
    (7, 'morph_value'),
    (8, 'entity_type'),
    (9, 'pipeline_component'),
    (10, 'factor_type'),
    (11, 'predicate'),
    (12, 'role'),
    (13, 'residual_type'),
    (14, 'object_kind'),
    (15, 'definition'),
    (16, 'scope'),
    (17, 'temporal'),
    (18, 'modal'),
    (19, 'grammatical')
ON CONFLICT (kind_id) DO UPDATE SET kind_name = EXCLUDED.kind_name;

CREATE TABLE IF NOT EXISTS execution.semantic_symbol (
    symbol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind_id SMALLINT NOT NULL
        REFERENCES execution.semantic_symbol_kind(kind_id) ON DELETE RESTRICT,
    symbol_text TEXT NOT NULL,
    symbol_digest BYTEA NOT NULL CHECK (octet_length(symbol_digest) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (kind_id, symbol_text),
    UNIQUE (kind_id, symbol_digest)
);

CREATE INDEX IF NOT EXISTS semantic_symbol_text_idx
    ON execution.semantic_symbol (kind_id, symbol_text);
CREATE INDEX IF NOT EXISTS semantic_symbol_digest_idx
    ON execution.semantic_symbol (kind_id, symbol_digest);

CREATE TABLE IF NOT EXISTS execution.semantic_morph_set (
    morph_set_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    morph_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(morph_digest) = 32),
    member_count SMALLINT NOT NULL CHECK (member_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS execution.semantic_morph_set_member (
    morph_set_id BIGINT NOT NULL
        REFERENCES execution.semantic_morph_set(morph_set_id) ON DELETE CASCADE,
    ordinal SMALLINT NOT NULL CHECK (ordinal >= 0),
    feature_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    value_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    PRIMARY KEY (morph_set_id, ordinal),
    UNIQUE (morph_set_id, feature_symbol_id, value_symbol_id)
);

-- Numeric parser occurrence identities. Legacy textual refs remain nullable
-- only for compatibility readers; representation_version=2 forbids their use
-- as authority and requires the numeric columns.
ALTER TABLE execution.semantic_parser_sentence
    ADD COLUMN IF NOT EXISTS sentence_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS sentence_digest BYTEA,
    ADD COLUMN IF NOT EXISTS representation_version SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE execution.semantic_parser_sentence
    DROP CONSTRAINT IF EXISTS semantic_parser_sentence_sentence_id_key;
ALTER TABLE execution.semantic_parser_sentence
    ADD CONSTRAINT semantic_parser_sentence_sentence_id_key UNIQUE (sentence_id);

ALTER TABLE execution.semantic_parser_sentence
    DROP CONSTRAINT IF EXISTS semantic_parser_sentence_digest_key;
ALTER TABLE execution.semantic_parser_sentence
    ADD CONSTRAINT semantic_parser_sentence_digest_key UNIQUE (sentence_digest);

ALTER TABLE execution.semantic_parser_token
    ALTER COLUMN orth_ref DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS token_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS token_digest BYTEA,
    ADD COLUMN IF NOT EXISTS orth_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS lemma_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS pos_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS tag_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS dependency_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS head_token_id BIGINT,
    ADD COLUMN IF NOT EXISTS morph_set_id BIGINT
        REFERENCES execution.semantic_morph_set(morph_set_id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS representation_version SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE execution.semantic_parser_token
    DROP CONSTRAINT IF EXISTS semantic_parser_token_token_id_key;
ALTER TABLE execution.semantic_parser_token
    ADD CONSTRAINT semantic_parser_token_token_id_key UNIQUE (token_id);

ALTER TABLE execution.semantic_parser_token
    DROP CONSTRAINT IF EXISTS semantic_parser_token_digest_key;
ALTER TABLE execution.semantic_parser_token
    ADD CONSTRAINT semantic_parser_token_digest_key UNIQUE (token_digest);

ALTER TABLE execution.semantic_parser_token
    DROP CONSTRAINT IF EXISTS semantic_parser_token_head_token_id_fkey;
ALTER TABLE execution.semantic_parser_token
    ADD CONSTRAINT semantic_parser_token_head_token_id_fkey
    FOREIGN KEY (head_token_id)
    REFERENCES execution.semantic_parser_token(token_id)
    ON DELETE RESTRICT
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE execution.semantic_parser_token
    DROP CONSTRAINT IF EXISTS semantic_parser_token_numeric_representation_ck;
ALTER TABLE execution.semantic_parser_token
    ADD CONSTRAINT semantic_parser_token_numeric_representation_ck CHECK (
        (representation_version = 1 AND orth_ref IS NOT NULL)
        OR
        (
            representation_version = 2
            AND orth_symbol_id IS NOT NULL
            AND orth_ref IS NULL
            AND lemma_ref IS NULL
            AND pos_ref IS NULL
            AND tag_ref IS NULL
            AND dependency_ref IS NULL
        )
    );

CREATE INDEX IF NOT EXISTS semantic_parser_token_numeric_sentence_idx
    ON execution.semantic_parser_token
       (sentence_ref, local_token_ordinal, token_id);
CREATE INDEX IF NOT EXISTS semantic_parser_token_numeric_dependency_idx
    ON execution.semantic_parser_token
       (sentence_ref, head_token_id, dependency_symbol_id);
CREATE INDEX IF NOT EXISTS semantic_parser_token_orth_symbol_idx
    ON execution.semantic_parser_token
       (orth_symbol_id, sentence_ref);
CREATE INDEX IF NOT EXISTS semantic_parser_token_lemma_symbol_idx
    ON execution.semantic_parser_token
       (lemma_symbol_id, sentence_ref);

ALTER TABLE execution.semantic_parser_entity_span
    ALTER COLUMN entity_type_ref DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS entity_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS entity_digest BYTEA,
    ADD COLUMN IF NOT EXISTS entity_type_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS representation_version SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE execution.semantic_parser_entity_span
    DROP CONSTRAINT IF EXISTS semantic_parser_entity_span_entity_id_key;
ALTER TABLE execution.semantic_parser_entity_span
    ADD CONSTRAINT semantic_parser_entity_span_entity_id_key UNIQUE (entity_id);

ALTER TABLE execution.semantic_parser_entity_span
    DROP CONSTRAINT IF EXISTS semantic_parser_entity_span_digest_key;
ALTER TABLE execution.semantic_parser_entity_span
    ADD CONSTRAINT semantic_parser_entity_span_digest_key UNIQUE (entity_digest);

ALTER TABLE execution.semantic_parser_entity_span
    DROP CONSTRAINT IF EXISTS semantic_parser_entity_numeric_representation_ck;
ALTER TABLE execution.semantic_parser_entity_span
    ADD CONSTRAINT semantic_parser_entity_numeric_representation_ck CHECK (
        (representation_version = 1 AND entity_type_ref IS NOT NULL)
        OR
        (
            representation_version = 2
            AND entity_type_symbol_id IS NOT NULL
            AND entity_type_ref IS NULL
        )
    );

-- Compact numeric enum codebooks. SMALLINT joins are the execution form;
-- names exist only for inspection and migration readability.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_region_kind (
    kind_id SMALLINT PRIMARY KEY,
    kind_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_region_kind VALUES
    (1, 'sentence'),
    (2, 'adjacent_sentence'),
    (3, 'paragraph'),
    (4, 'adjacent_paragraph'),
    (5, 'adaptive_block'),
    (6, 'provision'),
    (7, 'section'),
    (8, 'chapter'),
    (9, 'execution_window'),
    (10, 'document'),
    (11, 'tranche')
ON CONFLICT (kind_id) DO UPDATE SET kind_name = EXCLUDED.kind_name;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_edge_kind (
    kind_id SMALLINT PRIMARY KEY,
    kind_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_edge_kind VALUES
    (1, 'contains'),
    (2, 'adjacent'),
    (3, 'exports'),
    (4, 'resolves'),
    (5, 'supports'),
    (6, 'continues'),
    (7, 'execution_contains')
ON CONFLICT (kind_id) DO UPDATE SET kind_name = EXCLUDED.kind_name;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_closure_state (
    state_id SMALLINT PRIMARY KEY,
    state_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_closure_state VALUES
    (1, 'open'),
    (2, 'locally_closed'),
    (3, 'closed'),
    (4, 'failed')
ON CONFLICT (state_id) DO UPDATE SET state_name = EXCLUDED.state_name;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_export_kind (
    kind_id SMALLINT PRIMARY KEY,
    kind_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_export_kind VALUES
    (1, 'object'),
    (2, 'factor'),
    (3, 'definition'),
    (4, 'scope'),
    (5, 'demand'),
    (6, 'symbol_binding'),
    (7, 'temporal_state'),
    (8, 'modal_state')
ON CONFLICT (kind_id) DO UPDATE SET kind_name = EXCLUDED.kind_name;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_target_kind (
    kind_id SMALLINT PRIMARY KEY,
    kind_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_target_kind VALUES
    (1, 'object'),
    (2, 'factor'),
    (3, 'demand'),
    (4, 'definition'),
    (5, 'scope'),
    (6, 'token'),
    (7, 'sentence'),
    (8, 'region')
ON CONFLICT (kind_id) DO UPDATE SET kind_name = EXCLUDED.kind_name;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_work_operation (
    operation_id SMALLINT PRIMARY KEY,
    operation_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_work_operation VALUES
    (1, 'sentence_close'),
    (2, 'adjacent_reconcile'),
    (3, 'region_close'),
    (4, 'hierarchy_plan'),
    (5, 'document_close'),
    (6, 'visible_index_refresh')
ON CONFLICT (operation_id) DO UPDATE SET operation_name = EXCLUDED.operation_name;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_work_state (
    state_id SMALLINT PRIMARY KEY,
    state_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_work_state VALUES
    (1, 'ready'),
    (2, 'leased'),
    (3, 'completed'),
    (4, 'failed')
ON CONFLICT (state_id) DO UPDATE SET state_name = EXCLUDED.state_name;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_region (
    region_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(region_digest) = 32),
    run_ref TEXT NOT NULL
        REFERENCES execution.semantic_run(run_ref) ON DELETE CASCADE,
    document_ref TEXT NOT NULL,
    region_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_region_kind(kind_id) ON DELETE RESTRICT,
    start_char BIGINT NOT NULL CHECK (start_char >= 0),
    end_char BIGINT NOT NULL CHECK (end_char > start_char),
    sequence_no BIGINT NOT NULL CHECK (sequence_no >= 0),
    parent_region_id BIGINT
        REFERENCES execution.semantic_pnf_region(region_id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    closure_state SMALLINT NOT NULL DEFAULT 1
        REFERENCES execution.semantic_pnf_closure_state(state_id) ON DELETE RESTRICT,
    graph_revision BIGINT NOT NULL DEFAULT 0 CHECK (graph_revision >= 0),
    authored_boundary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ,
    UNIQUE (run_ref, document_ref, region_kind, start_char, end_char)
);

CREATE INDEX IF NOT EXISTS semantic_pnf_region_parent_idx
    ON execution.semantic_pnf_region (parent_region_id, sequence_no);
CREATE INDEX IF NOT EXISTS semantic_pnf_region_span_idx
    ON execution.semantic_pnf_region
       (run_ref, document_ref, start_char, end_char, region_kind);
CREATE INDEX IF NOT EXISTS semantic_pnf_region_state_idx
    ON execution.semantic_pnf_region
       (run_ref, document_ref, closure_state, region_kind, sequence_no);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_region_edge (
    edge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_region_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE,
    target_region_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE,
    edge_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_edge_kind(kind_id) ON DELETE RESTRICT,
    ordinal BIGINT NOT NULL DEFAULT 0 CHECK (ordinal >= 0),
    UNIQUE (source_region_id, target_region_id, edge_kind)
);

CREATE INDEX IF NOT EXISTS semantic_pnf_region_edge_target_idx
    ON execution.semantic_pnf_region_edge
       (target_region_id, edge_kind, source_region_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_sentence_region (
    sentence_id BIGINT PRIMARY KEY
        REFERENCES execution.semantic_parser_sentence(sentence_id) ON DELETE CASCADE,
    region_id BIGINT NOT NULL UNIQUE
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_interface (
    interface_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interface_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(interface_digest) = 32),
    region_id BIGINT NOT NULL UNIQUE
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE,
    parent_interface_id BIGINT
        REFERENCES execution.semantic_pnf_interface(interface_id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    closure_state SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_closure_state(state_id) ON DELETE RESTRICT,
    graph_revision BIGINT NOT NULL CHECK (graph_revision >= 0),
    node_count BIGINT NOT NULL DEFAULT 0 CHECK (node_count >= 0),
    edge_count BIGINT NOT NULL DEFAULT 0 CHECK (edge_count >= 0),
    alternative_count BIGINT NOT NULL DEFAULT 0 CHECK (alternative_count >= 0),
    unresolved_count BIGINT NOT NULL DEFAULT 0 CHECK (unresolved_count >= 0),
    boundary_demand_weight DOUBLE PRECISION NOT NULL DEFAULT 0
        CHECK (boundary_demand_weight >= 0),
    encoded_byte_count BIGINT NOT NULL DEFAULT 0 CHECK (encoded_byte_count >= 0),
    rule_count BIGINT NOT NULL DEFAULT 0 CHECK (rule_count >= 0),
    closure_rounds BIGINT NOT NULL DEFAULT 0 CHECK (closure_rounds >= 0),
    query_cost_ns BIGINT NOT NULL DEFAULT 0 CHECK (query_cost_ns >= 0),
    promoted_object_count BIGINT NOT NULL DEFAULT 0 CHECK (promoted_object_count >= 0),
    interface_cardinality BIGINT NOT NULL DEFAULT 0 CHECK (interface_cardinality >= 0),
    hierarchy_cost DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (hierarchy_cost >= 0),
    mdl_cost DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (mdl_cost >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS semantic_pnf_interface_parent_idx
    ON execution.semantic_pnf_interface (parent_interface_id, interface_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_interface_ancestor (
    interface_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE CASCADE,
    distance_power SMALLINT NOT NULL CHECK (distance_power BETWEEN 0 AND 62),
    ancestor_interface_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE CASCADE,
    distance BIGINT NOT NULL CHECK (distance > 0),
    PRIMARY KEY (interface_id, distance_power)
);

CREATE INDEX IF NOT EXISTS semantic_pnf_interface_ancestor_reverse_idx
    ON execution.semantic_pnf_interface_ancestor
       (ancestor_interface_id, distance_power, interface_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_interface_typed_ancestor (
    interface_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE CASCADE,
    ancestor_region_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_region_kind(kind_id) ON DELETE RESTRICT,
    ancestor_interface_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE CASCADE,
    distance BIGINT NOT NULL CHECK (distance > 0),
    PRIMARY KEY (interface_id, ancestor_region_kind)
);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_object (
    object_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(object_digest) = 32),
    region_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE,
    object_kind_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    head_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    scope_region_id BIGINT
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE RESTRICT,
    promotion_level SMALLINT NOT NULL DEFAULT 0 CHECK (promotion_level >= 0),
    information_gain DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (information_gain >= 0),
    representation_cost DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (representation_cost >= 0),
    ambiguity_cost DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (ambiguity_cost >= 0),
    promotion_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    visibility_start_char BIGINT,
    visibility_end_char BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        visibility_start_char IS NULL
        OR (
            visibility_end_char IS NOT NULL
            AND visibility_end_char >= visibility_start_char
        )
    )
);

CREATE INDEX IF NOT EXISTS semantic_pnf_object_region_idx
    ON execution.semantic_pnf_object
       (region_id, active, object_kind_symbol_id, head_symbol_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_object_token_support (
    object_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE CASCADE,
    token_id BIGINT NOT NULL
        REFERENCES execution.semantic_parser_token(token_id) ON DELETE RESTRICT,
    ordinal SMALLINT NOT NULL DEFAULT 0 CHECK (ordinal >= 0),
    PRIMARY KEY (object_id, token_id)
);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_factor (
    factor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factor_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(factor_digest) = 32),
    region_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE,
    factor_type_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    predicate_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    scope_region_id BIGINT
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE RESTRICT,
    temporal_state SMALLINT NOT NULL DEFAULT 0,
    modal_state SMALLINT NOT NULL DEFAULT 0,
    promotion_level SMALLINT NOT NULL DEFAULT 0 CHECK (promotion_level >= 0),
    support_score DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (support_score >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS semantic_pnf_factor_lookup_idx
    ON execution.semantic_pnf_factor
       (region_id, active, factor_type_symbol_id, predicate_symbol_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_hyperedge (
    factor_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_factor(factor_id) ON DELETE CASCADE,
    slot_ordinal SMALLINT NOT NULL CHECK (slot_ordinal >= 0),
    role_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    object_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE RESTRICT,
    resolution_state SMALLINT NOT NULL CHECK (resolution_state BETWEEN 1 AND 4),
    required BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (factor_id, slot_ordinal),
    UNIQUE (factor_id, role_symbol_id, object_id)
);

CREATE INDEX IF NOT EXISTS semantic_pnf_hyperedge_object_idx
    ON execution.semantic_pnf_hyperedge
       (object_id, role_symbol_id, factor_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_factor_token_support (
    factor_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_factor(factor_id) ON DELETE CASCADE,
    token_id BIGINT NOT NULL
        REFERENCES execution.semantic_parser_token(token_id) ON DELETE RESTRICT,
    ordinal SMALLINT NOT NULL CHECK (ordinal >= 0),
    PRIMARY KEY (factor_id, token_id),
    UNIQUE (factor_id, ordinal)
);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_demand (
    demand_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(demand_digest) = 32),
    source_interface_id BIGINT
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE CASCADE,
    source_region_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE,
    expected_target_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_target_kind(kind_id) ON DELETE RESTRICT,
    expected_factor_type_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    expected_object_kind_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    lexical_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    role_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    residual_type_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    recency_class SMALLINT NOT NULL CHECK (recency_class BETWEEN 1 AND 5),
    state SMALLINT NOT NULL DEFAULT 1 CHECK (state BETWEEN 1 AND 4),
    max_candidates SMALLINT NOT NULL DEFAULT 16 CHECK (max_candidates BETWEEN 1 AND 256),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_target_kind SMALLINT,
    resolved_target_id BIGINT
);

CREATE INDEX IF NOT EXISTS semantic_pnf_demand_open_idx
    ON execution.semantic_pnf_demand
       (source_region_id, state, expected_target_kind, expected_factor_type_symbol_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_interface_export (
    interface_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE CASCADE,
    export_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_export_kind(kind_id) ON DELETE RESTRICT,
    target_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_target_kind(kind_id) ON DELETE RESTRICT,
    target_id BIGINT NOT NULL,
    key_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    role_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    residual_type_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    rank BIGINT NOT NULL DEFAULT 0,
    promotion_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (interface_id, export_kind, target_kind, target_id)
);

CREATE INDEX IF NOT EXISTS semantic_pnf_interface_export_key_idx
    ON execution.semantic_pnf_interface_export
       (interface_id, export_kind, key_symbol_id, role_symbol_id, rank);
CREATE INDEX IF NOT EXISTS semantic_pnf_interface_export_factor_idx
    ON execution.semantic_pnf_interface_export
       (interface_id, target_kind, key_symbol_id, rank)
    WHERE target_kind = 2;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_interface_lookup (
    interface_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE CASCADE,
    key_kind SMALLINT NOT NULL CHECK (key_kind BETWEEN 1 AND 7),
    key_a BIGINT NOT NULL DEFAULT 0,
    key_b BIGINT NOT NULL DEFAULT 0,
    target_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_target_kind(kind_id) ON DELETE RESTRICT,
    target_id BIGINT NOT NULL,
    rank BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (
        interface_id, key_kind, key_a, key_b, target_kind, target_id
    )
);

CREATE INDEX IF NOT EXISTS semantic_pnf_interface_lookup_direct_idx
    ON execution.semantic_pnf_interface_lookup
       (interface_id, key_kind, key_a, key_b, rank, target_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_visible_lookup (
    interface_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE CASCADE,
    key_kind SMALLINT NOT NULL CHECK (key_kind BETWEEN 1 AND 7),
    key_a BIGINT NOT NULL DEFAULT 0,
    key_b BIGINT NOT NULL DEFAULT 0,
    target_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_target_kind(kind_id) ON DELETE RESTRICT,
    target_id BIGINT NOT NULL,
    source_interface_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE CASCADE,
    ancestor_distance BIGINT NOT NULL CHECK (ancestor_distance >= 0),
    rank BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (
        interface_id, key_kind, key_a, key_b,
        target_kind, target_id, source_interface_id
    )
);

CREATE INDEX IF NOT EXISTS semantic_pnf_visible_lookup_direct_idx
    ON execution.semantic_pnf_visible_lookup
       (interface_id, key_kind, key_a, key_b,
        ancestor_distance, rank, target_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_mdl_profile (
    profile_id SMALLINT PRIMARY KEY,
    node_weight DOUBLE PRECISION NOT NULL,
    edge_weight DOUBLE PRECISION NOT NULL,
    alternative_weight DOUBLE PRECISION NOT NULL,
    unresolved_weight DOUBLE PRECISION NOT NULL,
    boundary_weight DOUBLE PRECISION NOT NULL,
    encoded_byte_weight DOUBLE PRECISION NOT NULL,
    rule_weight DOUBLE PRECISION NOT NULL,
    closure_round_weight DOUBLE PRECISION NOT NULL,
    query_ns_weight DOUBLE PRECISION NOT NULL,
    promoted_object_weight DOUBLE PRECISION NOT NULL,
    interface_member_weight DOUBLE PRECISION NOT NULL,
    hierarchy_weight DOUBLE PRECISION NOT NULL,
    promotion_alpha DOUBLE PRECISION NOT NULL,
    promotion_beta DOUBLE PRECISION NOT NULL,
    promotion_threshold DOUBLE PRECISION NOT NULL,
    merge_threshold DOUBLE PRECISION NOT NULL,
    max_window SMALLINT NOT NULL CHECK (max_window BETWEEN 1 AND 256),
    beam_width SMALLINT NOT NULL CHECK (beam_width BETWEEN 1 AND 64)
);

INSERT INTO execution.semantic_pnf_mdl_profile VALUES (
    1,
    1.0, 0.75, 2.0, 3.0, 4.0,
    0.0009765625, 0.5, 1.0, 0.000001,
    0.25, 0.5, 0.25,
    1.0, 1.0, 0.0, 0.0,
    16, 4
)
ON CONFLICT (profile_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_work_item (
    work_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(work_digest) = 32),
    run_ref TEXT NOT NULL
        REFERENCES execution.semantic_run(run_ref) ON DELETE CASCADE,
    document_ref TEXT NOT NULL,
    region_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE,
    operation_id SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_work_operation(operation_id) ON DELETE RESTRICT,
    state_id SMALLINT NOT NULL DEFAULT 1
        REFERENCES execution.semantic_pnf_work_state(state_id) ON DELETE RESTRICT,
    priority SMALLINT NOT NULL DEFAULT 100,
    lease_owner TEXT,
    lease_token TEXT,
    lease_epoch BIGINT NOT NULL DEFAULT 0,
    lease_expires_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    last_error_code SMALLINT,
    UNIQUE (region_id, operation_id)
);

CREATE INDEX IF NOT EXISTS semantic_pnf_work_ready_idx
    ON execution.semantic_pnf_work_item
       (run_ref, state_id, priority, work_id)
    WHERE state_id IN (1, 2);

CREATE OR REPLACE FUNCTION execution.rebuild_pnf_interface_ancestors(
    selected_interface_id BIGINT
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    parent_id BIGINT;
    previous_ancestor BIGINT;
    next_ancestor BIGINT;
    power SMALLINT;
    distance_value BIGINT;
BEGIN
    DELETE FROM execution.semantic_pnf_interface_ancestor
     WHERE interface_id = selected_interface_id;
    DELETE FROM execution.semantic_pnf_interface_typed_ancestor
     WHERE interface_id = selected_interface_id;

    SELECT parent_interface_id
      INTO parent_id
      FROM execution.semantic_pnf_interface
     WHERE interface_id = selected_interface_id;

    IF parent_id IS NULL THEN
        RETURN;
    END IF;

    INSERT INTO execution.semantic_pnf_interface_ancestor
        (interface_id, distance_power, ancestor_interface_id, distance)
    VALUES (selected_interface_id, 0, parent_id, 1);

    previous_ancestor := parent_id;
    distance_value := 2;
    FOR power IN 1..62 LOOP
        SELECT ancestor_interface_id
          INTO next_ancestor
          FROM execution.semantic_pnf_interface_ancestor
         WHERE interface_id = previous_ancestor
           AND distance_power = power - 1;
        IF next_ancestor IS NULL THEN
            EXIT;
        END IF;
        INSERT INTO execution.semantic_pnf_interface_ancestor
            (interface_id, distance_power, ancestor_interface_id, distance)
        VALUES (
            selected_interface_id,
            power,
            next_ancestor,
            distance_value
        )
        ON CONFLICT (interface_id, distance_power) DO UPDATE SET
            ancestor_interface_id = EXCLUDED.ancestor_interface_id,
            distance = EXCLUDED.distance;
        previous_ancestor := next_ancestor;
        distance_value := distance_value * 2;
    END LOOP;

    WITH RECURSIVE chain(interface_id, distance) AS (
        SELECT parent_id, 1::BIGINT
        UNION ALL
        SELECT parent.parent_interface_id, chain.distance + 1
          FROM chain
          JOIN execution.semantic_pnf_interface AS parent
            ON parent.interface_id = chain.interface_id
         WHERE parent.parent_interface_id IS NOT NULL
    ),
    typed AS (
        SELECT DISTINCT ON (region.region_kind)
               region.region_kind,
               chain.interface_id,
               chain.distance
          FROM chain
          JOIN execution.semantic_pnf_interface AS interface
            ON interface.interface_id = chain.interface_id
          JOIN execution.semantic_pnf_region AS region
            ON region.region_id = interface.region_id
         ORDER BY region.region_kind, chain.distance
    )
    INSERT INTO execution.semantic_pnf_interface_typed_ancestor
        (interface_id, ancestor_region_kind, ancestor_interface_id, distance)
    SELECT selected_interface_id, region_kind, interface_id, distance
      FROM typed
    ON CONFLICT (interface_id, ancestor_region_kind) DO UPDATE SET
        ancestor_interface_id = EXCLUDED.ancestor_interface_id,
        distance = EXCLUDED.distance;
END;
$$;

CREATE OR REPLACE FUNCTION execution.refresh_pnf_visible_lookup(
    selected_run_ref TEXT,
    selected_document_ref TEXT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    inserted_count BIGINT;
BEGIN
    DELETE FROM execution.semantic_pnf_visible_lookup AS visible
    USING execution.semantic_pnf_interface AS interface,
          execution.semantic_pnf_region AS region
    WHERE visible.interface_id = interface.interface_id
      AND interface.region_id = region.region_id
      AND region.run_ref = selected_run_ref
      AND region.document_ref = selected_document_ref;

    WITH RECURSIVE chain(
        descendant_interface_id,
        ancestor_interface_id,
        distance
    ) AS (
        SELECT interface_id, interface_id, 0::BIGINT
          FROM execution.semantic_pnf_interface AS interface
          JOIN execution.semantic_pnf_region AS region
            ON region.region_id = interface.region_id
         WHERE region.run_ref = selected_run_ref
           AND region.document_ref = selected_document_ref
        UNION ALL
        SELECT chain.descendant_interface_id,
               parent.parent_interface_id,
               chain.distance + 1
          FROM chain
          JOIN execution.semantic_pnf_interface AS parent
            ON parent.interface_id = chain.ancestor_interface_id
         WHERE parent.parent_interface_id IS NOT NULL
    )
    INSERT INTO execution.semantic_pnf_visible_lookup
        (interface_id, key_kind, key_a, key_b,
         target_kind, target_id, source_interface_id,
         ancestor_distance, rank)
    SELECT chain.descendant_interface_id,
           lookup.key_kind,
           lookup.key_a,
           lookup.key_b,
           lookup.target_kind,
           lookup.target_id,
           chain.ancestor_interface_id,
           chain.distance,
           lookup.rank
      FROM chain
      JOIN execution.semantic_pnf_interface_lookup AS lookup
        ON lookup.interface_id = chain.ancestor_interface_id
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RETURN inserted_count;
END;
$$;

CREATE OR REPLACE FUNCTION execution.enqueue_numeric_sentence_region()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_region BIGINT;
    inserted_region BIGINT;
    digest_value BYTEA;
BEGIN
    IF NEW.representation_version <> 2 THEN
        RETURN NEW;
    END IF;

    SELECT region_id
      INTO parent_region
      FROM execution.semantic_pnf_region
     WHERE run_ref = NEW.run_ref
       AND document_ref = NEW.document_ref
       AND region_kind IN (3, 5, 6, 7, 8, 10)
       AND start_char <= NEW.start_char
       AND end_char >= NEW.end_char
     ORDER BY
       CASE region_kind
           WHEN 3 THEN 1
           WHEN 5 THEN 2
           WHEN 6 THEN 3
           WHEN 7 THEN 4
           WHEN 8 THEN 5
           ELSE 6
       END,
       end_char - start_char
     LIMIT 1;

    digest_value := digest(
        int8send(NEW.sentence_id)
        || int8send(NEW.start_char)
        || int8send(NEW.end_char),
        'sha256'
    );

    INSERT INTO execution.semantic_pnf_region
        (region_digest, run_ref, document_ref, region_kind,
         start_char, end_char, sequence_no, parent_region_id,
         closure_state, authored_boundary)
    VALUES (
        digest_value,
        NEW.run_ref,
        NEW.document_ref,
        1,
        NEW.start_char,
        NEW.end_char,
        NEW.start_char,
        parent_region,
        1,
        FALSE
    )
    ON CONFLICT (
        run_ref, document_ref, region_kind, start_char, end_char
    ) DO UPDATE SET parent_region_id = COALESCE(
        execution.semantic_pnf_region.parent_region_id,
        EXCLUDED.parent_region_id
    )
    RETURNING region_id INTO inserted_region;

    INSERT INTO execution.semantic_pnf_sentence_region
        (sentence_id, region_id)
    VALUES (NEW.sentence_id, inserted_region)
    ON CONFLICT (sentence_id) DO NOTHING;

    INSERT INTO execution.semantic_pnf_region_edge
        (source_region_id, target_region_id, edge_kind, ordinal)
    SELECT inserted_region, parent_region, 1, NEW.start_char
     WHERE parent_region IS NOT NULL
    ON CONFLICT DO NOTHING;

    INSERT INTO execution.semantic_pnf_work_item
        (work_digest, run_ref, document_ref, region_id,
         operation_id, state_id, priority)
    VALUES (
        digest(
            int8send(inserted_region) || int2send(1::SMALLINT),
            'sha256'
        ),
        NEW.run_ref,
        NEW.document_ref,
        inserted_region,
        1,
        1,
        10
    )
    ON CONFLICT (region_id, operation_id) DO NOTHING;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS semantic_numeric_sentence_region
    ON execution.semantic_parser_sentence;
CREATE TRIGGER semantic_numeric_sentence_region
AFTER INSERT ON execution.semantic_parser_sentence
FOR EACH ROW
EXECUTE FUNCTION execution.enqueue_numeric_sentence_region();

DROP TRIGGER IF EXISTS semantic_parser_sentence_graph_work
    ON execution.semantic_parser_sentence;
DROP TRIGGER IF EXISTS semantic_parser_document_graph_work
    ON execution.semantic_parser_document_coverage;

COMMIT;
