BEGIN;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_mention_kind (
    kind_id SMALLINT PRIMARY KEY,
    kind_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_mention_kind VALUES
    (1, 'parser_entity'),
    (2, 'noun'),
    (3, 'proper_noun'),
    (4, 'pronoun'),
    (5, 'defined_term'),
    (6, 'recurrence_member')
ON CONFLICT (kind_id) DO UPDATE SET kind_name = EXCLUDED.kind_name;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_mention (
    mention_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mention_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(mention_digest) = 32),
    region_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE,
    sentence_id BIGINT NOT NULL
        REFERENCES execution.semantic_parser_sentence(sentence_id) ON DELETE CASCADE,
    mention_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_mention_kind(kind_id) ON DELETE RESTRICT,
    start_char BIGINT NOT NULL CHECK (start_char >= 0),
    end_char BIGINT NOT NULL CHECK (end_char > start_char),
    head_token_id BIGINT NOT NULL
        REFERENCES execution.semantic_parser_token(token_id) ON DELETE RESTRICT,
    head_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    entity_type_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    grammatical_role_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    information_gain DOUBLE PRECISION NOT NULL CHECK (information_gain >= 0),
    representation_cost DOUBLE PRECISION NOT NULL CHECK (representation_cost >= 0),
    ambiguity_cost DOUBLE PRECISION NOT NULL CHECK (ambiguity_cost >= 0),
    promotion_score DOUBLE PRECISION NOT NULL,
    object_id BIGINT
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE SET NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (region_id, start_char, end_char, mention_kind)
);

CREATE INDEX IF NOT EXISTS semantic_pnf_mention_head_idx
    ON execution.semantic_pnf_mention
       (region_id, active, head_symbol_id, mention_kind);
CREATE INDEX IF NOT EXISTS semantic_pnf_mention_sentence_idx
    ON execution.semantic_pnf_mention
       (sentence_id, start_char, end_char, mention_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_mention_token (
    mention_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_mention(mention_id) ON DELETE CASCADE,
    token_id BIGINT NOT NULL
        REFERENCES execution.semantic_parser_token(token_id) ON DELETE RESTRICT,
    ordinal SMALLINT NOT NULL CHECK (ordinal >= 0),
    PRIMARY KEY (mention_id, token_id),
    UNIQUE (mention_id, ordinal)
);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_recurrence_group (
    recurrence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recurrence_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(recurrence_digest) = 32),
    region_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE,
    head_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    member_count BIGINT NOT NULL CHECK (member_count >= 2),
    object_id BIGINT
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (region_id, head_symbol_id)
);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_recurrence_member (
    recurrence_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_recurrence_group(recurrence_id)
        ON DELETE CASCADE,
    mention_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_mention(mention_id) ON DELETE RESTRICT,
    ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
    PRIMARY KEY (recurrence_id, mention_id),
    UNIQUE (recurrence_id, ordinal)
);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_object_mention_support (
    object_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE CASCADE,
    mention_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_mention(mention_id) ON DELETE RESTRICT,
    PRIMARY KEY (object_id, mention_id)
);

CREATE OR REPLACE FUNCTION execution.semantic_symbol_digest_value(
    selected_kind SMALLINT,
    selected_text TEXT
)
RETURNS BYTEA
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT digest(
        convert_to('symbol:v1', 'UTF8')
        || int2send(selected_kind)
        || int8send(octet_length(convert_to(selected_text, 'UTF8'))::BIGINT)
        || convert_to(selected_text, 'UTF8'),
        'sha256'
    )
$$;

CREATE OR REPLACE FUNCTION execution.ensure_semantic_symbol(
    selected_kind SMALLINT,
    selected_text TEXT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    result_id BIGINT;
BEGIN
    INSERT INTO execution.semantic_symbol
        (kind_id, symbol_text, symbol_digest)
    VALUES (
        selected_kind,
        selected_text,
        execution.semantic_symbol_digest_value(selected_kind, selected_text)
    )
    ON CONFLICT (kind_id, symbol_text) DO NOTHING;

    SELECT symbol_id
      INTO result_id
      FROM execution.semantic_symbol
     WHERE kind_id = selected_kind
       AND symbol_text = selected_text;
    IF result_id IS NULL THEN
        RAISE EXCEPTION 'failed to intern semantic symbol %, %',
            selected_kind, selected_text;
    END IF;
    RETURN result_id;
END;
$$;

CREATE OR REPLACE FUNCTION execution.derive_numeric_sentence_mentions()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    selected_sentence_id BIGINT;
    selected_interface_id BIGINT;
    profile RECORD;
    candidate RECORD;
    selected_mention_id BIGINT;
    selected_object_id BIGINT;
    selected_object_kind BIGINT;
    selected_role_symbol BIGINT;
    selected_residual_symbol BIGINT;
    candidate_score DOUBLE PRECISION;
    factor_participation BIGINT;
    candidate_kind SMALLINT;
    information_value DOUBLE PRECISION;
    ambiguity_value DOUBLE PRECISION;
BEGIN
    IF NEW.region_kind <> 1
       OR NEW.closure_state NOT IN (2, 3)
       OR OLD.closure_state IS NOT DISTINCT FROM NEW.closure_state THEN
        RETURN NEW;
    END IF;

    SELECT link.sentence_id, interface.interface_id
      INTO selected_sentence_id, selected_interface_id
      FROM execution.semantic_pnf_sentence_region AS link
      JOIN execution.semantic_pnf_interface AS interface
        ON interface.region_id = link.region_id
     WHERE link.region_id = NEW.region_id;
    IF selected_sentence_id IS NULL OR selected_interface_id IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT * INTO profile
      FROM execution.semantic_pnf_mdl_profile
     WHERE profile_id = 1;

    FOR candidate IN
        SELECT token.token_id,
               token.start_char,
               token.end_char,
               token.lemma_symbol_id AS head_symbol_id,
               token.dependency_symbol_id,
               pos.symbol_text AS pos_name,
               NULL::BIGINT AS entity_type_symbol_id
          FROM execution.semantic_parser_token AS token
          JOIN execution.semantic_symbol AS pos
            ON pos.symbol_id = token.pos_symbol_id
         WHERE token.sentence_id = selected_sentence_id
           AND pos.symbol_text IN ('NOUN', 'PROPN', 'PRON')
        UNION ALL
        SELECT head.token_id,
               entity.start_char,
               entity.end_char,
               head.lemma_symbol_id AS head_symbol_id,
               head.dependency_symbol_id,
               'ENTITY' AS pos_name,
               entity.entity_type_symbol_id
          FROM execution.semantic_parser_entity_span AS entity
          JOIN execution.semantic_parser_sentence AS sentence
            ON sentence.sentence_ref = entity.sentence_ref
          JOIN LATERAL (
              SELECT token.*
                FROM execution.semantic_parser_token AS token
               WHERE token.sentence_id = sentence.sentence_id
                 AND token.start_char >= entity.start_char
                 AND token.end_char <= entity.end_char
               ORDER BY token.start_char, token.token_id
               LIMIT 1
          ) AS head ON TRUE
         WHERE sentence.sentence_id = selected_sentence_id
           AND entity.representation_version = 2
    LOOP
        IF candidate.pos_name = 'ENTITY' THEN
            candidate_kind := 1;
            information_value := 4.0;
            ambiguity_value := 0.5;
            selected_object_kind := execution.ensure_semantic_symbol(
                14, 'mention.entity'
            );
        ELSIF candidate.pos_name = 'PROPN' THEN
            candidate_kind := 3;
            information_value := 3.0;
            ambiguity_value := 0.5;
            selected_object_kind := execution.ensure_semantic_symbol(
                14, 'mention.proper_noun'
            );
        ELSIF candidate.pos_name = 'PRON' THEN
            candidate_kind := 4;
            information_value := 1.0;
            ambiguity_value := 2.0;
            selected_object_kind := execution.ensure_semantic_symbol(
                14, 'mention.pronoun'
            );
        ELSE
            candidate_kind := 2;
            information_value := 2.0;
            ambiguity_value := 1.0;
            selected_object_kind := execution.ensure_semantic_symbol(
                14, 'mention.noun'
            );
        END IF;

        SELECT count(*)
          INTO factor_participation
          FROM execution.semantic_pnf_object_token_support AS support
          JOIN execution.semantic_pnf_hyperedge AS edge
            ON edge.object_id = support.object_id
         WHERE support.token_id = candidate.token_id;

        candidate_score := information_value
            + factor_participation
            - profile.promotion_alpha * 1.0
            - profile.promotion_beta * ambiguity_value;
        selected_role_symbol := execution.ensure_semantic_symbol(
            19,
            COALESCE(
                (
                    SELECT symbol_text
                      FROM execution.semantic_symbol
                     WHERE symbol_id = candidate.dependency_symbol_id
                ),
                'unknown'
            )
        );

        INSERT INTO execution.semantic_pnf_mention
            (mention_digest, region_id, sentence_id, mention_kind,
             start_char, end_char, head_token_id, head_symbol_id,
             entity_type_symbol_id, grammatical_role_symbol_id,
             information_gain, representation_cost, ambiguity_cost,
             promotion_score, active)
        VALUES (
            digest(
                int8send(NEW.region_id)
                || int8send(candidate.token_id)
                || int8send(candidate.start_char)
                || int8send(candidate.end_char)
                || int2send(candidate_kind),
                'sha256'
            ),
            NEW.region_id,
            selected_sentence_id,
            candidate_kind,
            candidate.start_char,
            candidate.end_char,
            candidate.token_id,
            candidate.head_symbol_id,
            candidate.entity_type_symbol_id,
            selected_role_symbol,
            information_value,
            1.0,
            ambiguity_value,
            candidate_score,
            TRUE
        )
        ON CONFLICT (region_id, start_char, end_char, mention_kind)
        DO UPDATE SET promotion_score = EXCLUDED.promotion_score
        RETURNING mention_id, object_id
        INTO selected_mention_id, selected_object_id;

        INSERT INTO execution.semantic_pnf_mention_token
            (mention_id, token_id, ordinal)
        SELECT selected_mention_id,
               token.token_id,
               row_number() OVER (
                   ORDER BY token.start_char, token.token_id
               ) - 1
          FROM execution.semantic_parser_token AS token
         WHERE token.sentence_id = selected_sentence_id
           AND token.start_char >= candidate.start_char
           AND token.end_char <= candidate.end_char
        ON CONFLICT DO NOTHING;

        IF selected_object_id IS NULL THEN
            SELECT support.object_id
              INTO selected_object_id
              FROM execution.semantic_pnf_object_token_support AS support
              JOIN execution.semantic_pnf_object AS object
                ON object.object_id = support.object_id
             WHERE support.token_id = candidate.token_id
               AND object.region_id = NEW.region_id
             ORDER BY object.object_id
             LIMIT 1;
        END IF;

        IF selected_object_id IS NULL
           AND (
               candidate_score > profile.promotion_threshold
               OR factor_participation > 0
           ) THEN
            INSERT INTO execution.semantic_pnf_object
                (object_digest, region_id, object_kind_symbol_id,
                 head_symbol_id, scope_region_id, promotion_level,
                 information_gain, representation_cost, ambiguity_cost,
                 promotion_score, active)
            VALUES (
                digest(
                    int8send(selected_mention_id)
                    || int8send(NEW.region_id)
                    || int8send(selected_object_kind),
                    'sha256'
                ),
                NEW.region_id,
                selected_object_kind,
                candidate.head_symbol_id,
                NEW.region_id,
                0,
                information_value,
                1.0,
                ambiguity_value,
                candidate_score,
                TRUE
            )
            ON CONFLICT (object_digest) DO UPDATE SET active = TRUE
            RETURNING object_id INTO selected_object_id;

            INSERT INTO execution.semantic_pnf_object_token_support
                (object_id, token_id, ordinal)
            VALUES (selected_object_id, candidate.token_id, 0)
            ON CONFLICT DO NOTHING;
        END IF;

        IF selected_object_id IS NOT NULL THEN
            UPDATE execution.semantic_pnf_mention
               SET object_id = selected_object_id
             WHERE mention_id = selected_mention_id;
            INSERT INTO execution.semantic_pnf_object_mention_support
                (object_id, mention_id)
            VALUES (selected_object_id, selected_mention_id)
            ON CONFLICT DO NOTHING;
            INSERT INTO execution.semantic_pnf_interface_export
                (interface_id, export_kind, target_kind, target_id,
                 key_symbol_id, role_symbol_id, rank, promotion_score)
            VALUES (
                selected_interface_id,
                1,
                1,
                selected_object_id,
                candidate.head_symbol_id,
                selected_role_symbol,
                candidate.start_char,
                candidate_score
            )
            ON CONFLICT DO NOTHING;
            INSERT INTO execution.semantic_pnf_interface_lookup
                (interface_id, key_kind, key_a, key_b,
                 target_kind, target_id, rank)
            VALUES (
                selected_interface_id,
                3,
                candidate.head_symbol_id,
                selected_role_symbol,
                1,
                selected_object_id,
                candidate.start_char
            )
            ON CONFLICT DO NOTHING;
        END IF;

        IF candidate_kind = 4 THEN
            selected_residual_symbol := execution.ensure_semantic_symbol(
                13, 'anaphor_unresolved'
            );
            INSERT INTO execution.semantic_pnf_demand
                (demand_digest, source_interface_id, source_region_id,
                 expected_target_kind, expected_object_kind_symbol_id,
                 lexical_symbol_id, role_symbol_id,
                 residual_type_symbol_id, recency_class,
                 state, max_candidates)
            VALUES (
                digest(
                    int8send(selected_mention_id)
                    || int8send(selected_residual_symbol),
                    'sha256'
                ),
                selected_interface_id,
                NEW.region_id,
                1,
                selected_object_kind,
                candidate.head_symbol_id,
                selected_role_symbol,
                selected_residual_symbol,
                3,
                1,
                16
            )
            ON CONFLICT (demand_digest) DO NOTHING;
        END IF;
    END LOOP;

    UPDATE execution.semantic_pnf_interface AS interface
       SET interface_cardinality = counts.total_count,
           promoted_object_count = counts.object_count,
           unresolved_count = counts.demand_count
      FROM (
          SELECT count(*) AS total_count,
                 count(*) FILTER (WHERE target_kind = 1) AS object_count,
                 count(*) FILTER (WHERE target_kind = 3) AS demand_count
            FROM execution.semantic_pnf_interface_export
           WHERE interface_id = selected_interface_id
      ) AS counts
     WHERE interface.interface_id = selected_interface_id;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION execution.derive_numeric_region_recurrence()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    selected_interface_id BIGINT;
    selected_object_kind BIGINT;
    candidate RECORD;
    selected_recurrence_id BIGINT;
    selected_object_id BIGINT;
BEGIN
    IF NEW.region_kind = 1
       OR NEW.closure_state NOT IN (2, 3)
       OR OLD.closure_state IS NOT DISTINCT FROM NEW.closure_state THEN
        RETURN NEW;
    END IF;

    SELECT interface_id
      INTO selected_interface_id
      FROM execution.semantic_pnf_interface
     WHERE region_id = NEW.region_id;
    IF selected_interface_id IS NULL THEN
        RETURN NEW;
    END IF;
    selected_object_kind := execution.ensure_semantic_symbol(
        14, 'mention.recurrence_group'
    );

    FOR candidate IN
        WITH RECURSIVE descendants(region_id) AS (
            SELECT child.region_id
              FROM execution.semantic_pnf_region AS child
             WHERE child.parent_region_id = NEW.region_id
            UNION ALL
            SELECT child.region_id
              FROM descendants
              JOIN execution.semantic_pnf_region AS child
                ON child.parent_region_id = descendants.region_id
        )
        SELECT mention.head_symbol_id,
               count(*) AS member_count
          FROM descendants
          JOIN execution.semantic_pnf_mention AS mention
            ON mention.region_id = descendants.region_id
         WHERE mention.active
         GROUP BY mention.head_symbol_id
        HAVING count(*) >= 2
    LOOP
        INSERT INTO execution.semantic_pnf_recurrence_group
            (recurrence_digest, region_id, head_symbol_id, member_count)
        VALUES (
            digest(
                int8send(NEW.region_id)
                || int8send(candidate.head_symbol_id)
                || int8send(candidate.member_count),
                'sha256'
            ),
            NEW.region_id,
            candidate.head_symbol_id,
            candidate.member_count
        )
        ON CONFLICT (region_id, head_symbol_id)
        DO UPDATE SET member_count = EXCLUDED.member_count
        RETURNING recurrence_id, object_id
        INTO selected_recurrence_id, selected_object_id;

        WITH RECURSIVE descendants(region_id) AS (
            SELECT child.region_id
              FROM execution.semantic_pnf_region AS child
             WHERE child.parent_region_id = NEW.region_id
            UNION ALL
            SELECT child.region_id
              FROM descendants
              JOIN execution.semantic_pnf_region AS child
                ON child.parent_region_id = descendants.region_id
        ),
        members AS (
            SELECT mention.mention_id,
                   row_number() OVER (
                       ORDER BY mention.start_char, mention.mention_id
                   ) - 1 AS ordinal
              FROM descendants
              JOIN execution.semantic_pnf_mention AS mention
                ON mention.region_id = descendants.region_id
             WHERE mention.active
               AND mention.head_symbol_id = candidate.head_symbol_id
        )
        INSERT INTO execution.semantic_pnf_recurrence_member
            (recurrence_id, mention_id, ordinal)
        SELECT selected_recurrence_id, mention_id, ordinal
          FROM members
        ON CONFLICT DO NOTHING;

        IF selected_object_id IS NULL THEN
            INSERT INTO execution.semantic_pnf_object
                (object_digest, region_id, object_kind_symbol_id,
                 head_symbol_id, scope_region_id, promotion_level,
                 information_gain, representation_cost, ambiguity_cost,
                 promotion_score, active)
            VALUES (
                digest(
                    int8send(selected_recurrence_id)
                    || int8send(NEW.region_id)
                    || int8send(selected_object_kind),
                    'sha256'
                ),
                NEW.region_id,
                selected_object_kind,
                candidate.head_symbol_id,
                NEW.region_id,
                NEW.region_kind,
                candidate.member_count,
                1.0,
                0.5,
                candidate.member_count - 1.5,
                TRUE
            )
            ON CONFLICT (object_digest) DO UPDATE SET active = TRUE
            RETURNING object_id INTO selected_object_id;
            UPDATE execution.semantic_pnf_recurrence_group
               SET object_id = selected_object_id
             WHERE recurrence_id = selected_recurrence_id;
        END IF;

        INSERT INTO execution.semantic_pnf_object_mention_support
            (object_id, mention_id)
        SELECT selected_object_id, mention_id
          FROM execution.semantic_pnf_recurrence_member
         WHERE recurrence_id = selected_recurrence_id
        ON CONFLICT DO NOTHING;

        INSERT INTO execution.semantic_pnf_interface_export
            (interface_id, export_kind, target_kind, target_id,
             key_symbol_id, rank, promotion_score)
        VALUES (
            selected_interface_id,
            1,
            1,
            selected_object_id,
            candidate.head_symbol_id,
            0,
            candidate.member_count - 1.5
        )
        ON CONFLICT DO NOTHING;
        INSERT INTO execution.semantic_pnf_interface_lookup
            (interface_id, key_kind, key_a, key_b,
             target_kind, target_id, rank)
        VALUES (
            selected_interface_id,
            3,
            candidate.head_symbol_id,
            0,
            1,
            selected_object_id,
            0
        )
        ON CONFLICT DO NOTHING;
    END LOOP;

    UPDATE execution.semantic_pnf_interface AS interface
       SET interface_cardinality = counts.total_count,
           promoted_object_count = counts.object_count,
           unresolved_count = counts.demand_count
      FROM (
          SELECT count(*) AS total_count,
                 count(*) FILTER (WHERE target_kind = 1) AS object_count,
                 count(*) FILTER (WHERE target_kind = 3) AS demand_count
            FROM execution.semantic_pnf_interface_export
           WHERE interface_id = selected_interface_id
      ) AS counts
     WHERE interface.interface_id = selected_interface_id;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS semantic_pnf_sentence_mention_derivation
    ON execution.semantic_pnf_region;
CREATE TRIGGER semantic_pnf_sentence_mention_derivation
AFTER UPDATE OF closure_state
ON execution.semantic_pnf_region
FOR EACH ROW
EXECUTE FUNCTION execution.derive_numeric_sentence_mentions();

DROP TRIGGER IF EXISTS semantic_pnf_region_recurrence_derivation
    ON execution.semantic_pnf_region;
CREATE TRIGGER semantic_pnf_region_recurrence_derivation
AFTER UPDATE OF closure_state
ON execution.semantic_pnf_region
FOR EACH ROW
EXECUTE FUNCTION execution.derive_numeric_region_recurrence();

COMMIT;
