BEGIN;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_run_identity (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_ref TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_document_identity (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_ref TEXT NOT NULL UNIQUE
);

INSERT INTO execution.semantic_pnf_run_identity (run_ref)
SELECT DISTINCT run_ref
  FROM execution.semantic_pnf_region
ON CONFLICT (run_ref) DO NOTHING;
INSERT INTO execution.semantic_pnf_document_identity (document_ref)
SELECT DISTINCT document_ref
  FROM execution.semantic_pnf_region
ON CONFLICT (document_ref) DO NOTHING;

ALTER TABLE execution.semantic_pnf_region
    ADD COLUMN IF NOT EXISTS run_id BIGINT
        REFERENCES execution.semantic_pnf_run_identity(run_id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS document_id BIGINT
        REFERENCES execution.semantic_pnf_document_identity(document_id)
        ON DELETE CASCADE;

UPDATE execution.semantic_pnf_region AS region
   SET run_id = run_identity.run_id,
       document_id = document_identity.document_id
  FROM execution.semantic_pnf_run_identity AS run_identity,
       execution.semantic_pnf_document_identity AS document_identity
 WHERE run_identity.run_ref = region.run_ref
   AND document_identity.document_ref = region.document_ref
   AND (region.run_id IS NULL OR region.document_id IS NULL);

ALTER TABLE execution.semantic_pnf_region
    ALTER COLUMN run_id SET NOT NULL,
    ALTER COLUMN document_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS semantic_pnf_region_numeric_scope_idx
    ON execution.semantic_pnf_region
       (run_id, document_id, region_kind, sequence_no, region_id);

CREATE OR REPLACE FUNCTION execution.assign_numeric_pnf_scope_ids()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.run_id IS NULL THEN
        INSERT INTO execution.semantic_pnf_run_identity (run_ref)
        VALUES (NEW.run_ref)
        ON CONFLICT (run_ref) DO NOTHING;
        SELECT run_id INTO NEW.run_id
          FROM execution.semantic_pnf_run_identity
         WHERE run_ref = NEW.run_ref;
    END IF;
    IF NEW.document_id IS NULL THEN
        INSERT INTO execution.semantic_pnf_document_identity (document_ref)
        VALUES (NEW.document_ref)
        ON CONFLICT (document_ref) DO NOTHING;
        SELECT document_id INTO NEW.document_id
          FROM execution.semantic_pnf_document_identity
         WHERE document_ref = NEW.document_ref;
    END IF;
    IF NEW.run_id IS NULL OR NEW.document_id IS NULL THEN
        RAISE EXCEPTION 'failed to assign numeric PNF run/document identity';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS semantic_pnf_region_numeric_scope
    ON execution.semantic_pnf_region;
CREATE TRIGGER semantic_pnf_region_numeric_scope
BEFORE INSERT OR UPDATE OF run_ref, document_ref
ON execution.semantic_pnf_region
FOR EACH ROW
EXECUTE FUNCTION execution.assign_numeric_pnf_scope_ids();

ALTER TABLE execution.semantic_pnf_work_item
    ADD COLUMN IF NOT EXISTS run_id BIGINT
        REFERENCES execution.semantic_pnf_run_identity(run_id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS document_id BIGINT
        REFERENCES execution.semantic_pnf_document_identity(document_id)
        ON DELETE CASCADE;

UPDATE execution.semantic_pnf_work_item AS work
   SET run_id = region.run_id,
       document_id = region.document_id
  FROM execution.semantic_pnf_region AS region
 WHERE region.region_id = work.region_id
   AND (work.run_id IS NULL OR work.document_id IS NULL);

ALTER TABLE execution.semantic_pnf_work_item
    ALTER COLUMN run_id SET NOT NULL,
    ALTER COLUMN document_id SET NOT NULL;

CREATE OR REPLACE FUNCTION execution.assign_numeric_pnf_work_scope()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.run_id IS NULL OR NEW.document_id IS NULL THEN
        SELECT run_id, document_id
          INTO NEW.run_id, NEW.document_id
          FROM execution.semantic_pnf_region
         WHERE region_id = NEW.region_id;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS semantic_pnf_work_numeric_scope
    ON execution.semantic_pnf_work_item;
CREATE TRIGGER semantic_pnf_work_numeric_scope
BEFORE INSERT OR UPDATE OF region_id
ON execution.semantic_pnf_work_item
FOR EACH ROW
EXECUTE FUNCTION execution.assign_numeric_pnf_work_scope();

CREATE INDEX IF NOT EXISTS semantic_pnf_work_numeric_ready_idx
    ON execution.semantic_pnf_work_item
       (run_id, document_id, state_id, priority, work_id);

ALTER TABLE execution.semantic_pnf_global_lookup
    ADD COLUMN IF NOT EXISTS run_id BIGINT
        REFERENCES execution.semantic_pnf_run_identity(run_id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS document_id BIGINT
        REFERENCES execution.semantic_pnf_document_identity(document_id)
        ON DELETE CASCADE;

UPDATE execution.semantic_pnf_global_lookup AS global
   SET run_id = region.run_id,
       document_id = region.document_id
  FROM execution.semantic_pnf_region AS region
 WHERE region.region_id = global.region_id
   AND (global.run_id IS NULL OR global.document_id IS NULL);

ALTER TABLE execution.semantic_pnf_global_lookup
    ALTER COLUMN run_id SET NOT NULL,
    ALTER COLUMN document_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS semantic_pnf_global_lookup_numeric_exact_idx
    ON execution.semantic_pnf_global_lookup
       (run_id, document_id, key_kind, key_a, key_b,
        target_kind, region_end_char DESC, rank, target_id);
CREATE INDEX IF NOT EXISTS semantic_pnf_global_lookup_numeric_target_idx
    ON execution.semantic_pnf_global_lookup
       (run_id, document_id, target_kind, target_id, interface_id);

CREATE OR REPLACE FUNCTION execution.refresh_pnf_global_lookup_ids(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    inserted_count BIGINT;
BEGIN
    DELETE FROM execution.semantic_pnf_global_lookup
     WHERE run_id = selected_run_id
       AND document_id = selected_document_id;

    INSERT INTO execution.semantic_pnf_global_lookup
        (run_ref, document_ref, run_id, document_id,
         interface_id, region_id, region_kind,
         region_start_char, region_end_char,
         key_kind, key_a, key_b, target_kind, target_id, rank)
    SELECT region.run_ref,
           region.document_ref,
           region.run_id,
           region.document_id,
           lookup.interface_id,
           region.region_id,
           region.region_kind,
           region.start_char,
           region.end_char,
           lookup.key_kind,
           lookup.key_a,
           lookup.key_b,
           lookup.target_kind,
           lookup.target_id,
           lookup.rank
      FROM execution.semantic_pnf_interface_lookup AS lookup
      JOIN execution.semantic_pnf_interface AS interface
        ON interface.interface_id = lookup.interface_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = interface.region_id
     WHERE region.run_id = selected_run_id
       AND region.document_id = selected_document_id
       AND interface.closure_state IN (2, 3)
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RETURN inserted_count;
END;
$$;

CREATE OR REPLACE FUNCTION execution.refresh_pnf_global_lookup(
    selected_run_ref TEXT,
    selected_document_ref TEXT
)
RETURNS BIGINT
LANGUAGE sql
AS $$
    SELECT execution.refresh_pnf_global_lookup_ids(
        (SELECT run_id
           FROM execution.semantic_pnf_run_identity
          WHERE run_ref = selected_run_ref),
        (SELECT document_id
           FROM execution.semantic_pnf_document_identity
          WHERE document_ref = selected_document_ref)
    )
$$;

CREATE OR REPLACE FUNCTION execution.plan_numeric_pnf_demand_candidates_ids(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    demand_row RECORD;
    inserted_total BIGINT := 0;
    inserted_for_demand BIGINT;
    anaphor_residual_id BIGINT;
    pronoun_kind_id BIGINT;
BEGIN
    SELECT symbol_id INTO anaphor_residual_id
      FROM execution.semantic_symbol
     WHERE kind_id = 13 AND symbol_text = 'anaphor_unresolved';
    SELECT symbol_id INTO pronoun_kind_id
      FROM execution.semantic_symbol
     WHERE kind_id = 14 AND symbol_text = 'mention.pronoun';

    FOR demand_row IN
        SELECT demand.*
          FROM execution.semantic_pnf_demand AS demand
          JOIN execution.semantic_pnf_region AS source_region
            ON source_region.region_id = demand.source_region_id
         WHERE source_region.run_id = selected_run_id
           AND source_region.document_id = selected_document_id
           AND demand.source_interface_id IS NOT NULL
           AND demand.state IN (1, 2)
         ORDER BY demand.demand_id
    LOOP
        DELETE FROM execution.semantic_pnf_demand_candidate
         WHERE demand_id = demand_row.demand_id;

        INSERT INTO execution.semantic_pnf_demand_candidate
            (demand_id, ordinal, target_kind, target_id,
             source_interface_id, ancestor_distance,
             index_rank, candidate_score)
        SELECT demand_row.demand_id,
               row_number() OVER (
                   ORDER BY candidate.structural_distance,
                            candidate.index_rank,
                            candidate.target_id
               ) - 1,
               candidate.target_kind,
               candidate.target_id,
               candidate.source_interface_id,
               candidate.structural_distance,
               candidate.index_rank,
               candidate.candidate_score
          FROM LATERAL (
              SELECT DISTINCT ON (global.target_kind, global.target_id)
                     global.target_kind,
                     global.target_id,
                     global.interface_id AS source_interface_id,
                     abs(
                         COALESCE(demand_row.source_start_char, 0)
                         - global.region_end_char
                     ) AS structural_distance,
                     global.rank AS index_rank,
                     COALESCE(object.promotion_score, factor.support_score, 0)
                         AS candidate_score
                FROM execution.semantic_pnf_global_lookup AS global
                LEFT JOIN execution.semantic_pnf_object AS object
                  ON global.target_kind = 1
                 AND object.object_id = global.target_id
                LEFT JOIN execution.semantic_pnf_factor AS factor
                  ON global.target_kind = 2
                 AND factor.factor_id = global.target_id
               WHERE global.run_id = selected_run_id
                 AND global.document_id = selected_document_id
                 AND global.target_kind = demand_row.expected_target_kind
                 AND global.target_id <> demand_row.demand_id
                 AND (
                     (
                         demand_row.residual_type_symbol_id = anaphor_residual_id
                         AND global.target_kind = 1
                         AND global.region_id <> demand_row.source_region_id
                         AND (
                             pronoun_kind_id IS NULL
                             OR object.object_kind_symbol_id <> pronoun_kind_id
                         )
                         AND global.region_end_char
                             <= COALESCE(
                                 demand_row.source_start_char,
                                 global.region_end_char
                             )
                     )
                     OR (
                         demand_row.expected_factor_type_symbol_id IS NOT NULL
                         AND global.key_kind = 1
                         AND global.key_a
                             = demand_row.expected_factor_type_symbol_id
                     )
                     OR (
                         demand_row.expected_object_kind_symbol_id IS NOT NULL
                         AND global.key_kind = 2
                         AND global.key_a
                             = demand_row.expected_object_kind_symbol_id
                     )
                     OR (
                         demand_row.lexical_symbol_id IS NOT NULL
                         AND global.key_kind = 3
                         AND global.key_a = demand_row.lexical_symbol_id
                     )
                     OR (
                         global.key_kind = 5
                         AND global.key_a
                             = demand_row.residual_type_symbol_id
                     )
                 )
               ORDER BY global.target_kind,
                        global.target_id,
                        structural_distance,
                        global.rank
               LIMIT demand_row.max_candidates
          ) AS candidate;

        GET DIAGNOSTICS inserted_for_demand = ROW_COUNT;
        inserted_total := inserted_total + inserted_for_demand;
        UPDATE execution.semantic_pnf_demand
           SET candidate_count = inserted_for_demand,
               state = CASE WHEN inserted_for_demand > 0 THEN 2 ELSE state END
         WHERE demand_id = demand_row.demand_id;
    END LOOP;

    UPDATE execution.semantic_pnf_demand AS demand
       SET state = 3
      FROM execution.semantic_pnf_region AS source_region
     WHERE source_region.region_id = demand.source_region_id
       AND source_region.run_id = selected_run_id
       AND source_region.document_id = selected_document_id
       AND demand.state = 1
       AND demand.candidate_count = 0
       AND EXISTS (
           SELECT 1
             FROM execution.semantic_pnf_region AS document_region
            WHERE document_region.run_id = selected_run_id
              AND document_region.document_id = selected_document_id
              AND document_region.region_kind = 10
              AND document_region.closure_state = 3
       );
    RETURN inserted_total;
END;
$$;

CREATE OR REPLACE FUNCTION execution.plan_numeric_pnf_demand_candidates(
    selected_run_ref TEXT,
    selected_document_ref TEXT
)
RETURNS BIGINT
LANGUAGE sql
AS $$
    SELECT execution.plan_numeric_pnf_demand_candidates_ids(
        (SELECT run_id
           FROM execution.semantic_pnf_run_identity
          WHERE run_ref = selected_run_ref),
        (SELECT document_id
           FROM execution.semantic_pnf_document_identity
          WHERE document_ref = selected_document_ref)
    )
$$;

CREATE OR REPLACE FUNCTION execution.plan_demands_after_global_lookup_refresh()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    selected RECORD;
BEGIN
    FOR selected IN
        SELECT DISTINCT run_id, document_id
          FROM inserted_global
    LOOP
        PERFORM execution.plan_numeric_pnf_demand_candidates_ids(
            selected.run_id,
            selected.document_id
        );
    END LOOP;
    RETURN NULL;
END;
$$;

COMMIT;
