BEGIN;

-- Proof-relevant identity fibres ------------------------------------------------
--
-- Local objects remain immutable textual evidence.  Identity is represented as
-- a separate witnessed projection from a local object into a canonical entity.
-- No paragraph co-presence, lexical proximity, or co-occurrence relation is an
-- identity witness.

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_identity_authority_class (
    authority_class SMALLINT PRIMARY KEY,
    authority_name TEXT NOT NULL UNIQUE,
    world_canonical BOOLEAN NOT NULL DEFAULT FALSE
);
INSERT INTO execution.semantic_pnf_identity_authority_class
    (authority_class, authority_name, world_canonical)
VALUES
    (1, 'surface_local', FALSE),
    (2, 'document_derived', FALSE),
    (3, 'corpus_derived', FALSE),
    (4, 'external_authority', TRUE)
ON CONFLICT (authority_class) DO UPDATE SET
    authority_name = EXCLUDED.authority_name,
    world_canonical = EXCLUDED.world_canonical;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_identity_witness_kind (
    witness_kind SMALLINT PRIMARY KEY,
    witness_name TEXT NOT NULL UNIQUE,
    default_authority_class SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_identity_authority_class(authority_class)
        ON DELETE RESTRICT,
    symmetric_identity BOOLEAN NOT NULL DEFAULT TRUE
);
INSERT INTO execution.semantic_pnf_identity_witness_kind
    (witness_kind, witness_name, default_authority_class, symmetric_identity)
VALUES
    (1, 'resolution_anchor', 2, TRUE),
    (2, 'apposition', 2, TRUE),
    (3, 'proper_name_expansion', 2, TRUE),
    (4, 'title_role_closure', 2, TRUE),
    (5, 'anaphor_demand_resolution', 2, TRUE),
    (6, 'explicit_alias', 2, TRUE),
    (7, 'definition_equivalence', 2, TRUE),
    (8, 'typed_demand_unique', 2, TRUE),
    (9, 'corpus_identity_closure', 3, TRUE),
    (10, 'external_authority_alignment', 4, TRUE)
ON CONFLICT (witness_kind) DO UPDATE SET
    witness_name = EXCLUDED.witness_name,
    default_authority_class = EXCLUDED.default_authority_class,
    symmetric_identity = EXCLUDED.symmetric_identity;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_identity_admission_state (
    admission_state SMALLINT PRIMARY KEY,
    admission_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_identity_admission_state
    (admission_state, admission_name)
VALUES
    (1, 'candidate'),
    (2, 'accepted'),
    (3, 'rejected'),
    (4, 'superseded')
ON CONFLICT (admission_state) DO UPDATE
SET admission_name = EXCLUDED.admission_name;

-- A canonical entity is a base object for identity fibres.  A document-derived
-- entity is anchored to one local object.  It is *not* a claim that the anchor
-- is a world-unique person.  External/world identity requires authority_class 4
-- and an explicit authority namespace + identifier.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_canonical_entity (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_ref TEXT NOT NULL UNIQUE,
    authority_class SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_identity_authority_class(authority_class)
        ON DELETE RESTRICT,
    canonical_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    anchor_object_id BIGINT
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE RESTRICT,
    authority_namespace TEXT,
    authority_identifier TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        authority_class <> 4
        OR (
            authority_namespace IS NOT NULL
            AND authority_identifier IS NOT NULL
        )
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS semantic_pnf_canonical_entity_anchor_idx
    ON execution.semantic_pnf_canonical_entity(anchor_object_id)
    WHERE anchor_object_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS semantic_pnf_canonical_entity_external_idx
    ON execution.semantic_pnf_canonical_entity(
        authority_namespace, authority_identifier
    )
    WHERE authority_class = 4;

-- Demands need an explicit source object before they can prove identity.  The
-- backfill below is intentionally conservative: it binds only when one and only
-- one object in the demand's own source region has the recorded surface symbol.
ALTER TABLE execution.semantic_pnf_demand
    ADD COLUMN IF NOT EXISTS source_object_id BIGINT
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS semantic_pnf_demand_source_object_idx
    ON execution.semantic_pnf_demand(source_object_id, state, demand_id)
    WHERE source_object_id IS NOT NULL;

CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_demand_source_objects(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    affected_count BIGINT := 0;
BEGIN
    WITH candidate AS (
        SELECT demand.demand_id,
               object.object_id,
               count(*) OVER (PARTITION BY demand.demand_id) AS candidate_count
          FROM execution.semantic_pnf_demand AS demand
          JOIN execution.semantic_pnf_region AS source_region
            ON source_region.region_id = demand.source_region_id
          JOIN execution.semantic_pnf_object AS object
            ON object.region_id = demand.source_region_id
           AND object.head_symbol_id = COALESCE(
               demand.surface_lexical_symbol_id,
               demand.lexical_symbol_id
           )
         WHERE source_region.run_id = selected_run_id
           AND source_region.document_id = selected_document_id
           AND demand.source_object_id IS NULL
           AND COALESCE(
               demand.surface_lexical_symbol_id,
               demand.lexical_symbol_id
           ) IS NOT NULL
    ),
    unique_candidate AS (
        SELECT demand_id, min(object_id) AS object_id
          FROM candidate
         WHERE candidate_count = 1
         GROUP BY demand_id
    )
    UPDATE execution.semantic_pnf_demand AS demand
       SET source_object_id = unique_candidate.object_id
      FROM unique_candidate
     WHERE demand.demand_id = unique_candidate.demand_id
       AND demand.source_object_id IS NULL;
    GET DIAGNOSTICS affected_count = ROW_COUNT;
    RETURN affected_count;
END;
$$;

-- Witness rows are immutable evidence.  Current admission/retraction is kept in
-- a separate relation so provenance survives a later change of judgement.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_identity_witness (
    witness_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_object_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE RESTRICT,
    target_entity_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_canonical_entity(entity_id)
        ON DELETE RESTRICT,
    witness_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_identity_witness_kind(witness_kind)
        ON DELETE RESTRICT,
    authority_class SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_identity_authority_class(authority_class)
        ON DELETE RESTRICT,
    source_interface_id BIGINT
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE SET NULL,
    demand_id BIGINT
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE SET NULL,
    resolution_interface_id BIGINT
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE SET NULL,
    candidate_count SMALLINT NOT NULL DEFAULT 1
        CHECK (candidate_count BETWEEN 0 AND 256),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS semantic_pnf_identity_witness_natural_idx
    ON execution.semantic_pnf_identity_witness(
        source_object_id,
        target_entity_id,
        witness_kind,
        COALESCE(demand_id, 0),
        COALESCE(resolution_interface_id, 0)
    );
CREATE INDEX IF NOT EXISTS semantic_pnf_identity_witness_source_idx
    ON execution.semantic_pnf_identity_witness(
        source_object_id, authority_class, target_entity_id, witness_id
    );
CREATE INDEX IF NOT EXISTS semantic_pnf_identity_witness_target_idx
    ON execution.semantic_pnf_identity_witness(
        target_entity_id, authority_class, source_object_id, witness_id
    );

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_identity_witness_admission (
    witness_id BIGINT PRIMARY KEY
        REFERENCES execution.semantic_pnf_identity_witness(witness_id)
        ON DELETE RESTRICT,
    admission_state SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_identity_admission_state(admission_state)
        ON DELETE RESTRICT,
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    admitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS semantic_pnf_identity_admission_current_idx
    ON execution.semantic_pnf_identity_witness_admission(
        admission_state, witness_id
    );

-- Each typed constraint that survived unique resolution is retained as part of
-- the witness proof.  This is proof provenance, not a recomputed interpretation.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_identity_witness_constraint (
    witness_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_identity_witness(witness_id)
        ON DELETE CASCADE,
    constraint_ordinal SMALLINT NOT NULL,
    key_kind SMALLINT NOT NULL,
    key_a BIGINT NOT NULL,
    key_b BIGINT NOT NULL DEFAULT 0,
    polarity SMALLINT NOT NULL,
    satisfied BOOLEAN NOT NULL,
    PRIMARY KEY (witness_id, constraint_ordinal)
);

-- Accepted witnesses project local objects into entity fibres only when all
-- accepted witnesses at an authority class agree on one target entity.  If two
-- accepted targets conflict, no projection is produced: ambiguity remains
-- explicit rather than being collapsed by preference ordering.
CREATE OR REPLACE VIEW execution.semantic_pnf_identity_projection AS
SELECT witness.source_object_id,
       witness.authority_class,
       min(witness.target_entity_id) AS target_entity_id,
       array_agg(witness.witness_id ORDER BY witness.witness_id) AS witness_ids,
       count(*)::BIGINT AS witness_count
  FROM execution.semantic_pnf_identity_witness AS witness
  JOIN execution.semantic_pnf_identity_witness_admission AS admission
    ON admission.witness_id = witness.witness_id
   AND admission.admission_state = 2
 GROUP BY witness.source_object_id, witness.authority_class
HAVING count(DISTINCT witness.target_entity_id) = 1;

CREATE OR REPLACE VIEW execution.semantic_pnf_identity_fibre_member AS
SELECT projection.target_entity_id AS entity_id,
       projection.source_object_id AS object_id,
       projection.authority_class,
       projection.witness_ids,
       projection.witness_count
  FROM execution.semantic_pnf_identity_projection AS projection;

-- Direct hyperedges remain Level 1.  A Level 3 row exists only when an admitted
-- proof-relevant identity projection exists.  There is no paragraph-co-scope
-- branch in this view.
CREATE OR REPLACE VIEW execution.semantic_pnf_witnessed_hyperedge AS
SELECT edge.factor_id,
       edge.slot_ordinal,
       edge.role_symbol_id,
       edge.object_id AS surface_object_id,
       NULL::BIGINT AS identity_entity_id,
       NULL::SMALLINT AS identity_authority_class,
       NULL::BIGINT[] AS identity_witness_ids,
       1::SMALLINT AS epistemic_level
  FROM execution.semantic_pnf_hyperedge AS edge
UNION ALL
SELECT edge.factor_id,
       edge.slot_ordinal,
       edge.role_symbol_id,
       edge.object_id AS surface_object_id,
       projection.target_entity_id AS identity_entity_id,
       projection.authority_class AS identity_authority_class,
       projection.witness_ids AS identity_witness_ids,
       3::SMALLINT AS epistemic_level
  FROM execution.semantic_pnf_hyperedge AS edge
  JOIN execution.semantic_pnf_identity_projection AS projection
    ON projection.source_object_id = edge.object_id;

-- Set-based materialisation from *resolved_unique* frontier proof objects only.
-- A candidate list, paragraph membership, surface similarity, or no_witness row
-- can never create an identity witness.
CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_identity_witnesses(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    affected_count BIGINT := 0;
BEGIN
    PERFORM execution.refresh_numeric_pnf_demand_source_objects(
        selected_run_id,
        selected_document_id
    );

    -- Create one document-local canonical base for every uniquely selected
    -- object target.  The base is anchored to the object's immutable digest.
    INSERT INTO execution.semantic_pnf_canonical_entity
        (entity_ref, authority_class, canonical_symbol_id, anchor_object_id)
    SELECT 'document-object:' || encode(target.object_digest, 'hex'),
           2,
           target.head_symbol_id,
           target.object_id
      FROM execution.semantic_pnf_frontier_resolution AS resolution
      JOIN execution.semantic_pnf_demand AS demand
        ON demand.demand_id = resolution.demand_id
      JOIN execution.semantic_pnf_region AS source_region
        ON source_region.region_id = demand.source_region_id
      JOIN execution.semantic_pnf_object AS target
        ON target.object_id = resolution.selected_target_id
     WHERE source_region.run_id = selected_run_id
       AND source_region.document_id = selected_document_id
       AND resolution.outcome_state = 2
       AND resolution.selected_target_kind = 1
    ON CONFLICT DO NOTHING;

    -- Anchor the selected object itself to that document-local base.
    INSERT INTO execution.semantic_pnf_identity_witness
        (source_object_id, target_entity_id, witness_kind, authority_class,
         source_interface_id, demand_id, resolution_interface_id,
         candidate_count)
    SELECT target.object_id,
           entity.entity_id,
           1,
           2,
           resolution.witness_interface_id,
           NULL,
           resolution.interface_id,
           1
      FROM execution.semantic_pnf_frontier_resolution AS resolution
      JOIN execution.semantic_pnf_demand AS demand
        ON demand.demand_id = resolution.demand_id
      JOIN execution.semantic_pnf_region AS source_region
        ON source_region.region_id = demand.source_region_id
      JOIN execution.semantic_pnf_object AS target
        ON target.object_id = resolution.selected_target_id
      JOIN execution.semantic_pnf_canonical_entity AS entity
        ON entity.anchor_object_id = target.object_id
     WHERE source_region.run_id = selected_run_id
       AND source_region.document_id = selected_document_id
       AND resolution.outcome_state = 2
       AND resolution.selected_target_kind = 1
    ON CONFLICT DO NOTHING;

    -- Project the demand's source object only when the frontier supplied an
    -- explicit unique target proof.  Anaphors are one witness kind among many;
    -- the mechanism itself is generic.
    INSERT INTO execution.semantic_pnf_identity_witness
        (source_object_id, target_entity_id, witness_kind, authority_class,
         source_interface_id, demand_id, resolution_interface_id,
         candidate_count)
    SELECT demand.source_object_id,
           entity.entity_id,
           CASE
               WHEN residual.symbol_text = 'anaphor_unresolved' THEN 5
               ELSE 8
           END,
           2,
           demand.source_interface_id,
           demand.demand_id,
           resolution.interface_id,
           resolution.candidate_count
      FROM execution.semantic_pnf_frontier_resolution AS resolution
      JOIN execution.semantic_pnf_demand AS demand
        ON demand.demand_id = resolution.demand_id
      JOIN execution.semantic_pnf_region AS source_region
        ON source_region.region_id = demand.source_region_id
      JOIN execution.semantic_pnf_object AS target
        ON target.object_id = resolution.selected_target_id
      JOIN execution.semantic_pnf_canonical_entity AS entity
        ON entity.anchor_object_id = target.object_id
      LEFT JOIN execution.semantic_symbol AS residual
        ON residual.symbol_id = demand.residual_type_symbol_id
     WHERE source_region.run_id = selected_run_id
       AND source_region.document_id = selected_document_id
       AND resolution.outcome_state = 2
       AND resolution.selected_target_kind = 1
       AND resolution.candidate_count = 1
       AND demand.source_object_id IS NOT NULL
       AND demand.source_object_id <> target.object_id
    ON CONFLICT DO NOTHING;

    -- Accepted admission is explicit and separate from immutable witness rows.
    INSERT INTO execution.semantic_pnf_identity_witness_admission
        (witness_id, admission_state, revision)
    SELECT witness.witness_id, 2, 1
      FROM execution.semantic_pnf_identity_witness AS witness
      JOIN execution.semantic_pnf_object AS source
        ON source.object_id = witness.source_object_id
      JOIN execution.semantic_pnf_region AS source_region
        ON source_region.region_id = source.region_id
     WHERE source_region.run_id = selected_run_id
       AND source_region.document_id = selected_document_id
       AND witness.authority_class = 2
    ON CONFLICT (witness_id) DO NOTHING;

    -- Preserve the exact typed constraint conjunction associated with each
    -- demand-derived identity proof.
    INSERT INTO execution.semantic_pnf_identity_witness_constraint
        (witness_id, constraint_ordinal, key_kind, key_a, key_b,
         polarity, satisfied)
    SELECT witness.witness_id,
           constraint_row.ordinal,
           constraint_row.key_kind,
           constraint_row.key_a,
           constraint_row.key_b,
           constraint_row.polarity,
           TRUE
      FROM execution.semantic_pnf_identity_witness AS witness
      JOIN execution.semantic_pnf_demand_constraint AS constraint_row
        ON constraint_row.demand_id = witness.demand_id
      JOIN execution.semantic_pnf_object AS source
        ON source.object_id = witness.source_object_id
      JOIN execution.semantic_pnf_region AS source_region
        ON source_region.region_id = source.region_id
     WHERE source_region.run_id = selected_run_id
       AND source_region.document_id = selected_document_id
       AND witness.demand_id IS NOT NULL
    ON CONFLICT DO NOTHING;

    SELECT count(*)
      INTO affected_count
      FROM execution.semantic_pnf_identity_witness AS witness
      JOIN execution.semantic_pnf_object AS source
        ON source.object_id = witness.source_object_id
      JOIN execution.semantic_pnf_region AS source_region
        ON source_region.region_id = source.region_id
     WHERE source_region.run_id = selected_run_id
       AND source_region.document_id = selected_document_id;

    RETURN affected_count;
END;
$$;

COMMIT;
