BEGIN;

-- Proof-relevant factor derivations -------------------------------------------
--
-- Factors are immutable Level-1 structural evidence.  Derived propositions are
-- separate rows that retain their premise factors, argument provenance, and any
-- identity-witness path used for substitution.

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_derivation_state (
    derivation_state SMALLINT PRIMARY KEY,
    derivation_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_derivation_state
    (derivation_state, derivation_name)
VALUES
    (1, 'candidate'),
    (2, 'admitted'),
    (3, 'rejected'),
    (4, 'superseded')
ON CONFLICT (derivation_state) DO UPDATE
SET derivation_name = EXCLUDED.derivation_name;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_derivation_kind (
    derivation_kind SMALLINT PRIMARY KEY,
    derivation_name TEXT NOT NULL UNIQUE
);
INSERT INTO execution.semantic_pnf_derivation_kind
    (derivation_kind, derivation_name)
VALUES
    (1, 'identity_substitution'),
    (2, 'factor_composition')
ON CONFLICT (derivation_kind) DO UPDATE
SET derivation_name = EXCLUDED.derivation_name;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_factor_derivation_rule (
    rule_ref TEXT PRIMARY KEY,
    derivation_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_derivation_kind(derivation_kind)
        ON DELETE RESTRICT,
    rule_version BIGINT NOT NULL DEFAULT 1 CHECK (rule_version > 0),
    description TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO execution.semantic_pnf_factor_derivation_rule
    (rule_ref, derivation_kind, rule_version, description, enabled)
VALUES
    (
        'identity-substitution:v1',
        1,
        1,
        'Substitute a local factor argument by an admitted proof-relevant identity projection; preserve predicate, modality, temporality and all unprojected arguments.',
        TRUE
    ),
    (
        'shared-argument-composition:candidate-v1',
        2,
        1,
        'Structural composition candidate only: two factors share the same local object or the same admitted identity entity within one local region. No semantic conclusion is licensed by this rule alone.',
        TRUE
    )
ON CONFLICT (rule_ref) DO UPDATE SET
    derivation_kind = EXCLUDED.derivation_kind,
    rule_version = EXCLUDED.rule_version,
    description = EXCLUDED.description,
    enabled = EXCLUDED.enabled;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_factor_derivation (
    derivation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    derivation_ref TEXT NOT NULL UNIQUE,
    rule_ref TEXT NOT NULL
        REFERENCES execution.semantic_pnf_factor_derivation_rule(rule_ref)
        ON DELETE RESTRICT,
    derivation_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_derivation_kind(derivation_kind)
        ON DELETE RESTRICT,
    derivation_state SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_derivation_state(derivation_state)
        ON DELETE RESTRICT,
    epistemic_level SMALLINT NOT NULL CHECK (epistemic_level BETWEEN 1 AND 4),
    authority_class SMALLINT
        REFERENCES execution.semantic_pnf_identity_authority_class(authority_class)
        ON DELETE RESTRICT,
    scope_interface_id BIGINT
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE SET NULL,
    conclusion_factor_type_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    conclusion_predicate_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    modal_state SMALLINT NOT NULL DEFAULT 0,
    temporal_state SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS semantic_pnf_factor_derivation_scope_idx
    ON execution.semantic_pnf_factor_derivation(
        scope_interface_id, derivation_state, derivation_kind, derivation_id
    );
CREATE INDEX IF NOT EXISTS semantic_pnf_factor_derivation_predicate_idx
    ON execution.semantic_pnf_factor_derivation(
        conclusion_predicate_symbol_id, derivation_state, derivation_id
    );

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_factor_derivation_premise (
    derivation_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_factor_derivation(derivation_id)
        ON DELETE CASCADE,
    premise_ordinal SMALLINT NOT NULL CHECK (premise_ordinal BETWEEN 0 AND 31),
    factor_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_factor(factor_id) ON DELETE RESTRICT,
    PRIMARY KEY (derivation_id, premise_ordinal),
    UNIQUE (derivation_id, factor_id)
);
CREATE INDEX IF NOT EXISTS semantic_pnf_factor_derivation_premise_factor_idx
    ON execution.semantic_pnf_factor_derivation_premise(
        factor_id, derivation_id
    );

-- Exactly one carrier is active for each derived argument: either the original
-- local object or an identity entity.  witness_ids is mandatory for an identity
-- substitution and makes the substitution itself auditable.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_factor_derivation_argument (
    derivation_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_factor_derivation(derivation_id)
        ON DELETE CASCADE,
    slot_ordinal SMALLINT NOT NULL CHECK (slot_ordinal >= 0),
    role_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    source_object_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE RESTRICT,
    local_object_id BIGINT
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE RESTRICT,
    identity_entity_id BIGINT
        REFERENCES execution.semantic_pnf_canonical_entity(entity_id)
        ON DELETE RESTRICT,
    identity_witness_ids BIGINT[],
    PRIMARY KEY (derivation_id, slot_ordinal),
    CHECK (
        (local_object_id IS NOT NULL AND identity_entity_id IS NULL)
        OR
        (local_object_id IS NULL AND identity_entity_id IS NOT NULL)
    ),
    CHECK (
        identity_entity_id IS NULL
        OR (
            identity_witness_ids IS NOT NULL
            AND cardinality(identity_witness_ids) > 0
        )
    )
);
CREATE INDEX IF NOT EXISTS semantic_pnf_factor_derivation_argument_object_idx
    ON execution.semantic_pnf_factor_derivation_argument(
        local_object_id, role_symbol_id, derivation_id
    )
    WHERE local_object_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS semantic_pnf_factor_derivation_argument_entity_idx
    ON execution.semantic_pnf_factor_derivation_argument(
        identity_entity_id, role_symbol_id, derivation_id
    )
    WHERE identity_entity_id IS NOT NULL;

-- Structural factor-composition candidates.  These are not propositions.  They
-- merely say that two immutable factors possess a proof-relevant bridge suitable
-- for a later rule.  The candidate is bounded per bridge and local region.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_factor_composition_candidate (
    candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_interface_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_interface(interface_id)
        ON DELETE CASCADE,
    region_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE CASCADE,
    left_factor_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_factor(factor_id) ON DELETE CASCADE,
    right_factor_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_factor(factor_id) ON DELETE CASCADE,
    left_role_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    right_role_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    bridge_object_id BIGINT
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE CASCADE,
    bridge_entity_id BIGINT
        REFERENCES execution.semantic_pnf_canonical_entity(entity_id)
        ON DELETE CASCADE,
    identity_authority_class SMALLINT
        REFERENCES execution.semantic_pnf_identity_authority_class(authority_class)
        ON DELETE RESTRICT,
    candidate_rank SMALLINT NOT NULL CHECK (candidate_rank BETWEEN 0 AND 255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (left_factor_id < right_factor_id),
    CHECK (
        (bridge_object_id IS NOT NULL AND bridge_entity_id IS NULL)
        OR
        (bridge_object_id IS NULL AND bridge_entity_id IS NOT NULL)
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS semantic_pnf_factor_composition_local_uq
    ON execution.semantic_pnf_factor_composition_candidate(
        region_id, left_factor_id, right_factor_id,
        left_role_symbol_id, right_role_symbol_id, bridge_object_id
    )
    WHERE bridge_object_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS semantic_pnf_factor_composition_entity_uq
    ON execution.semantic_pnf_factor_composition_candidate(
        region_id, left_factor_id, right_factor_id,
        left_role_symbol_id, right_role_symbol_id,
        bridge_entity_id, identity_authority_class
    )
    WHERE bridge_entity_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS semantic_pnf_factor_composition_bridge_object_idx
    ON execution.semantic_pnf_factor_composition_candidate(
        bridge_object_id, region_id, candidate_rank
    )
    WHERE bridge_object_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS semantic_pnf_factor_composition_bridge_entity_idx
    ON execution.semantic_pnf_factor_composition_candidate(
        bridge_entity_id, identity_authority_class,
        region_id, candidate_rank
    )
    WHERE bridge_entity_id IS NOT NULL;

CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_identity_substitution_derivations(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    affected_count BIGINT := 0;
BEGIN
    -- One derivation per factor and identity authority class.  This prevents an
    -- external authority alignment from silently replacing a document-derived
    -- identity claim; downstream queries choose the authority surface explicitly.
    INSERT INTO execution.semantic_pnf_factor_derivation
        (derivation_ref, rule_ref, derivation_kind, derivation_state,
         epistemic_level, authority_class, scope_interface_id,
         conclusion_factor_type_symbol_id, conclusion_predicate_symbol_id,
         modal_state, temporal_state)
    SELECT 'identity-substitution:' || factor.factor_id::TEXT || ':'
               || projection.authority_class::TEXT,
           'identity-substitution:v1',
           1,
           2,
           3,
           projection.authority_class,
           interface.interface_id,
           factor.factor_type_symbol_id,
           factor.predicate_symbol_id,
           factor.modal_state,
           factor.temporal_state
      FROM execution.semantic_pnf_factor AS factor
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = factor.region_id
      JOIN execution.semantic_pnf_interface AS interface
        ON interface.region_id = region.region_id
      JOIN execution.semantic_pnf_hyperedge AS edge
        ON edge.factor_id = factor.factor_id
      JOIN execution.semantic_pnf_identity_projection AS projection
        ON projection.source_object_id = edge.object_id
     WHERE region.run_id = selected_run_id
       AND region.document_id = selected_document_id
     GROUP BY factor.factor_id,
              projection.authority_class,
              interface.interface_id,
              factor.factor_type_symbol_id,
              factor.predicate_symbol_id,
              factor.modal_state,
              factor.temporal_state
    ON CONFLICT (derivation_ref) DO NOTHING;

    INSERT INTO execution.semantic_pnf_factor_derivation_premise
        (derivation_id, premise_ordinal, factor_id)
    SELECT derivation.derivation_id, 0, factor.factor_id
      FROM execution.semantic_pnf_factor_derivation AS derivation
      JOIN execution.semantic_pnf_factor AS factor
        ON derivation.derivation_ref =
           'identity-substitution:' || factor.factor_id::TEXT || ':'
           || derivation.authority_class::TEXT
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = factor.region_id
     WHERE derivation.rule_ref = 'identity-substitution:v1'
       AND region.run_id = selected_run_id
       AND region.document_id = selected_document_id
    ON CONFLICT DO NOTHING;

    INSERT INTO execution.semantic_pnf_factor_derivation_argument
        (derivation_id, slot_ordinal, role_symbol_id, source_object_id,
         local_object_id, identity_entity_id, identity_witness_ids)
    SELECT derivation.derivation_id,
           edge.slot_ordinal,
           edge.role_symbol_id,
           edge.object_id,
           CASE WHEN projection.target_entity_id IS NULL
                THEN edge.object_id ELSE NULL END,
           projection.target_entity_id,
           projection.witness_ids
      FROM execution.semantic_pnf_factor_derivation AS derivation
      JOIN execution.semantic_pnf_factor_derivation_premise AS premise
        ON premise.derivation_id = derivation.derivation_id
       AND premise.premise_ordinal = 0
      JOIN execution.semantic_pnf_factor AS factor
        ON factor.factor_id = premise.factor_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = factor.region_id
      JOIN execution.semantic_pnf_hyperedge AS edge
        ON edge.factor_id = factor.factor_id
      LEFT JOIN execution.semantic_pnf_identity_projection AS projection
        ON projection.source_object_id = edge.object_id
       AND projection.authority_class = derivation.authority_class
     WHERE derivation.rule_ref = 'identity-substitution:v1'
       AND region.run_id = selected_run_id
       AND region.document_id = selected_document_id
    ON CONFLICT (derivation_id, slot_ordinal) DO NOTHING;

    SELECT count(*)
      INTO affected_count
      FROM execution.semantic_pnf_factor_derivation AS derivation
      JOIN execution.semantic_pnf_factor_derivation_premise AS premise
        ON premise.derivation_id = derivation.derivation_id
      JOIN execution.semantic_pnf_factor AS factor
        ON factor.factor_id = premise.factor_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = factor.region_id
     WHERE derivation.rule_ref = 'identity-substitution:v1'
       AND region.run_id = selected_run_id
       AND region.document_id = selected_document_id;
    RETURN affected_count;
END;
$$;

CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_factor_composition_candidates(
    selected_run_id BIGINT,
    selected_document_id BIGINT,
    max_per_bridge INTEGER DEFAULT 16
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    inserted_count BIGINT := 0;
    identity_inserted_count BIGINT := 0;
BEGIN
    IF max_per_bridge < 1 OR max_per_bridge > 256 THEN
        RAISE EXCEPTION 'max_per_bridge must be between 1 and 256';
    END IF;

    DELETE FROM execution.semantic_pnf_factor_composition_candidate AS candidate
    USING execution.semantic_pnf_region AS region
     WHERE candidate.region_id = region.region_id
       AND region.run_id = selected_run_id
       AND region.document_id = selected_document_id;

    -- Exact local-object bridge.
    WITH raw AS (
        SELECT region.region_id,
               interface.interface_id AS source_interface_id,
               left_edge.factor_id AS left_factor_id,
               right_edge.factor_id AS right_factor_id,
               left_edge.role_symbol_id AS left_role_symbol_id,
               right_edge.role_symbol_id AS right_role_symbol_id,
               left_edge.object_id AS bridge_object_id,
               row_number() OVER (
                   PARTITION BY region.region_id, left_edge.object_id
                   ORDER BY left_edge.factor_id, right_edge.factor_id,
                            left_edge.slot_ordinal, right_edge.slot_ordinal
               ) - 1 AS candidate_rank
          FROM execution.semantic_pnf_hyperedge AS left_edge
          JOIN execution.semantic_pnf_factor AS left_factor
            ON left_factor.factor_id = left_edge.factor_id
          JOIN execution.semantic_pnf_hyperedge AS right_edge
            ON right_edge.object_id = left_edge.object_id
           AND right_edge.factor_id > left_edge.factor_id
          JOIN execution.semantic_pnf_factor AS right_factor
            ON right_factor.factor_id = right_edge.factor_id
           AND right_factor.region_id = left_factor.region_id
          JOIN execution.semantic_pnf_region AS region
            ON region.region_id = left_factor.region_id
          JOIN execution.semantic_pnf_interface AS interface
            ON interface.region_id = region.region_id
         WHERE region.run_id = selected_run_id
           AND region.document_id = selected_document_id
    )
    INSERT INTO execution.semantic_pnf_factor_composition_candidate
        (source_interface_id, region_id,
         left_factor_id, right_factor_id,
         left_role_symbol_id, right_role_symbol_id,
         bridge_object_id, bridge_entity_id,
         identity_authority_class, candidate_rank)
    SELECT source_interface_id,
           region_id,
           left_factor_id,
           right_factor_id,
           left_role_symbol_id,
           right_role_symbol_id,
           bridge_object_id,
           NULL,
           NULL,
           candidate_rank::SMALLINT
      FROM raw
     WHERE candidate_rank < max_per_bridge
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS inserted_count = ROW_COUNT;

    -- Proof-relevant identity bridge.  Distinct local objects may compose only
    -- when both project to the same entity at the same explicit authority class.
    WITH projected_edge AS (
        SELECT edge.factor_id,
               edge.slot_ordinal,
               edge.role_symbol_id,
               edge.object_id,
               factor.region_id,
               projection.target_entity_id,
               projection.authority_class
          FROM execution.semantic_pnf_hyperedge AS edge
          JOIN execution.semantic_pnf_factor AS factor
            ON factor.factor_id = edge.factor_id
          JOIN execution.semantic_pnf_region AS region
            ON region.region_id = factor.region_id
          JOIN execution.semantic_pnf_identity_projection AS projection
            ON projection.source_object_id = edge.object_id
         WHERE region.run_id = selected_run_id
           AND region.document_id = selected_document_id
    ),
    raw AS (
        SELECT left_edge.region_id,
               interface.interface_id AS source_interface_id,
               left_edge.factor_id AS left_factor_id,
               right_edge.factor_id AS right_factor_id,
               left_edge.role_symbol_id AS left_role_symbol_id,
               right_edge.role_symbol_id AS right_role_symbol_id,
               left_edge.target_entity_id AS bridge_entity_id,
               left_edge.authority_class,
               row_number() OVER (
                   PARTITION BY left_edge.region_id,
                                left_edge.target_entity_id,
                                left_edge.authority_class
                   ORDER BY left_edge.factor_id, right_edge.factor_id,
                            left_edge.slot_ordinal, right_edge.slot_ordinal
               ) - 1 AS candidate_rank
          FROM projected_edge AS left_edge
          JOIN projected_edge AS right_edge
            ON right_edge.region_id = left_edge.region_id
           AND right_edge.target_entity_id = left_edge.target_entity_id
           AND right_edge.authority_class = left_edge.authority_class
           AND right_edge.factor_id > left_edge.factor_id
           AND right_edge.object_id <> left_edge.object_id
          JOIN execution.semantic_pnf_interface AS interface
            ON interface.region_id = left_edge.region_id
    )
    INSERT INTO execution.semantic_pnf_factor_composition_candidate
        (source_interface_id, region_id,
         left_factor_id, right_factor_id,
         left_role_symbol_id, right_role_symbol_id,
         bridge_object_id, bridge_entity_id,
         identity_authority_class, candidate_rank)
    SELECT source_interface_id,
           region_id,
           left_factor_id,
           right_factor_id,
           left_role_symbol_id,
           right_role_symbol_id,
           NULL,
           bridge_entity_id,
           authority_class,
           candidate_rank::SMALLINT
      FROM raw
     WHERE candidate_rank < max_per_bridge
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS identity_inserted_count = ROW_COUNT;
    inserted_count := inserted_count + identity_inserted_count;

    RETURN inserted_count;
END;
$$;

-- Explicit derivation-stage orchestrator.  It never promotes composition
-- candidates to propositions by itself.
CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_semantic_derivations(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS TABLE (
    identity_witness_count BIGINT,
    identity_derivation_count BIGINT,
    composition_candidate_count BIGINT
)
LANGUAGE plpgsql
AS $$
BEGIN
    identity_witness_count := execution.refresh_numeric_pnf_identity_witnesses(
        selected_run_id,
        selected_document_id
    );
    identity_derivation_count :=
        execution.refresh_numeric_pnf_identity_substitution_derivations(
            selected_run_id,
            selected_document_id
        );
    composition_candidate_count :=
        execution.refresh_numeric_pnf_factor_composition_candidates(
            selected_run_id,
            selected_document_id,
            16
        );
    RETURN NEXT;
END;
$$;

COMMIT;
