BEGIN;

-- Parser-grounded identity evidence -------------------------------------------------
-- Candidate evidence is distinct from admitted identity.  No paragraph co-presence,
-- lexical proximity, or generic string equality is an admissible evidence producer.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_identity_evidence_candidate (
    candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    source_object_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE CASCADE,
    target_object_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE CASCADE,
    witness_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_identity_witness_kind(witness_kind)
        ON DELETE RESTRICT,
    source_token_id BIGINT
        REFERENCES execution.semantic_parser_token(token_id) ON DELETE SET NULL,
    target_token_id BIGINT
        REFERENCES execution.semantic_parser_token(token_id) ON DELETE SET NULL,
    sentence_id BIGINT
        REFERENCES execution.semantic_parser_sentence(sentence_id) ON DELETE SET NULL,
    evidence_ref TEXT NOT NULL,
    candidate_count SMALLINT NOT NULL CHECK (candidate_count BETWEEN 1 AND 256),
    evidence_state SMALLINT NOT NULL DEFAULT 1 CHECK (evidence_state IN (1, 2, 3, 4)),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (run_id, document_id, source_object_id, target_object_id,
            witness_kind, evidence_ref)
);
CREATE INDEX IF NOT EXISTS semantic_pnf_identity_evidence_candidate_doc_idx
    ON execution.semantic_pnf_identity_evidence_candidate
       (run_id, document_id, evidence_state, witness_kind, candidate_count,
        source_object_id, target_object_id);

-- A parser token may anchor a local PNF object only when the smallest containing
-- PNF region yields exactly one object whose head matches the token orth/lemma.
-- This is an observation-to-object bridge, not an identity inference.
CREATE OR REPLACE VIEW execution.semantic_pnf_parser_object_anchor AS
WITH candidate AS (
    SELECT token.token_id,
           token.sentence_id,
           token.run_ref,
           token.document_ref,
           object.object_id,
           region.region_id,
           (region.end_char - region.start_char) AS region_span,
           min(region.end_char - region.start_char)
               OVER (PARTITION BY token.token_id) AS minimum_region_span
      FROM execution.semantic_parser_token AS token
      JOIN execution.semantic_pnf_run_identity AS run_identity
        ON run_identity.run_ref = token.run_ref
      JOIN execution.semantic_pnf_document_identity AS document_identity
        ON document_identity.document_ref = token.document_ref
      JOIN execution.semantic_pnf_region AS region
        ON region.run_id = run_identity.run_id
       AND region.document_id = document_identity.document_id
       AND token.start_char >= region.start_char
       AND token.end_char <= region.end_char
      JOIN execution.semantic_pnf_object AS object
        ON object.region_id = region.region_id
       AND object.head_symbol_id IN (token.lemma_symbol_id, token.orth_symbol_id)
     WHERE token.representation_version = 2
), smallest AS (
    SELECT *
      FROM candidate
     WHERE region_span = minimum_region_span
), unique_anchor AS (
    SELECT token_id,
           min(sentence_id) AS sentence_id,
           min(object_id) AS object_id,
           count(DISTINCT object_id) AS object_count
      FROM smallest
     GROUP BY token_id
)
SELECT token_id, sentence_id, object_id
  FROM unique_anchor
 WHERE object_count = 1;

CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_parser_identity_evidence(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    selected_run_ref TEXT;
    selected_document_ref TEXT;
    affected_count BIGINT := 0;
BEGIN
    SELECT run_ref INTO selected_run_ref
      FROM execution.semantic_pnf_run_identity
     WHERE run_id = selected_run_id;
    SELECT document_ref INTO selected_document_ref
      FROM execution.semantic_pnf_document_identity
     WHERE document_id = selected_document_id;

    IF selected_run_ref IS NULL OR selected_document_ref IS NULL THEN
        RAISE EXCEPTION 'unknown numeric run/document %, %',
            selected_run_id, selected_document_id;
    END IF;

    UPDATE execution.semantic_pnf_identity_evidence_candidate
       SET evidence_state = 4
     WHERE run_id = selected_run_id
       AND document_id = selected_document_id
       AND evidence_state IN (1, 2);

    -- Direct dependency apposition.  This is the strongest local parser producer:
    -- the dependency itself is the evidence, never sentence or paragraph proximity.
    INSERT INTO execution.semantic_pnf_identity_evidence_candidate
        (run_id, document_id, source_object_id, target_object_id,
         witness_kind, source_token_id, target_token_id, sentence_id,
         evidence_ref, candidate_count, evidence_state)
    SELECT selected_run_id,
           selected_document_id,
           source_anchor.object_id,
           target_anchor.object_id,
           CASE
               WHEN source_pos.symbol_text IN ('NOUN', 'PROPN')
                    AND EXISTS (
                        SELECT 1
                          FROM execution.semantic_parser_entity_span AS entity
                         WHERE entity.run_ref = selected_run_ref
                           AND entity.document_ref = selected_document_ref
                           AND entity.sentence_id = source_token.sentence_id
                           AND target_token.start_char >= entity.start_char
                           AND target_token.end_char <= entity.end_char
                           AND EXISTS (
                               SELECT 1
                                 FROM execution.semantic_symbol AS entity_type
                                WHERE entity_type.symbol_id = entity.entity_type_symbol_id
                                  AND entity_type.symbol_text = 'PERSON'
                           )
                    )
               THEN 4
               ELSE 2
           END,
           source_token.token_id,
           target_token.token_id,
           source_token.sentence_id,
           'parser-appos:' || source_token.token_id::TEXT || ':' || target_token.token_id::TEXT,
           1,
           1
      FROM execution.semantic_parser_token AS source_token
      JOIN execution.semantic_symbol AS dependency
        ON dependency.symbol_id = source_token.dependency_symbol_id
       AND dependency.symbol_text = 'appos'
      JOIN execution.semantic_parser_token AS target_token
        ON target_token.token_id = source_token.head_token_id
       AND target_token.sentence_id = source_token.sentence_id
      JOIN execution.semantic_pnf_parser_object_anchor AS source_anchor
        ON source_anchor.token_id = source_token.token_id
      JOIN execution.semantic_pnf_parser_object_anchor AS target_anchor
        ON target_anchor.token_id = target_token.token_id
      JOIN execution.semantic_symbol AS source_pos
        ON source_pos.symbol_id = source_token.pos_symbol_id
     WHERE source_token.run_ref = selected_run_ref
       AND source_token.document_ref = selected_document_ref
       AND source_anchor.object_id <> target_anchor.object_id
    ON CONFLICT (run_id, document_id, source_object_id, target_object_id,
                 witness_kind, evidence_ref)
    DO UPDATE SET evidence_state = 1, candidate_count = EXCLUDED.candidate_count;

    -- Proper-name expansion.  A surname-like token may project to a multi-token
    -- PERSON mention only if exactly one PERSON entity in the document has that
    -- final proper-name lemma.  Two Ronald/Nancy-style family-name anchors remain
    -- candidate_count > 1 and therefore cannot be admitted.
    WITH person_entity_head AS (
        SELECT entity.entity_id AS parser_entity_id,
               entity.sentence_id,
               entity.start_char,
               entity.end_char,
               head.token_id AS head_token_id,
               head.lemma_symbol_id AS family_lemma_symbol_id,
               anchor.object_id AS anchor_object_id
          FROM execution.semantic_parser_entity_span AS entity
          JOIN execution.semantic_symbol AS entity_type
            ON entity_type.symbol_id = entity.entity_type_symbol_id
           AND entity_type.symbol_text = 'PERSON'
          JOIN LATERAL (
              SELECT token.token_id, token.lemma_symbol_id, token.end_char
                FROM execution.semantic_parser_token AS token
                JOIN execution.semantic_symbol AS pos
                  ON pos.symbol_id = token.pos_symbol_id
                 AND pos.symbol_text = 'PROPN'
               WHERE token.sentence_id = entity.sentence_id
                 AND token.start_char >= entity.start_char
                 AND token.end_char <= entity.end_char
               ORDER BY token.end_char DESC, token.token_id DESC
               LIMIT 1
          ) AS head ON TRUE
          JOIN execution.semantic_pnf_parser_object_anchor AS anchor
            ON anchor.token_id = head.token_id
         WHERE entity.run_ref = selected_run_ref
           AND entity.document_ref = selected_document_ref
           AND EXISTS (
               SELECT 1
                 FROM execution.semantic_parser_token AS t1
                 JOIN execution.semantic_parser_token AS t2
                   ON t2.sentence_id = t1.sentence_id
                  AND t2.token_id <> t1.token_id
                WHERE t1.sentence_id = entity.sentence_id
                  AND t1.start_char >= entity.start_char
                  AND t1.end_char <= entity.end_char
                  AND t2.start_char >= entity.start_char
                  AND t2.end_char <= entity.end_char
           )
    ), family_cardinality AS (
        SELECT family_lemma_symbol_id,
               count(DISTINCT parser_entity_id)::SMALLINT AS candidate_count
          FROM person_entity_head
         GROUP BY family_lemma_symbol_id
    )
    INSERT INTO execution.semantic_pnf_identity_evidence_candidate
        (run_id, document_id, source_object_id, target_object_id,
         witness_kind, source_token_id, target_token_id, sentence_id,
         evidence_ref, candidate_count, evidence_state)
    SELECT selected_run_id,
           selected_document_id,
           mention_anchor.object_id,
           person.anchor_object_id,
           3,
           mention.token_id,
           person.head_token_id,
           mention.sentence_id,
           'proper-name-expansion:' || mention.token_id::TEXT || ':'
               || person.parser_entity_id::TEXT,
           cardinality.candidate_count,
           1
      FROM execution.semantic_parser_token AS mention
      JOIN execution.semantic_symbol AS mention_pos
        ON mention_pos.symbol_id = mention.pos_symbol_id
       AND mention_pos.symbol_text = 'PROPN'
      JOIN execution.semantic_pnf_parser_object_anchor AS mention_anchor
        ON mention_anchor.token_id = mention.token_id
      JOIN person_entity_head AS person
        ON person.family_lemma_symbol_id = mention.lemma_symbol_id
      JOIN family_cardinality AS cardinality
        ON cardinality.family_lemma_symbol_id = mention.lemma_symbol_id
     WHERE mention.run_ref = selected_run_ref
       AND mention.document_ref = selected_document_ref
       AND NOT (
           mention.sentence_id = person.sentence_id
           AND mention.start_char >= person.start_char
           AND mention.end_char <= person.end_char
       )
       AND mention_anchor.object_id <> person.anchor_object_id
    ON CONFLICT (run_id, document_id, source_object_id, target_object_id,
                 witness_kind, evidence_ref)
    DO UPDATE SET evidence_state = 1, candidate_count = EXCLUDED.candidate_count;

    -- Explicit aliases: a lexical alias cue between two PERSON spans in the same
    -- sentence licenses a candidate.  The cue, not nearness by itself, is the evidence.
    INSERT INTO execution.semantic_pnf_identity_evidence_candidate
        (run_id, document_id, source_object_id, target_object_id,
         witness_kind, source_token_id, target_token_id, sentence_id,
         evidence_ref, candidate_count, evidence_state)
    SELECT selected_run_id,
           selected_document_id,
           right_anchor.object_id,
           left_anchor.object_id,
           6,
           right_head.token_id,
           left_head.token_id,
           left_entity.sentence_id,
           'explicit-alias:' || marker.token_id::TEXT || ':'
               || left_entity.entity_id::TEXT || ':' || right_entity.entity_id::TEXT,
           1,
           1
      FROM execution.semantic_parser_entity_span AS left_entity
      JOIN execution.semantic_parser_entity_span AS right_entity
        ON right_entity.sentence_id = left_entity.sentence_id
       AND right_entity.start_char > left_entity.end_char
      JOIN execution.semantic_symbol AS left_type
        ON left_type.symbol_id = left_entity.entity_type_symbol_id
       AND left_type.symbol_text = 'PERSON'
      JOIN execution.semantic_symbol AS right_type
        ON right_type.symbol_id = right_entity.entity_type_symbol_id
       AND right_type.symbol_text = 'PERSON'
      JOIN execution.semantic_parser_token AS marker
        ON marker.sentence_id = left_entity.sentence_id
       AND marker.start_char >= left_entity.end_char
       AND marker.end_char <= right_entity.start_char
      JOIN execution.semantic_symbol AS marker_orth
        ON marker_orth.symbol_id = marker.orth_symbol_id
       AND lower(marker_orth.symbol_text) IN ('aka', 'a.k.a.', 'alias')
      JOIN LATERAL (
          SELECT token.token_id
            FROM execution.semantic_parser_token AS token
           WHERE token.sentence_id = left_entity.sentence_id
             AND token.start_char >= left_entity.start_char
             AND token.end_char <= left_entity.end_char
           ORDER BY token.end_char DESC
           LIMIT 1
      ) AS left_head ON TRUE
      JOIN LATERAL (
          SELECT token.token_id
            FROM execution.semantic_parser_token AS token
           WHERE token.sentence_id = right_entity.sentence_id
             AND token.start_char >= right_entity.start_char
             AND token.end_char <= right_entity.end_char
           ORDER BY token.end_char DESC
           LIMIT 1
      ) AS right_head ON TRUE
      JOIN execution.semantic_pnf_parser_object_anchor AS left_anchor
        ON left_anchor.token_id = left_head.token_id
      JOIN execution.semantic_pnf_parser_object_anchor AS right_anchor
        ON right_anchor.token_id = right_head.token_id
     WHERE left_entity.run_ref = selected_run_ref
       AND left_entity.document_ref = selected_document_ref
       AND right_entity.run_ref = selected_run_ref
       AND right_entity.document_ref = selected_document_ref
       AND left_anchor.object_id <> right_anchor.object_id
    ON CONFLICT (run_id, document_id, source_object_id, target_object_id,
                 witness_kind, evidence_ref)
    DO UPDATE SET evidence_state = 1, candidate_count = EXCLUDED.candidate_count;

    SELECT count(*) INTO affected_count
      FROM execution.semantic_pnf_identity_evidence_candidate
     WHERE run_id = selected_run_id
       AND document_id = selected_document_id
       AND evidence_state = 1;
    RETURN affected_count;
END;
$$;

CREATE OR REPLACE FUNCTION execution.admit_numeric_pnf_parser_identity_evidence(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    admitted_count BIGINT := 0;
BEGIN
    -- Withdraw prior parser-produced document identity before recomputing current evidence.
    UPDATE execution.semantic_pnf_identity_witness_admission AS admission
       SET admission_state = 4,
           revision = admission.revision + 1,
           updated_at = CURRENT_TIMESTAMP
      FROM execution.semantic_pnf_identity_witness AS witness
      JOIN execution.semantic_pnf_object AS source
        ON source.object_id = witness.source_object_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = source.region_id
     WHERE admission.witness_id = witness.witness_id
       AND admission.admission_state = 2
       AND witness.authority_class = 2
       AND witness.witness_kind IN (1, 2, 3, 4, 6)
       AND witness.demand_id IS NULL
       AND region.run_id = selected_run_id
       AND region.document_id = selected_document_id;

    INSERT INTO execution.semantic_pnf_canonical_entity
        (entity_ref, authority_class, canonical_symbol_id, anchor_object_id)
    SELECT 'document-object:' || encode(target.object_digest, 'hex'),
           2,
           target.head_symbol_id,
           target.object_id
      FROM execution.semantic_pnf_identity_evidence_candidate AS candidate
      JOIN execution.semantic_pnf_object AS target
        ON target.object_id = candidate.target_object_id
     WHERE candidate.run_id = selected_run_id
       AND candidate.document_id = selected_document_id
       AND candidate.evidence_state = 1
       AND candidate.candidate_count = 1
    ON CONFLICT DO NOTHING;

    -- The target object is admitted as the document-local base because the same
    -- parser evidence establishes the source->target relation.  This remains
    -- document authority only; no world identity is created.
    INSERT INTO execution.semantic_pnf_identity_witness
        (source_object_id, target_entity_id, witness_kind, authority_class,
         candidate_count)
    SELECT DISTINCT candidate.target_object_id,
           entity.entity_id,
           1,
           2,
           1
      FROM execution.semantic_pnf_identity_evidence_candidate AS candidate
      JOIN execution.semantic_pnf_canonical_entity AS entity
        ON entity.anchor_object_id = candidate.target_object_id
     WHERE candidate.run_id = selected_run_id
       AND candidate.document_id = selected_document_id
       AND candidate.evidence_state = 1
       AND candidate.candidate_count = 1
    ON CONFLICT DO NOTHING;

    INSERT INTO execution.semantic_pnf_identity_witness
        (source_object_id, target_entity_id, witness_kind, authority_class,
         source_interface_id, candidate_count)
    SELECT candidate.source_object_id,
           entity.entity_id,
           candidate.witness_kind,
           2,
           interface.interface_id,
           candidate.candidate_count
      FROM execution.semantic_pnf_identity_evidence_candidate AS candidate
      JOIN execution.semantic_pnf_canonical_entity AS entity
        ON entity.anchor_object_id = candidate.target_object_id
      JOIN execution.semantic_pnf_object AS source
        ON source.object_id = candidate.source_object_id
      LEFT JOIN execution.semantic_pnf_interface AS interface
        ON interface.region_id = source.region_id
     WHERE candidate.run_id = selected_run_id
       AND candidate.document_id = selected_document_id
       AND candidate.evidence_state = 1
       AND candidate.candidate_count = 1
       AND candidate.witness_kind IN (2, 3, 4, 6)
    ON CONFLICT DO NOTHING;

    INSERT INTO execution.semantic_pnf_identity_witness_admission
        (witness_id, admission_state, revision)
    SELECT witness.witness_id, 2, 1
      FROM execution.semantic_pnf_identity_witness AS witness
      JOIN execution.semantic_pnf_canonical_entity AS entity
        ON entity.entity_id = witness.target_entity_id
      JOIN execution.semantic_pnf_object AS source
        ON source.object_id = witness.source_object_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = source.region_id
     WHERE region.run_id = selected_run_id
       AND region.document_id = selected_document_id
       AND witness.authority_class = 2
       AND entity.authority_class = 2
       AND witness.candidate_count = 1
       AND witness.witness_kind IN (1, 2, 3, 4, 6)
       AND witness.demand_id IS NULL
       AND (
           witness.witness_kind = 1
           OR EXISTS (
               SELECT 1
                 FROM execution.semantic_pnf_identity_evidence_candidate AS candidate
                WHERE candidate.run_id = selected_run_id
                  AND candidate.document_id = selected_document_id
                  AND candidate.evidence_state = 1
                  AND candidate.candidate_count = 1
                  AND candidate.source_object_id = witness.source_object_id
                  AND candidate.target_object_id = entity.anchor_object_id
                  AND candidate.witness_kind = witness.witness_kind
           )
       )
    ON CONFLICT (witness_id) DO UPDATE SET
        admission_state = 2,
        revision = execution.semantic_pnf_identity_witness_admission.revision + 1,
        updated_at = CURRENT_TIMESTAMP;

    UPDATE execution.semantic_pnf_identity_evidence_candidate AS candidate
       SET evidence_state = CASE WHEN candidate_count = 1 THEN 2 ELSE 3 END
     WHERE candidate.run_id = selected_run_id
       AND candidate.document_id = selected_document_id
       AND candidate.evidence_state = 1;

    SELECT count(*) INTO admitted_count
      FROM execution.semantic_pnf_identity_witness AS witness
      JOIN execution.semantic_pnf_identity_witness_admission AS admission
        ON admission.witness_id = witness.witness_id
       AND admission.admission_state = 2
      JOIN execution.semantic_pnf_object AS source
        ON source.object_id = witness.source_object_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = source.region_id
     WHERE region.run_id = selected_run_id
       AND region.document_id = selected_document_id
       AND witness.authority_class = 2
       AND witness.witness_kind IN (2, 3, 4, 6);
    RETURN admitted_count;
END;
$$;

-- Integrate parser evidence with the already proof-relevant demand path.  Demand
-- resolution remains the only producer for anaphor witness kind 5.
CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_semantic_derivations(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS TABLE (
    identity_witness_count BIGINT,
    identity_derivation_count BIGINT,
    composition_candidate_count BIGINT
)
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM execution.refresh_numeric_pnf_identity_witnesses(
        selected_run_id, selected_document_id
    );
    PERFORM execution.refresh_numeric_pnf_parser_identity_evidence(
        selected_run_id, selected_document_id
    );
    PERFORM execution.admit_numeric_pnf_parser_identity_evidence(
        selected_run_id, selected_document_id
    );

    identity_derivation_count :=
        execution.refresh_numeric_pnf_identity_substitution_derivations(
            selected_run_id, selected_document_id
        );
    composition_candidate_count :=
        execution.refresh_numeric_pnf_factor_composition_candidates(
            selected_run_id, selected_document_id, 16
        );

    SELECT count(*) INTO identity_witness_count
      FROM execution.semantic_pnf_identity_witness AS witness
      JOIN execution.semantic_pnf_identity_witness_admission AS admission
        ON admission.witness_id = witness.witness_id
       AND admission.admission_state = 2
      JOIN execution.semantic_pnf_object AS source
        ON source.object_id = witness.source_object_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = source.region_id
     WHERE region.run_id = selected_run_id
       AND region.document_id = selected_document_id;
    RETURN NEXT;
END;
$$;

COMMIT;
