BEGIN;

-- Consumer-indexed, reopenable runtime carrier --------------------------------
--
-- Agda reference contract:
--   F = represented candidate fibre (the existing demand_candidate relation)
--   P = active bounded execution surface
--   Q = represented but inactive/reopenable candidates
--   R = other represented unresolved residual structure
--   O = explicit outside-model/open-world ignorance
--
-- The current demand_candidate table remains the hot execution surface.  It is
-- intentionally NOT promoted to semantic truth: planner replacement is logged
-- as an execution event and candidate history survives replanning.

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_demand_candidate_observation (
    observation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE CASCADE,
    target_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_target_kind(kind_id) ON DELETE RESTRICT,
    target_id BIGINT NOT NULL,
    observation_kind SMALLINT NOT NULL CHECK (observation_kind IN (1, 2)),
    planning_ordinal SMALLINT,
    source_interface_id BIGINT
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE SET NULL,
    ancestor_distance BIGINT,
    index_rank BIGINT,
    candidate_score DOUBLE PRECISION,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS semantic_pnf_candidate_observation_candidate_idx
    ON execution.semantic_pnf_demand_candidate_observation
       (demand_id, target_kind, target_id, observation_id);
CREATE INDEX IF NOT EXISTS semantic_pnf_candidate_observation_time_idx
    ON execution.semantic_pnf_demand_candidate_observation
       (demand_id, observed_at, observation_id);

-- Fine evidence is append-only in ordinary operation.  The signed residual is
-- the authoritative numeric evidence coordinate; -1/0/+1 is derived by views.
-- Horizon 3/6/9 is cumulative over one candidate fibre, not three candidate
-- searches.  Family 1=local structural, 2=discourse/temporal, 3=external.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_candidate_evidence (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE CASCADE,
    target_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_target_kind(kind_id) ON DELETE RESTRICT,
    target_id BIGINT NOT NULL,
    evidence_ref TEXT NOT NULL,
    evidence_family SMALLINT NOT NULL CHECK (evidence_family IN (1, 2, 3)),
    horizon SMALLINT NOT NULL CHECK (horizon IN (3, 6, 9)),
    signed_residual BIGINT NOT NULL,
    evidence_kind TEXT NOT NULL,
    provenance_ref TEXT,
    source_interface_id BIGINT
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE SET NULL,
    source_region_id BIGINT
        REFERENCES execution.semantic_pnf_region(region_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (demand_id, target_kind, target_id, evidence_ref),
    CHECK (
        (evidence_family = 1 AND horizon = 3)
        OR (evidence_family = 2 AND horizon = 6)
        OR (evidence_family = 3 AND horizon = 9)
    )
);
CREATE INDEX IF NOT EXISTS semantic_pnf_candidate_evidence_horizon_idx
    ON execution.semantic_pnf_candidate_evidence
       (demand_id, target_kind, target_id, horizon, evidence_id);
CREATE INDEX IF NOT EXISTS semantic_pnf_candidate_evidence_provenance_idx
    ON execution.semantic_pnf_candidate_evidence
       (provenance_ref, evidence_id)
    WHERE provenance_ref IS NOT NULL;

-- Execution events are explicitly non-semantic.  1=activate, 2=prune,
-- 3=reopen, 4=resource-limited, 5=planner-superseded.  None refutes a candidate.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_candidate_execution_event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE CASCADE,
    target_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_target_kind(kind_id) ON DELETE RESTRICT,
    target_id BIGINT NOT NULL,
    event_kind SMALLINT NOT NULL CHECK (event_kind BETWEEN 1 AND 5),
    active_budget INTEGER CHECK (active_budget IS NULL OR active_budget > 0),
    reason_ref TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS semantic_pnf_candidate_execution_latest_idx
    ON execution.semantic_pnf_candidate_execution_event
       (demand_id, target_kind, target_id, event_id DESC);

-- Semantic refutation/restoration is a DIFFERENT event family and every event
-- requires a concrete evidence row.  1=refute, 2=restore admissibility.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_candidate_admissibility_event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE CASCADE,
    target_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_target_kind(kind_id) ON DELETE RESTRICT,
    target_id BIGINT NOT NULL,
    event_kind SMALLINT NOT NULL CHECK (event_kind IN (1, 2)),
    evidence_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_candidate_evidence(evidence_id)
        ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS semantic_pnf_candidate_admissibility_latest_idx
    ON execution.semantic_pnf_candidate_admissibility_event
       (demand_id, target_kind, target_id, event_id DESC);

-- Inductive preference is revisioned and remains non-proof.  It is intentionally
-- disjoint from identity_witness / identity_witness_admission.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_candidate_preference (
    preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE CASCADE,
    target_kind SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_target_kind(kind_id) ON DELETE RESTRICT,
    target_id BIGINT NOT NULL,
    horizon SMALLINT NOT NULL CHECK (horizon IN (3, 6, 9)),
    revision BIGINT NOT NULL CHECK (revision > 0),
    preferred BOOLEAN NOT NULL,
    margin BIGINT NOT NULL DEFAULT 0,
    evidence_count BIGINT NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (demand_id, target_kind, target_id, horizon, revision)
);
CREATE INDEX IF NOT EXISTS semantic_pnf_candidate_preference_latest_idx
    ON execution.semantic_pnf_candidate_preference
       (demand_id, target_kind, target_id, horizon, revision DESC);

-- Open-world closure cannot be asserted merely because current candidates sum
-- to a normalized unit.  A demand is open-world by default.  Closing that door
-- requires an explicit coverage witness reference.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_demand_open_world_state (
    demand_id BIGINT PRIMARY KEY
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE CASCADE,
    outside_model_possible BOOLEAN NOT NULL DEFAULT TRUE,
    coverage_witness_ref TEXT,
    represented_residual_count BIGINT NOT NULL DEFAULT 0
        CHECK (represented_residual_count >= 0),
    resource_limited BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (outside_model_possible OR coverage_witness_ref IS NOT NULL)
);

INSERT INTO execution.semantic_pnf_demand_open_world_state (demand_id)
SELECT demand_id
  FROM execution.semantic_pnf_demand
ON CONFLICT (demand_id) DO NOTHING;

CREATE OR REPLACE FUNCTION execution.seed_numeric_pnf_open_world_state()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO execution.semantic_pnf_demand_open_world_state (demand_id)
    VALUES (NEW.demand_id)
    ON CONFLICT (demand_id) DO NOTHING;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS semantic_pnf_demand_open_world_seed
    ON execution.semantic_pnf_demand;
CREATE TRIGGER semantic_pnf_demand_open_world_seed
AFTER INSERT ON execution.semantic_pnf_demand
FOR EACH ROW EXECUTE FUNCTION execution.seed_numeric_pnf_open_world_state();

-- Consumer/model-relative mass accounting.  These exact integer masses are not
-- probabilities and do not assert that the represented candidate universe is
-- complete.  mass_kind: 1=candidate weight, 2=represented provenance,
-- 3=consumer/task relevance.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_demand_relevance_accounting (
    accounting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE CASCADE,
    consumer_ref TEXT NOT NULL,
    mass_kind SMALLINT NOT NULL CHECK (mass_kind IN (1, 2, 3)),
    horizon SMALLINT NOT NULL CHECK (horizon IN (3, 6, 9)),
    active_mass BIGINT NOT NULL CHECK (active_mass >= 0),
    residual_candidate_mass BIGINT NOT NULL CHECK (residual_candidate_mass >= 0),
    represented_residual_mass BIGINT NOT NULL CHECK (represented_residual_mass >= 0),
    outside_model_mass BIGINT NOT NULL CHECK (outside_model_mass >= 0),
    total_mass BIGINT NOT NULL CHECK (total_mass > 0),
    measurement_ref TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        active_mass + residual_candidate_mass
        + represented_residual_mass + outside_model_mass = total_mass
    )
);
CREATE INDEX IF NOT EXISTS semantic_pnf_relevance_accounting_demand_idx
    ON execution.semantic_pnf_demand_relevance_accounting
       (demand_id, consumer_ref, horizon, accounting_id DESC);

-- Planner hot-surface lifecycle ------------------------------------------------
-- Existing planners DELETE + INSERT demand_candidate rows.  Preserve those
-- transitions rather than interpreting DELETE as semantic disappearance.

CREATE OR REPLACE FUNCTION execution.observe_numeric_pnf_candidate_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO execution.semantic_pnf_demand_candidate_observation
        (demand_id, target_kind, target_id, observation_kind,
         planning_ordinal, source_interface_id, ancestor_distance,
         index_rank, candidate_score)
    VALUES
        (NEW.demand_id, NEW.target_kind, NEW.target_id, 1,
         NEW.ordinal, NEW.source_interface_id, NEW.ancestor_distance,
         NEW.index_rank, NEW.candidate_score);

    INSERT INTO execution.semantic_pnf_candidate_execution_event
        (demand_id, target_kind, target_id, event_kind, reason_ref)
    VALUES (NEW.demand_id, NEW.target_kind, NEW.target_id, 1, 'planner-active');

    -- Candidate generation is neutral structural evidence: membership in F is
    -- recorded without converting the legacy floating candidate_score to a
    -- semantic signed residual.
    INSERT INTO execution.semantic_pnf_candidate_evidence
        (demand_id, target_kind, target_id, evidence_ref,
         evidence_family, horizon, signed_residual, evidence_kind,
         provenance_ref, source_interface_id)
    VALUES
        (NEW.demand_id, NEW.target_kind, NEW.target_id,
         'planner-membership:' || NEW.target_kind::TEXT || ':' || NEW.target_id::TEXT,
         1, 3, 0, 'candidate_generation',
         'semantic_pnf_demand_candidate', NEW.source_interface_id)
    ON CONFLICT (demand_id, target_kind, target_id, evidence_ref) DO NOTHING;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION execution.observe_numeric_pnf_candidate_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO execution.semantic_pnf_demand_candidate_observation
        (demand_id, target_kind, target_id, observation_kind,
         planning_ordinal, source_interface_id, ancestor_distance,
         index_rank, candidate_score)
    VALUES
        (OLD.demand_id, OLD.target_kind, OLD.target_id, 2,
         OLD.ordinal, OLD.source_interface_id, OLD.ancestor_distance,
         OLD.index_rank, OLD.candidate_score);

    INSERT INTO execution.semantic_pnf_candidate_execution_event
        (demand_id, target_kind, target_id, event_kind, reason_ref)
    VALUES
        (OLD.demand_id, OLD.target_kind, OLD.target_id, 5,
         'planner-replan-superseded');
    RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS semantic_pnf_candidate_observe_insert
    ON execution.semantic_pnf_demand_candidate;
CREATE TRIGGER semantic_pnf_candidate_observe_insert
AFTER INSERT ON execution.semantic_pnf_demand_candidate
FOR EACH ROW EXECUTE FUNCTION execution.observe_numeric_pnf_candidate_insert();

DROP TRIGGER IF EXISTS semantic_pnf_candidate_observe_delete
    ON execution.semantic_pnf_demand_candidate;
CREATE TRIGGER semantic_pnf_candidate_observe_delete
BEFORE DELETE ON execution.semantic_pnf_demand_candidate
FOR EACH ROW EXECUTE FUNCTION execution.observe_numeric_pnf_candidate_delete();

-- Backfill the currently active fibre after trigger installation.
INSERT INTO execution.semantic_pnf_demand_candidate_observation
    (demand_id, target_kind, target_id, observation_kind,
     planning_ordinal, source_interface_id, ancestor_distance,
     index_rank, candidate_score)
SELECT candidate.demand_id,
       candidate.target_kind,
       candidate.target_id,
       1,
       candidate.ordinal,
       candidate.source_interface_id,
       candidate.ancestor_distance,
       candidate.index_rank,
       candidate.candidate_score
  FROM execution.semantic_pnf_demand_candidate AS candidate
 WHERE NOT EXISTS (
       SELECT 1
         FROM execution.semantic_pnf_demand_candidate_observation AS observation
        WHERE observation.demand_id = candidate.demand_id
          AND observation.target_kind = candidate.target_kind
          AND observation.target_id = candidate.target_id
   );

INSERT INTO execution.semantic_pnf_candidate_execution_event
    (demand_id, target_kind, target_id, event_kind, reason_ref)
SELECT candidate.demand_id, candidate.target_kind, candidate.target_id,
       1, 'migration-086-active-backfill'
  FROM execution.semantic_pnf_demand_candidate AS candidate
 WHERE NOT EXISTS (
       SELECT 1
         FROM execution.semantic_pnf_candidate_execution_event AS event
        WHERE event.demand_id = candidate.demand_id
          AND event.target_kind = candidate.target_kind
          AND event.target_id = candidate.target_id
   );

INSERT INTO execution.semantic_pnf_candidate_evidence
    (demand_id, target_kind, target_id, evidence_ref,
     evidence_family, horizon, signed_residual, evidence_kind,
     provenance_ref, source_interface_id)
SELECT candidate.demand_id,
       candidate.target_kind,
       candidate.target_id,
       'planner-membership:' || candidate.target_kind::TEXT || ':'
           || candidate.target_id::TEXT,
       1, 3, 0, 'candidate_generation',
       'semantic_pnf_demand_candidate', candidate.source_interface_id
  FROM execution.semantic_pnf_demand_candidate AS candidate
ON CONFLICT (demand_id, target_kind, target_id, evidence_ref) DO NOTHING;

-- Candidate-state and horizon views -------------------------------------------

CREATE OR REPLACE VIEW execution.semantic_pnf_candidate_latest_execution AS
SELECT DISTINCT ON (demand_id, target_kind, target_id)
       demand_id, target_kind, target_id, event_id, event_kind,
       active_budget, reason_ref, created_at
  FROM execution.semantic_pnf_candidate_execution_event
 ORDER BY demand_id, target_kind, target_id, event_id DESC;

CREATE OR REPLACE VIEW execution.semantic_pnf_candidate_latest_admissibility AS
SELECT DISTINCT ON (demand_id, target_kind, target_id)
       demand_id, target_kind, target_id, event_id, event_kind,
       evidence_id, created_at
  FROM execution.semantic_pnf_candidate_admissibility_event
 ORDER BY demand_id, target_kind, target_id, event_id DESC;

CREATE OR REPLACE VIEW execution.semantic_pnf_candidate_latest_preference AS
SELECT DISTINCT ON (demand_id, target_kind, target_id, horizon)
       demand_id, target_kind, target_id, horizon, revision,
       preferred, margin, evidence_count, preference_id
  FROM execution.semantic_pnf_candidate_preference
 ORDER BY demand_id, target_kind, target_id, horizon, revision DESC,
          preference_id DESC;

CREATE OR REPLACE VIEW execution.semantic_pnf_candidate_universe AS
SELECT observation.demand_id,
       observation.target_kind,
       observation.target_id,
       min(observation.observation_id) AS first_observation_id,
       max(observation.observation_id) AS latest_observation_id
  FROM execution.semantic_pnf_demand_candidate_observation AS observation
 GROUP BY observation.demand_id, observation.target_kind, observation.target_id;

CREATE OR REPLACE VIEW execution.semantic_pnf_candidate_state_v1 AS
SELECT universe.demand_id,
       universe.target_kind,
       universe.target_id,
       TRUE AS represented_possible,
       current_candidate.demand_id IS NOT NULL
           AND COALESCE(execution_state.event_kind, 1) IN (1, 3)
           AS active,
       COALESCE(execution_state.event_kind IN (2, 4, 5), FALSE)
           AS execution_residual,
       COALESCE(admissibility.event_kind = 1, FALSE) AS refuted,
       NOT COALESCE(admissibility.event_kind = 1, FALSE) AS admissible,
       execution_state.reason_ref AS execution_reason_ref,
       admissibility.evidence_id AS admissibility_evidence_id
  FROM execution.semantic_pnf_candidate_universe AS universe
  LEFT JOIN execution.semantic_pnf_demand_candidate AS current_candidate
    ON current_candidate.demand_id = universe.demand_id
   AND current_candidate.target_kind = universe.target_kind
   AND current_candidate.target_id = universe.target_id
  LEFT JOIN execution.semantic_pnf_candidate_latest_execution AS execution_state
    ON execution_state.demand_id = universe.demand_id
   AND execution_state.target_kind = universe.target_kind
   AND execution_state.target_id = universe.target_id
  LEFT JOIN execution.semantic_pnf_candidate_latest_admissibility AS admissibility
    ON admissibility.demand_id = universe.demand_id
   AND admissibility.target_kind = universe.target_kind
   AND admissibility.target_id = universe.target_id;

CREATE OR REPLACE VIEW execution.semantic_pnf_candidate_evidence_horizon_v1 AS
WITH horizon(horizon) AS (
    VALUES (3::SMALLINT), (6::SMALLINT), (9::SMALLINT)
)
SELECT universe.demand_id,
       universe.target_kind,
       universe.target_id,
       horizon.horizon,
       COALESCE(sum(evidence.signed_residual), 0)::BIGINT AS signed_residual,
       sign(COALESCE(sum(evidence.signed_residual), 0))::SMALLINT AS phase,
       count(evidence.evidence_id)::BIGINT AS evidence_count
  FROM execution.semantic_pnf_candidate_universe AS universe
 CROSS JOIN horizon
  LEFT JOIN execution.semantic_pnf_candidate_evidence AS evidence
    ON evidence.demand_id = universe.demand_id
   AND evidence.target_kind = universe.target_kind
   AND evidence.target_id = universe.target_id
   AND evidence.horizon <= horizon.horizon
 GROUP BY universe.demand_id, universe.target_kind, universe.target_id,
          horizon.horizon;

-- Explicit helpers.  Pruning/reopening never touches semantic admissibility.
CREATE OR REPLACE FUNCTION execution.prune_numeric_pnf_candidate_execution(
    selected_demand_id BIGINT,
    selected_target_kind SMALLINT,
    selected_target_id BIGINT,
    selected_budget INTEGER,
    selected_reason_ref TEXT DEFAULT 'bounded-execution'
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE inserted_event BIGINT;
BEGIN
    INSERT INTO execution.semantic_pnf_candidate_execution_event
        (demand_id, target_kind, target_id, event_kind,
         active_budget, reason_ref)
    VALUES
        (selected_demand_id, selected_target_kind, selected_target_id,
         2, selected_budget, selected_reason_ref)
    RETURNING event_id INTO inserted_event;
    RETURN inserted_event;
END;
$$;

CREATE OR REPLACE FUNCTION execution.reopen_numeric_pnf_candidate_execution(
    selected_demand_id BIGINT,
    selected_target_kind SMALLINT,
    selected_target_id BIGINT,
    selected_reason_ref TEXT DEFAULT 'new-evidence'
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE inserted_event BIGINT;
BEGIN
    INSERT INTO execution.semantic_pnf_candidate_execution_event
        (demand_id, target_kind, target_id, event_kind, reason_ref)
    VALUES
        (selected_demand_id, selected_target_kind, selected_target_id,
         3, selected_reason_ref)
    RETURNING event_id INTO inserted_event;
    RETURN inserted_event;
END;
$$;

CREATE OR REPLACE FUNCTION execution.record_numeric_pnf_candidate_admissibility(
    selected_demand_id BIGINT,
    selected_target_kind SMALLINT,
    selected_target_id BIGINT,
    selected_event_kind SMALLINT,
    selected_evidence_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE inserted_event BIGINT;
BEGIN
    IF selected_event_kind NOT IN (1, 2) THEN
        RAISE EXCEPTION 'admissibility event kind must be 1=refute or 2=restore';
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM execution.semantic_pnf_candidate_evidence AS evidence
         WHERE evidence.evidence_id = selected_evidence_id
           AND evidence.demand_id = selected_demand_id
           AND evidence.target_kind = selected_target_kind
           AND evidence.target_id = selected_target_id
    ) THEN
        RAISE EXCEPTION 'admissibility event requires evidence for the same candidate';
    END IF;
    INSERT INTO execution.semantic_pnf_candidate_admissibility_event
        (demand_id, target_kind, target_id, event_kind, evidence_id)
    VALUES
        (selected_demand_id, selected_target_kind, selected_target_id,
         selected_event_kind, selected_evidence_id)
    RETURNING event_id INTO inserted_event;
    RETURN inserted_event;
END;
$$;

-- Exact representation support -> factor applicability ------------------------
-- Reuse semantic_pnf_object_token_support.  Sharing the SAME parser token
-- occurrence is a structural representation bridge, not an identity assertion.

CREATE OR REPLACE VIEW execution.semantic_pnf_factor_identity_support_v1 AS
SELECT edge.factor_id,
       edge.slot_ordinal,
       edge.role_symbol_id,
       edge.object_id AS factor_object_id,
       projection.source_object_id AS identity_source_object_id,
       projection.target_entity_id,
       projection.authority_class,
       projection.witness_ids,
       1::SMALLINT AS support_kind,
       NULL::BIGINT AS support_token_id
  FROM execution.semantic_pnf_hyperedge AS edge
  JOIN execution.semantic_pnf_identity_projection AS projection
    ON projection.source_object_id = edge.object_id
UNION ALL
SELECT edge.factor_id,
       edge.slot_ordinal,
       edge.role_symbol_id,
       edge.object_id AS factor_object_id,
       projection.source_object_id AS identity_source_object_id,
       projection.target_entity_id,
       projection.authority_class,
       projection.witness_ids,
       2::SMALLINT AS support_kind,
       factor_support.token_id AS support_token_id
  FROM execution.semantic_pnf_hyperedge AS edge
  JOIN execution.semantic_pnf_factor AS factor
    ON factor.factor_id = edge.factor_id
  JOIN execution.semantic_pnf_region AS factor_region
    ON factor_region.region_id = factor.region_id
  JOIN execution.semantic_pnf_object_token_support AS factor_support
    ON factor_support.object_id = edge.object_id
  JOIN execution.semantic_pnf_object_token_support AS identity_support
    ON identity_support.token_id = factor_support.token_id
   AND identity_support.object_id <> edge.object_id
  JOIN execution.semantic_pnf_identity_projection AS projection
    ON projection.source_object_id = identity_support.object_id
  JOIN execution.semantic_pnf_object AS identity_object
    ON identity_object.object_id = projection.source_object_id
  JOIN execution.semantic_pnf_region AS identity_region
    ON identity_region.region_id = identity_object.region_id
   AND identity_region.run_id = factor_region.run_id
   AND identity_region.document_id = factor_region.document_id;

-- Fail closed when one factor argument/authority is structurally supported by
-- projections to more than one canonical entity.  When several representations
-- support the SAME entity, choose one deterministic witness path.
CREATE OR REPLACE VIEW execution.semantic_pnf_factor_identity_support_unique_v1 AS
WITH unambiguous AS (
    SELECT factor_id, slot_ordinal, authority_class
      FROM execution.semantic_pnf_factor_identity_support_v1
     GROUP BY factor_id, slot_ordinal, authority_class
    HAVING count(DISTINCT target_entity_id) = 1
)
SELECT DISTINCT ON (support.factor_id, support.slot_ordinal, support.authority_class)
       support.*
  FROM execution.semantic_pnf_factor_identity_support_v1 AS support
  JOIN unambiguous
    ON unambiguous.factor_id = support.factor_id
   AND unambiguous.slot_ordinal = support.slot_ordinal
   AND unambiguous.authority_class = support.authority_class
 ORDER BY support.factor_id,
          support.slot_ordinal,
          support.authority_class,
          support.support_kind,
          support.identity_source_object_id,
          support.support_token_id NULLS FIRST;

INSERT INTO execution.semantic_pnf_factor_derivation_rule
    (rule_ref, derivation_kind, rule_version, description, enabled)
VALUES
    (
        'identity-supported-substitution:v1',
        1,
        1,
        'Apply an already-admitted identity projection to a factor argument only through exact shared parser-token representation support. The support edge does not create an identity projection for the factor object.',
        TRUE
    )
ON CONFLICT (rule_ref) DO UPDATE SET
    derivation_kind = EXCLUDED.derivation_kind,
    rule_version = EXCLUDED.rule_version,
    description = EXCLUDED.description,
    enabled = EXCLUDED.enabled;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_factor_derivation_support (
    derivation_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_factor_derivation(derivation_id)
        ON DELETE CASCADE,
    slot_ordinal SMALLINT NOT NULL CHECK (slot_ordinal >= 0),
    identity_source_object_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE RESTRICT,
    target_entity_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_canonical_entity(entity_id)
        ON DELETE RESTRICT,
    authority_class SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_identity_authority_class(authority_class)
        ON DELETE RESTRICT,
    support_kind SMALLINT NOT NULL CHECK (support_kind IN (1, 2)),
    support_token_id BIGINT,
    identity_witness_ids BIGINT[] NOT NULL,
    PRIMARY KEY (derivation_id, slot_ordinal),
    CHECK (cardinality(identity_witness_ids) > 0),
    CHECK (
        (support_kind = 1 AND support_token_id IS NULL)
        OR (support_kind = 2 AND support_token_id IS NOT NULL)
    )
);
CREATE INDEX IF NOT EXISTS semantic_pnf_factor_derivation_support_source_idx
    ON execution.semantic_pnf_factor_derivation_support
       (identity_source_object_id, target_entity_id, authority_class,
        derivation_id);

CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_supported_identity_substitution_derivations(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE affected_count BIGINT := 0;
BEGIN
    -- Create one Level-3 derivation per factor/authority only when at least one
    -- argument gains identity applicability through exact token support that is
    -- not already the direct edge object.
    INSERT INTO execution.semantic_pnf_factor_derivation
        (derivation_ref, rule_ref, derivation_kind, derivation_state,
         epistemic_level, authority_class, scope_interface_id,
         conclusion_factor_type_symbol_id, conclusion_predicate_symbol_id,
         modal_state, temporal_state)
    SELECT 'identity-supported-substitution:' || factor.factor_id::TEXT || ':'
               || support.authority_class::TEXT,
           'identity-supported-substitution:v1',
           1,
           2,
           3,
           support.authority_class,
           interface.interface_id,
           factor.factor_type_symbol_id,
           factor.predicate_symbol_id,
           factor.modal_state,
           factor.temporal_state
      FROM execution.semantic_pnf_factor AS factor
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = factor.region_id
      JOIN execution.semantic_pnf_interface AS interface
        ON interface.region_id = region.region_id
      JOIN execution.semantic_pnf_factor_identity_support_unique_v1 AS support
        ON support.factor_id = factor.factor_id
       AND support.support_kind = 2
     WHERE region.run_id = selected_run_id
       AND region.document_id = selected_document_id
     GROUP BY factor.factor_id, support.authority_class,
              interface.interface_id,
              factor.factor_type_symbol_id,
              factor.predicate_symbol_id,
              factor.modal_state,
              factor.temporal_state
    ON CONFLICT (derivation_ref) DO NOTHING;

    INSERT INTO execution.semantic_pnf_factor_derivation_premise
        (derivation_id, premise_ordinal, factor_id)
    SELECT derivation.derivation_id, 0, factor.factor_id
      FROM execution.semantic_pnf_factor_derivation AS derivation
      JOIN execution.semantic_pnf_factor AS factor
        ON derivation.derivation_ref =
           'identity-supported-substitution:' || factor.factor_id::TEXT || ':'
           || derivation.authority_class::TEXT
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = factor.region_id
     WHERE derivation.rule_ref = 'identity-supported-substitution:v1'
       AND region.run_id = selected_run_id
       AND region.document_id = selected_document_id
    ON CONFLICT DO NOTHING;

    INSERT INTO execution.semantic_pnf_factor_derivation_argument
        (derivation_id, slot_ordinal, role_symbol_id, source_object_id,
         local_object_id, identity_entity_id, identity_witness_ids)
    SELECT derivation.derivation_id,
           edge.slot_ordinal,
           edge.role_symbol_id,
           edge.object_id,
           CASE WHEN support.target_entity_id IS NULL
                THEN edge.object_id ELSE NULL END,
           support.target_entity_id,
           support.witness_ids
      FROM execution.semantic_pnf_factor_derivation AS derivation
      JOIN execution.semantic_pnf_factor_derivation_premise AS premise
        ON premise.derivation_id = derivation.derivation_id
       AND premise.premise_ordinal = 0
      JOIN execution.semantic_pnf_factor AS factor
        ON factor.factor_id = premise.factor_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = factor.region_id
      JOIN execution.semantic_pnf_hyperedge AS edge
        ON edge.factor_id = factor.factor_id
      LEFT JOIN execution.semantic_pnf_factor_identity_support_unique_v1 AS support
        ON support.factor_id = edge.factor_id
       AND support.slot_ordinal = edge.slot_ordinal
       AND support.authority_class = derivation.authority_class
     WHERE derivation.rule_ref = 'identity-supported-substitution:v1'
       AND region.run_id = selected_run_id
       AND region.document_id = selected_document_id
    ON CONFLICT (derivation_id, slot_ordinal) DO NOTHING;

    INSERT INTO execution.semantic_pnf_factor_derivation_support
        (derivation_id, slot_ordinal, identity_source_object_id,
         target_entity_id, authority_class, support_kind, support_token_id,
         identity_witness_ids)
    SELECT derivation.derivation_id,
           edge.slot_ordinal,
           support.identity_source_object_id,
           support.target_entity_id,
           support.authority_class,
           support.support_kind,
           support.support_token_id,
           support.witness_ids
      FROM execution.semantic_pnf_factor_derivation AS derivation
      JOIN execution.semantic_pnf_factor_derivation_premise AS premise
        ON premise.derivation_id = derivation.derivation_id
       AND premise.premise_ordinal = 0
      JOIN execution.semantic_pnf_factor AS factor
        ON factor.factor_id = premise.factor_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = factor.region_id
      JOIN execution.semantic_pnf_hyperedge AS edge
        ON edge.factor_id = factor.factor_id
      JOIN execution.semantic_pnf_factor_identity_support_unique_v1 AS support
        ON support.factor_id = edge.factor_id
       AND support.slot_ordinal = edge.slot_ordinal
       AND support.authority_class = derivation.authority_class
     WHERE derivation.rule_ref = 'identity-supported-substitution:v1'
       AND region.run_id = selected_run_id
       AND region.document_id = selected_document_id
    ON CONFLICT (derivation_id, slot_ordinal) DO NOTHING;

    SELECT count(*)
      INTO affected_count
      FROM execution.semantic_pnf_factor_derivation AS derivation
      JOIN execution.semantic_pnf_factor_derivation_premise AS premise
        ON premise.derivation_id = derivation.derivation_id
      JOIN execution.semantic_pnf_factor AS factor
        ON factor.factor_id = premise.factor_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = factor.region_id
     WHERE derivation.rule_ref = 'identity-supported-substitution:v1'
       AND region.run_id = selected_run_id
       AND region.document_id = selected_document_id;
    RETURN affected_count;
END;
$$;

-- Preserve the existing semantic-derivation API and wire structural-support
-- applicability into the normal post-identity derivation refresh.
CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_semantic_derivations(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS TABLE (
    identity_witness_count BIGINT,
    identity_derivation_count BIGINT,
    composition_candidate_count BIGINT
)
LANGUAGE plpgsql
AS $$
DECLARE supported_identity_derivation_count BIGINT := 0;
BEGIN
    identity_witness_count := execution.refresh_numeric_pnf_identity_witnesses(
        selected_run_id,
        selected_document_id
    );
    identity_derivation_count :=
        execution.refresh_numeric_pnf_identity_substitution_derivations(
            selected_run_id,
            selected_document_id
        );
    supported_identity_derivation_count :=
        execution.refresh_numeric_pnf_supported_identity_substitution_derivations(
            selected_run_id,
            selected_document_id
        );
    identity_derivation_count :=
        identity_derivation_count + supported_identity_derivation_count;
    composition_candidate_count :=
        execution.refresh_numeric_pnf_factor_composition_candidates(
            selected_run_id,
            selected_document_id,
            16
        );
    RETURN NEXT;
END;
$$;

-- Alignment audit -------------------------------------------------------------
CREATE OR REPLACE VIEW execution.semantic_pnf_identity_factor_alignment_audit_v1 AS
SELECT projection.source_object_id,
       projection.target_entity_id,
       projection.authority_class,
       source_region.run_id,
       source_region.document_id,
       CASE
           WHEN EXISTS (
               SELECT 1
                 FROM execution.semantic_pnf_hyperedge AS edge
                WHERE edge.object_id = projection.source_object_id
           ) THEN 'direct_factor_participant'
           WHEN EXISTS (
               SELECT 1
                 FROM execution.semantic_pnf_factor_identity_support_v1 AS support
                WHERE support.identity_source_object_id = projection.source_object_id
                  AND support.authority_class = projection.authority_class
                  AND support.target_entity_id = projection.target_entity_id
                  AND support.support_kind = 2
           ) THEN 'exact_token_structural_support'
           WHEN EXISTS (
               SELECT 1
                 FROM execution.semantic_pnf_factor AS factor
                WHERE factor.region_id = source_object.region_id
           ) THEN 'same_region_unbridged'
           ELSE 'no_structural_bridge'
       END AS alignment_class
  FROM execution.semantic_pnf_identity_projection AS projection
  JOIN execution.semantic_pnf_object AS source_object
    ON source_object.object_id = projection.source_object_id
  JOIN execution.semantic_pnf_region AS source_region
    ON source_region.region_id = source_object.region_id;

CREATE OR REPLACE VIEW execution.semantic_pnf_identity_factor_alignment_summary_v1 AS
SELECT run_id,
       document_id,
       alignment_class,
       count(*)::BIGINT AS projection_count
  FROM execution.semantic_pnf_identity_factor_alignment_audit_v1
 GROUP BY run_id, document_id, alignment_class;

-- Typed-demand funnel ----------------------------------------------------------
CREATE OR REPLACE VIEW execution.semantic_pnf_demand_funnel_v1 AS
SELECT demand.demand_id,
       source_region.run_id,
       source_region.document_id,
       demand.state AS demand_state,
       count(DISTINCT universe.target_kind::TEXT || ':' || universe.target_id::TEXT)
           AS represented_candidate_count,
       count(DISTINCT CASE WHEN candidate_state.active
             THEN candidate_state.target_kind::TEXT || ':' || candidate_state.target_id::TEXT END)
           AS active_candidate_count,
       count(DISTINCT CASE WHEN candidate_state.execution_residual
             THEN candidate_state.target_kind::TEXT || ':' || candidate_state.target_id::TEXT END)
           AS residual_candidate_count,
       count(DISTINCT CASE WHEN candidate_state.refuted
             THEN candidate_state.target_kind::TEXT || ':' || candidate_state.target_id::TEXT END)
           AS refuted_candidate_count,
       count(DISTINCT evidence.evidence_id) AS evidence_count,
       count(DISTINCT CASE WHEN admission.admission_state = 2
             THEN witness.witness_id END) AS admitted_identity_witness_count,
       COALESCE(open_world.outside_model_possible, TRUE) AS outside_model_possible,
       COALESCE(open_world.resource_limited, FALSE) AS resource_limited
  FROM execution.semantic_pnf_demand AS demand
  JOIN execution.semantic_pnf_region AS source_region
    ON source_region.region_id = demand.source_region_id
  LEFT JOIN execution.semantic_pnf_candidate_universe AS universe
    ON universe.demand_id = demand.demand_id
  LEFT JOIN execution.semantic_pnf_candidate_state_v1 AS candidate_state
    ON candidate_state.demand_id = universe.demand_id
   AND candidate_state.target_kind = universe.target_kind
   AND candidate_state.target_id = universe.target_id
  LEFT JOIN execution.semantic_pnf_candidate_evidence AS evidence
    ON evidence.demand_id = demand.demand_id
  LEFT JOIN execution.semantic_pnf_identity_witness AS witness
    ON witness.demand_id = demand.demand_id
  LEFT JOIN execution.semantic_pnf_identity_witness_admission AS admission
    ON admission.witness_id = witness.witness_id
  LEFT JOIN execution.semantic_pnf_demand_open_world_state AS open_world
    ON open_world.demand_id = demand.demand_id
 GROUP BY demand.demand_id,
          source_region.run_id,
          source_region.document_id,
          demand.state,
          open_world.outside_model_possible,
          open_world.resource_limited;

CREATE OR REPLACE VIEW execution.semantic_pnf_candidate_compression_v1 AS
SELECT demand.demand_id,
       source_region.run_id,
       source_region.document_id,
       count(universe.target_id)::BIGINT AS represented_candidate_count,
       count(*) FILTER (WHERE state.active)::BIGINT AS active_candidate_count,
       count(*) FILTER (WHERE state.execution_residual)::BIGINT
           AS residual_candidate_count,
       count(*) FILTER (WHERE state.refuted)::BIGINT AS refuted_candidate_count,
       CASE WHEN count(universe.target_id) = 0 THEN NULL
            ELSE count(*) FILTER (WHERE state.active)::NUMERIC
                 / count(universe.target_id)::NUMERIC
       END AS active_compression_ratio,
       COALESCE(open_world.outside_model_possible, TRUE) AS outside_model_possible
  FROM execution.semantic_pnf_demand AS demand
  JOIN execution.semantic_pnf_region AS source_region
    ON source_region.region_id = demand.source_region_id
  LEFT JOIN execution.semantic_pnf_candidate_universe AS universe
    ON universe.demand_id = demand.demand_id
  LEFT JOIN execution.semantic_pnf_candidate_state_v1 AS state
    ON state.demand_id = universe.demand_id
   AND state.target_kind = universe.target_kind
   AND state.target_id = universe.target_id
  LEFT JOIN execution.semantic_pnf_demand_open_world_state AS open_world
    ON open_world.demand_id = demand.demand_id
 GROUP BY demand.demand_id,
          source_region.run_id,
          source_region.document_id,
          open_world.outside_model_possible;

-- Performance / retrieval observatory -----------------------------------------
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_runtime_stage_measurement (
    measurement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measurement_ref TEXT NOT NULL UNIQUE,
    workload_ref TEXT NOT NULL,
    run_id BIGINT,
    document_id BIGINT,
    stage_name TEXT NOT NULL,
    input_units BIGINT NOT NULL CHECK (input_units >= 0),
    generated_units BIGINT NOT NULL CHECK (generated_units >= 0),
    retained_units BIGINT NOT NULL CHECK (retained_units >= 0),
    output_units BIGINT NOT NULL CHECK (output_units >= 0),
    work_units BIGINT NOT NULL CHECK (work_units >= 0),
    elapsed_microseconds BIGINT NOT NULL CHECK (elapsed_microseconds >= 0),
    peak_memory_bytes BIGINT CHECK (peak_memory_bytes IS NULL OR peak_memory_bytes >= 0),
    measured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS semantic_pnf_runtime_stage_workload_idx
    ON execution.semantic_pnf_runtime_stage_measurement
       (workload_ref, stage_name, measured_at, measurement_id);

-- retrieval_kind: 1=exact numeric/equality, 2=object-token support,
-- 3=ordered/range (B-tree), 4=PG FTS lexical normalization/stemming,
-- 5=prefix/structural address, 6=vector neighbourhood proposal.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_retrieval_measurement (
    measurement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measurement_ref TEXT NOT NULL UNIQUE,
    workload_ref TEXT NOT NULL,
    retrieval_kind SMALLINT NOT NULL CHECK (retrieval_kind BETWEEN 1 AND 6),
    universe_units BIGINT NOT NULL CHECK (universe_units >= 0),
    frontier_units BIGINT NOT NULL CHECK (frontier_units >= 0),
    probe_microseconds BIGINT NOT NULL CHECK (probe_microseconds >= 0),
    downstream_work_units BIGINT NOT NULL CHECK (downstream_work_units >= 0),
    exact_downstream_required BOOLEAN NOT NULL DEFAULT FALSE,
    measured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (frontier_units <= universe_units),
    CHECK (retrieval_kind <> 6 OR exact_downstream_required)
);
CREATE INDEX IF NOT EXISTS semantic_pnf_retrieval_workload_idx
    ON execution.semantic_pnf_retrieval_measurement
       (workload_ref, retrieval_kind, measured_at, measurement_id);

CREATE OR REPLACE VIEW execution.semantic_pnf_runtime_parser_dominance_v1 AS
WITH latest AS (
    SELECT DISTINCT ON (workload_ref, stage_name)
           workload_ref, stage_name, elapsed_microseconds, work_units,
           measurement_id
      FROM execution.semantic_pnf_runtime_stage_measurement
     WHERE stage_name IN ('spacy', 'post_parser_total')
     ORDER BY workload_ref, stage_name, measurement_id DESC
)
SELECT parser.workload_ref,
       parser.elapsed_microseconds AS parser_elapsed_microseconds,
       semantics.elapsed_microseconds AS post_parser_elapsed_microseconds,
       parser.work_units AS parser_work_units,
       semantics.work_units AS post_parser_work_units,
       CASE WHEN semantics.elapsed_microseconds = 0 THEN NULL
            ELSE parser.elapsed_microseconds::NUMERIC
                 / semantics.elapsed_microseconds::NUMERIC
       END AS elapsed_dominance_ratio,
       CASE WHEN semantics.work_units = 0 THEN NULL
            ELSE parser.work_units::NUMERIC / semantics.work_units::NUMERIC
       END AS work_dominance_ratio
  FROM latest AS parser
  JOIN latest AS semantics
    ON semantics.workload_ref = parser.workload_ref
   AND semantics.stage_name = 'post_parser_total'
 WHERE parser.stage_name = 'spacy';

COMMIT;
