BEGIN;

-- Progressive evidence resolution -------------------------------------------------
--
-- H3/H6/H9 are cumulative evidence horizons over ONE durable candidate fibre.
-- This migration never converts a ranking/preference into an identity proof.
-- Existing frontier_resolution rows remain the proof-producing authority for
-- resolved_unique outcomes; this layer records only inductive preference and
-- exposes when an existing deductive proof agrees/disagrees with that surface.

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_progressive_resolution_run (
    progressive_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    horizon SMALLINT NOT NULL CHECK (horizon IN (3, 6, 9)),
    demand_count BIGINT NOT NULL CHECK (demand_count >= 0),
    preference_count BIGINT NOT NULL CHECK (preference_count >= 0),
    deductive_unique_count BIGINT NOT NULL CHECK (deductive_unique_count >= 0),
    unresolved_count BIGINT NOT NULL CHECK (unresolved_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS semantic_pnf_progressive_resolution_run_doc_idx
    ON execution.semantic_pnf_progressive_resolution_run
       (run_id, document_id, horizon, progressive_run_id DESC);

-- A preference winner exists only when one admissible represented candidate has
-- a non-neutral cumulative residual strictly greater than every other admissible
-- represented candidate at the requested horizon.  Ties and all-neutral fibres
-- remain unresolved.
CREATE OR REPLACE VIEW execution.semantic_pnf_progressive_preference_candidate_v1 AS
WITH ranked AS (
    SELECT state.demand_id,
           state.target_kind,
           state.target_id,
           state.horizon,
           state.signed_residual,
           state.evidence_count,
           state.active,
           state.execution_residual,
           state.current_planner_member,
           row_number() OVER (
               PARTITION BY state.demand_id, state.horizon
               ORDER BY state.signed_residual DESC,
                        state.evidence_count DESC,
                        state.target_kind,
                        state.target_id
           ) AS rank_ordinal,
           lead(state.signed_residual) OVER (
               PARTITION BY state.demand_id, state.horizon
               ORDER BY state.signed_residual DESC,
                        state.evidence_count DESC,
                        state.target_kind,
                        state.target_id
           ) AS next_residual
      FROM execution.semantic_pnf_candidate_horizon_state_v1 AS state
     WHERE state.represented_possible
       AND state.admissible
       AND NOT state.refuted
), winner AS (
    SELECT ranked.*,
           ranked.signed_residual <> 0
           AND (
               ranked.next_residual IS NULL
               OR ranked.signed_residual > ranked.next_residual
           ) AS strict_winner
      FROM ranked
     WHERE ranked.rank_ordinal = 1
)
SELECT demand_id,
       target_kind,
       target_id,
       horizon,
       signed_residual,
       evidence_count,
       active,
       execution_residual,
       current_planner_member,
       strict_winner
  FROM winner;

-- Existing proof and new preference are displayed side-by-side.  outcome_state
-- 2 is the existing resolved_unique proof state used by identity witness
-- production.  preference_only is therefore explicitly non-proof.
CREATE OR REPLACE VIEW execution.semantic_pnf_progressive_resolution_v1 AS
WITH proof AS (
    SELECT DISTINCT ON (resolution.demand_id)
           resolution.demand_id,
           resolution.outcome_state,
           resolution.selected_target_kind,
           resolution.selected_target_id,
           resolution.candidate_count,
           resolution.interface_id AS resolution_interface_id
      FROM execution.semantic_pnf_frontier_resolution AS resolution
     ORDER BY resolution.demand_id, resolution.interface_id DESC
), horizon AS (
    SELECT preference.*,
           demand.state AS demand_state,
           demand.reference_mode,
           open_world.outside_model_possible,
           open_world.coverage_witness_ref,
           open_world.resource_limited,
           proof.outcome_state AS proof_outcome_state,
           proof.selected_target_kind AS proof_target_kind,
           proof.selected_target_id AS proof_target_id,
           proof.candidate_count AS proof_candidate_count,
           proof.resolution_interface_id
      FROM execution.semantic_pnf_progressive_preference_candidate_v1 AS preference
      JOIN execution.semantic_pnf_demand AS demand
        ON demand.demand_id = preference.demand_id
      LEFT JOIN execution.semantic_pnf_demand_open_world_state AS open_world
        ON open_world.demand_id = preference.demand_id
      LEFT JOIN proof
        ON proof.demand_id = preference.demand_id
)
SELECT horizon.*,
       COALESCE(horizon.proof_outcome_state = 2, FALSE) AS deductive_unique,
       COALESCE(
           horizon.proof_outcome_state = 2
           AND horizon.proof_target_kind = horizon.target_kind
           AND horizon.proof_target_id = horizon.target_id,
           FALSE
       ) AS preference_agrees_with_proof,
       horizon.strict_winner
           AND NOT COALESCE(horizon.proof_outcome_state = 2, FALSE)
           AS preference_only,
       CASE
           WHEN horizon.proof_outcome_state = 2 THEN 'deductive_unique'
           WHEN horizon.strict_winner THEN 'inductive_preference'
           WHEN horizon.resource_limited THEN 'resource_limited'
           ELSE 'unresolved'
       END AS resolution_class
  FROM horizon;

-- Materialise current strict winners as a revisioned preference surface.  This
-- function cannot touch semantic_pnf_frontier_resolution or identity witnesses.
CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_progressive_preferences(
    selected_run_id BIGINT,
    selected_document_id BIGINT,
    selected_horizon SMALLINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    inserted_count BIGINT := 0;
    selected_count BIGINT := 0;
    deductive_count BIGINT := 0;
    unresolved_count BIGINT := 0;
BEGIN
    IF selected_horizon NOT IN (3, 6, 9) THEN
        RAISE EXCEPTION 'selected_horizon must be 3, 6, or 9';
    END IF;

    WITH document_demand AS (
        SELECT demand.demand_id
          FROM execution.semantic_pnf_demand AS demand
          JOIN execution.semantic_pnf_region AS region
            ON region.region_id = demand.source_region_id
         WHERE region.run_id = selected_run_id
           AND region.document_id = selected_document_id
    ), winner AS (
        SELECT preference.*
          FROM execution.semantic_pnf_progressive_preference_candidate_v1 AS preference
          JOIN document_demand AS document_demand
            ON document_demand.demand_id = preference.demand_id
         WHERE preference.horizon = selected_horizon
           AND preference.strict_winner
    ), revisioned AS (
        SELECT winner.*,
               COALESCE((
                   SELECT max(existing.revision)
                     FROM execution.semantic_pnf_candidate_preference AS existing
                    WHERE existing.demand_id = winner.demand_id
                      AND existing.target_kind = winner.target_kind
                      AND existing.target_id = winner.target_id
                      AND existing.horizon = winner.horizon
               ), 0) + 1 AS revision
          FROM winner
    )
    INSERT INTO execution.semantic_pnf_candidate_preference
        (demand_id, target_kind, target_id, horizon, revision,
         preferred, margin, evidence_count)
    SELECT revisioned.demand_id,
           revisioned.target_kind,
           revisioned.target_id,
           revisioned.horizon,
           revisioned.revision,
           TRUE,
           revisioned.signed_residual,
           revisioned.evidence_count
      FROM revisioned;
    GET DIAGNOSTICS inserted_count = ROW_COUNT;

    SELECT count(*) INTO selected_count
      FROM execution.semantic_pnf_demand AS demand
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = demand.source_region_id
     WHERE region.run_id = selected_run_id
       AND region.document_id = selected_document_id;

    SELECT count(*) FILTER (WHERE resolution.deductive_unique),
           count(*) FILTER (
               WHERE NOT resolution.deductive_unique
                 AND NOT resolution.strict_winner
           )
      INTO deductive_count, unresolved_count
      FROM execution.semantic_pnf_progressive_resolution_v1 AS resolution
      JOIN execution.semantic_pnf_demand AS demand
        ON demand.demand_id = resolution.demand_id
      JOIN execution.semantic_pnf_region AS region
        ON region.region_id = demand.source_region_id
     WHERE region.run_id = selected_run_id
       AND region.document_id = selected_document_id
       AND resolution.horizon = selected_horizon;

    -- Demands with no represented candidate never appear in the progressive
    -- candidate view and therefore remain unresolved rather than disappearing.
    unresolved_count := unresolved_count + GREATEST(
        selected_count - (
            SELECT count(DISTINCT resolution.demand_id)
              FROM execution.semantic_pnf_progressive_resolution_v1 AS resolution
              JOIN execution.semantic_pnf_demand AS demand
                ON demand.demand_id = resolution.demand_id
              JOIN execution.semantic_pnf_region AS region
                ON region.region_id = demand.source_region_id
             WHERE region.run_id = selected_run_id
               AND region.document_id = selected_document_id
               AND resolution.horizon = selected_horizon
        ),
        0
    );

    INSERT INTO execution.semantic_pnf_progressive_resolution_run
        (run_id, document_id, horizon, demand_count, preference_count,
         deductive_unique_count, unresolved_count)
    VALUES
        (selected_run_id, selected_document_id, selected_horizon,
         selected_count, inserted_count, deductive_count, unresolved_count);

    RETURN inserted_count;
END;
$$;

-- Escalation observatory: no candidate identity is regenerated between horizons;
-- the same (demand,target) fibre is inspected cumulatively at H3/H6/H9.
CREATE OR REPLACE VIEW execution.semantic_pnf_horizon_escalation_v1 AS
WITH by_horizon AS (
    SELECT demand_id,
           horizon,
           count(*) FILTER (WHERE represented_possible) AS represented_count,
           count(*) FILTER (WHERE active) AS active_count,
           count(*) FILTER (WHERE admissible AND NOT refuted) AS admissible_count,
           count(*) FILTER (WHERE signed_residual <> 0) AS evidenced_count,
           count(*) FILTER (WHERE preferred) AS preferred_count
      FROM execution.semantic_pnf_candidate_horizon_state_v1
     GROUP BY demand_id, horizon
)
SELECT demand_id,
       max(represented_count) FILTER (WHERE horizon = 3) AS h3_represented,
       max(represented_count) FILTER (WHERE horizon = 6) AS h6_represented,
       max(represented_count) FILTER (WHERE horizon = 9) AS h9_represented,
       max(evidenced_count) FILTER (WHERE horizon = 3) AS h3_evidenced,
       max(evidenced_count) FILTER (WHERE horizon = 6) AS h6_evidenced,
       max(evidenced_count) FILTER (WHERE horizon = 9) AS h9_evidenced,
       max(preferred_count) FILTER (WHERE horizon = 3) AS h3_preferred,
       max(preferred_count) FILTER (WHERE horizon = 6) AS h6_preferred,
       max(preferred_count) FILTER (WHERE horizon = 9) AS h9_preferred,
       count(DISTINCT represented_count) = 1 AS fibre_cardinality_invariant
  FROM by_horizon
 GROUP BY demand_id;

COMMIT;
