BEGIN;

-- 096: late external-demand planning.  External providers are downstream of
-- consumer-specific H9 residual planning, not part of ordinary parser/PNF work.
-- A fresh provider request exists only for a deduplicated cache miss.

-- Consumer/query-specific external needs are compiled explicitly.  We do not
-- infer "proper noun => Wikidata".  A consumer must expose the external fact it
-- can actually observe/use.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_consumer_external_need (
    demand_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE CASCADE,
    consumer_ref TEXT NOT NULL,
    query_ref TEXT NOT NULL,
    policy_ref TEXT NOT NULL DEFAULT '',
    need_kind SMALLINT NOT NULL CHECK (need_kind IN (1,2,3)),
    -- 1 candidate discovery; 2 property/axis enrichment; 3 identity alignment.
    provider_id SMALLINT NOT NULL DEFAULT 1
        REFERENCES execution.semantic_pnf_world_provider(provider_id) ON DELETE RESTRICT,
    axis_kind SMALLINT,
    provider_property_numeric_id BIGINT,
    priority SMALLINT NOT NULL DEFAULT 100,
    need_revision BIGINT NOT NULL DEFAULT 1 CHECK (need_revision > 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (
        demand_id,consumer_ref,query_ref,policy_ref,need_kind,provider_id,
        need_revision
    ),
    CHECK (
        (need_kind = 1 AND axis_kind IS NULL AND provider_property_numeric_id IS NULL)
        OR
        (need_kind = 2 AND axis_kind IS NOT NULL
                       AND provider_property_numeric_id IS NOT NULL
                       AND provider_property_numeric_id > 0)
        OR
        (need_kind = 3 AND axis_kind IS NULL AND provider_property_numeric_id IS NULL)
    )
);
CREATE INDEX IF NOT EXISTS semantic_pnf_consumer_external_need_active_idx
    ON execution.semantic_pnf_consumer_external_need
       (consumer_ref,query_ref,policy_ref,demand_id,priority)
    WHERE active;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_external_request (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(request_digest)=32),
    provider_id SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_world_provider(provider_id) ON DELETE RESTRICT,
    request_kind SMALLINT NOT NULL CHECK (request_kind IN (1,2,3)),
    label_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    world_entity_id BIGINT
        REFERENCES execution.semantic_pnf_world_entity_numeric(world_entity_id) ON DELETE RESTRICT,
    provider_property_numeric_id BIGINT,
    axis_kind SMALLINT,
    request_revision BIGINT NOT NULL DEFAULT 1 CHECK (request_revision > 0),
    request_state SMALLINT NOT NULL DEFAULT 1 CHECK (request_state IN (1,2,3,4,5,6)),
    -- 1 planned/cache-probe; 2 cache-satisfied; 3 provider-ready;
    -- 4 leased; 5 acquired; 6 failed/retryable.
    priority SMALLINT NOT NULL DEFAULT 100,
    lease_owner TEXT,
    lease_expires_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_error_ref TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (request_kind=1 AND label_symbol_id IS NOT NULL
                        AND world_entity_id IS NULL
                        AND provider_property_numeric_id IS NULL)
        OR
        (request_kind=2 AND world_entity_id IS NOT NULL
                        AND provider_property_numeric_id IS NOT NULL
                        AND provider_property_numeric_id > 0
                        AND axis_kind IS NOT NULL)
        OR
        (request_kind=3 AND world_entity_id IS NOT NULL
                        AND provider_property_numeric_id IS NULL)
    )
);
CREATE INDEX IF NOT EXISTS semantic_pnf_external_request_ready_idx
    ON execution.semantic_pnf_external_request
       (provider_id,priority,request_id)
    WHERE request_state=3;
CREATE INDEX IF NOT EXISTS semantic_pnf_external_request_subject_idx
    ON execution.semantic_pnf_external_request
       (provider_id,world_entity_id,provider_property_numeric_id,request_id);

-- Many consumer/demand fibres may share one physical provider request.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_external_request_member (
    request_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_external_request(request_id) ON DELETE CASCADE,
    demand_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE CASCADE,
    consumer_ref TEXT NOT NULL,
    query_ref TEXT NOT NULL,
    policy_ref TEXT NOT NULL DEFAULT '',
    need_kind SMALLINT NOT NULL CHECK (need_kind IN (1,2,3)),
    PRIMARY KEY(request_id,demand_id,consumer_ref,query_ref,policy_ref,need_kind)
);
CREATE INDEX IF NOT EXISTS semantic_pnf_external_request_member_demand_idx
    ON execution.semantic_pnf_external_request_member
       (demand_id,consumer_ref,query_ref,policy_ref,request_id);

-- Immutable provider evidence cache.  This is cold external evidence, not an
-- identity/type promotion.  Downstream adapters must explicitly turn a cached
-- fact into contextual pressure or a proof-bearing identity witness.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_external_evidence (
    external_evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(evidence_digest)=32),
    request_id BIGINT
        REFERENCES execution.semantic_pnf_external_request(request_id) ON DELETE SET NULL,
    provider_id SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_world_provider(provider_id) ON DELETE RESTRICT,
    subject_world_entity_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_world_entity_numeric(world_entity_id) ON DELETE CASCADE,
    provider_property_numeric_id BIGINT NOT NULL CHECK (provider_property_numeric_id > 0),
    axis_kind SMALLINT,
    value_kind SMALLINT NOT NULL CHECK (value_kind IN (1,2,3)),
    -- 1 world entity, 2 local symbol, 3 numeric scalar.
    value_world_entity_id BIGINT
        REFERENCES execution.semantic_pnf_world_entity_numeric(world_entity_id) ON DELETE RESTRICT,
    value_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    value_numeric BIGINT,
    provider_revision BIGINT,
    source_ref TEXT NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (value_kind=1 AND value_world_entity_id IS NOT NULL
                      AND value_symbol_id IS NULL AND value_numeric IS NULL)
        OR
        (value_kind=2 AND value_world_entity_id IS NULL
                      AND value_symbol_id IS NOT NULL AND value_numeric IS NULL)
        OR
        (value_kind=3 AND value_world_entity_id IS NULL
                      AND value_symbol_id IS NULL AND value_numeric IS NOT NULL)
    )
);
CREATE INDEX IF NOT EXISTS semantic_pnf_external_evidence_probe_idx
    ON execution.semantic_pnf_external_evidence
       (provider_id,subject_world_entity_id,provider_property_numeric_id,external_evidence_id);

CREATE OR REPLACE FUNCTION execution.ensure_numeric_pnf_external_request(
    selected_provider_id SMALLINT,
    selected_request_kind SMALLINT,
    selected_label_symbol_id BIGINT,
    selected_world_entity_id BIGINT,
    selected_provider_property_numeric_id BIGINT,
    selected_axis_kind SMALLINT,
    selected_request_revision BIGINT,
    selected_priority SMALLINT DEFAULT 100
) RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE digest_value BYTEA; resolved_request_id BIGINT;
BEGIN
    digest_value := digest(
        int2send(selected_provider_id)
        || int2send(selected_request_kind)
        || int8send(COALESCE(selected_label_symbol_id,0))
        || int8send(COALESCE(selected_world_entity_id,0))
        || int8send(COALESCE(selected_provider_property_numeric_id,0))
        || int2send(COALESCE(selected_axis_kind,0))
        || int8send(selected_request_revision),
        'sha256'
    );

    INSERT INTO execution.semantic_pnf_external_request
        (request_digest,provider_id,request_kind,label_symbol_id,world_entity_id,
         provider_property_numeric_id,axis_kind,request_revision,priority)
    VALUES (digest_value,selected_provider_id,selected_request_kind,
            selected_label_symbol_id,selected_world_entity_id,
            selected_provider_property_numeric_id,selected_axis_kind,
            selected_request_revision,selected_priority)
    ON CONFLICT(request_digest) DO UPDATE SET
        priority=LEAST(execution.semantic_pnf_external_request.priority,EXCLUDED.priority),
        updated_at=CURRENT_TIMESTAMP
    RETURNING request_id INTO resolved_request_id;
    RETURN resolved_request_id;
END;
$$;

-- Probe all planned requests against durable local caches before a provider can
-- see them.  Acquired rows remain acquired; leased rows are not stolen here.
CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_external_request_cache_state()
RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE affected BIGINT := 0; n BIGINT := 0;
BEGIN
    UPDATE execution.semantic_pnf_external_request AS request
       SET request_state=2,updated_at=CURRENT_TIMESTAMP
     WHERE request.request_state IN (1,3,6)
       AND (
           (request.request_kind=1 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_label_world_candidate AS candidate
                WHERE candidate.label_symbol_id=request.label_symbol_id
           ))
           OR
           (request.request_kind=2 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_external_evidence AS evidence
                WHERE evidence.provider_id=request.provider_id
                  AND evidence.subject_world_entity_id=request.world_entity_id
                  AND evidence.provider_property_numeric_id=request.provider_property_numeric_id
           ))
           OR
           (request.request_kind=3 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_world_entity_numeric AS world
                WHERE world.world_entity_id=request.world_entity_id
                  AND world.canonical_entity_id IS NOT NULL
           ))
       );
    GET DIAGNOSTICS n=ROW_COUNT; affected:=affected+n;

    UPDATE execution.semantic_pnf_external_request AS request
       SET request_state=3,updated_at=CURRENT_TIMESTAMP,last_error_ref=NULL
     WHERE request.request_state IN (1,2,6)
       AND NOT (
           (request.request_kind=1 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_label_world_candidate AS candidate
                WHERE candidate.label_symbol_id=request.label_symbol_id
           ))
           OR
           (request.request_kind=2 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_external_evidence AS evidence
                WHERE evidence.provider_id=request.provider_id
                  AND evidence.subject_world_entity_id=request.world_entity_id
                  AND evidence.provider_property_numeric_id=request.provider_property_numeric_id
           ))
           OR
           (request.request_kind=3 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_world_entity_numeric AS world
                WHERE world.world_entity_id=request.world_entity_id
                  AND world.canonical_entity_id IS NOT NULL
           ))
       );
    GET DIAGNOSTICS n=ROW_COUNT; affected:=affected+n;
    RETURN affected;
END;
$$;

CREATE OR REPLACE FUNCTION execution.plan_numeric_pnf_external_demands_for_consumer(
    selected_run_id BIGINT,
    selected_document_id BIGINT,
    selected_consumer_ref TEXT,
    selected_query_ref TEXT,
    selected_policy_ref TEXT DEFAULT ''
) RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE need RECORD; candidate RECORD; attachment RECORD; request_id_value BIGINT;
        affected BIGINT := 0;
BEGIN
    -- Only the consumer-specific unresolved H9 residual may generate an external
    -- request.  H3/H6 work and already-sufficient demands are invisible here.
    FOR need IN
        SELECT need.*,demand.lexical_symbol_id,demand.source_object_id
          FROM execution.semantic_pnf_consumer_external_need AS need
          JOIN execution.semantic_pnf_consumer_horizon_work_queue AS work
            ON work.demand_id=need.demand_id
           AND work.consumer_ref=need.consumer_ref
           AND work.query_ref=need.query_ref
           AND work.policy_ref=need.policy_ref
           AND work.horizon=9 AND work.work_state=1
          JOIN execution.semantic_pnf_demand AS demand ON demand.demand_id=need.demand_id
          JOIN execution.semantic_pnf_region AS region ON region.region_id=demand.source_region_id
         WHERE need.active
           AND need.consumer_ref=selected_consumer_ref
           AND need.query_ref=selected_query_ref
           AND need.policy_ref=selected_policy_ref
           AND region.run_id=selected_run_id
           AND region.document_id=selected_document_id
           AND NOT execution.numeric_pnf_consumer_stop_at_horizon(
               need.demand_id,need.consumer_ref,need.query_ref,need.policy_ref,6
           )
         ORDER BY need.priority,need.demand_id
    LOOP
        IF need.lexical_symbol_id IS NULL AND need.need_kind IN (1,2) THEN
            CONTINUE;
        END IF;

        -- Candidate discovery is itself deduplicated by provider+label+revision.
        IF need.need_kind IN (1,2)
           AND NOT EXISTS (
               SELECT 1 FROM execution.semantic_pnf_label_world_candidate AS cached
                WHERE cached.label_symbol_id=need.lexical_symbol_id
           ) THEN
            request_id_value := execution.ensure_numeric_pnf_external_request(
                need.provider_id,1,need.lexical_symbol_id,NULL,NULL,NULL,
                need.need_revision,need.priority
            );
            INSERT INTO execution.semantic_pnf_external_request_member
                (request_id,demand_id,consumer_ref,query_ref,policy_ref,need_kind)
            VALUES (request_id_value,need.demand_id,need.consumer_ref,need.query_ref,
                    need.policy_ref,need.need_kind)
            ON CONFLICT DO NOTHING;
            affected:=affected+1;
            CONTINUE;
        END IF;

        IF need.need_kind=1 THEN
            -- Existing candidate fibre satisfies discovery without provider work.
            CONTINUE;
        ELSIF need.need_kind=2 THEN
            -- Enrich only the property/axis explicitly demanded by the consumer,
            -- and only for candidates already in the local fibre.
            FOR candidate IN
                SELECT candidate.world_entity_id
                  FROM execution.semantic_pnf_label_world_candidate AS candidate
                 WHERE candidate.label_symbol_id=need.lexical_symbol_id
                 ORDER BY candidate.candidate_ordinal,candidate.world_entity_id
            LOOP
                request_id_value := execution.ensure_numeric_pnf_external_request(
                    need.provider_id,2,need.lexical_symbol_id,candidate.world_entity_id,
                    need.provider_property_numeric_id,need.axis_kind,
                    need.need_revision,need.priority
                );
                INSERT INTO execution.semantic_pnf_external_request_member
                    (request_id,demand_id,consumer_ref,query_ref,policy_ref,need_kind)
                VALUES (request_id_value,need.demand_id,need.consumer_ref,need.query_ref,
                        need.policy_ref,need.need_kind)
                ON CONFLICT DO NOTHING;
                affected:=affected+1;
            END LOOP;
        ELSE
            -- Identity alignment is late even inside H9: only a world candidate
            -- already attached to a token supporting this demand's source object
            -- is eligible.  Contextual preference still does not prove identity.
            FOR attachment IN
                SELECT DISTINCT attachment.world_entity_id,attachment.label_symbol_id
                  FROM execution.semantic_pnf_object_token_support AS support
                  JOIN execution.semantic_pnf_mention_world_attachment AS attachment
                    ON attachment.token_id=support.token_id
                 WHERE support.object_id=need.source_object_id
                   AND attachment.attachment_state=1
            LOOP
                request_id_value := execution.ensure_numeric_pnf_external_request(
                    need.provider_id,3,attachment.label_symbol_id,
                    attachment.world_entity_id,NULL,NULL,
                    need.need_revision,need.priority
                );
                INSERT INTO execution.semantic_pnf_external_request_member
                    (request_id,demand_id,consumer_ref,query_ref,policy_ref,need_kind)
                VALUES (request_id_value,need.demand_id,need.consumer_ref,need.query_ref,
                        need.policy_ref,need.need_kind)
                ON CONFLICT DO NOTHING;
                affected:=affected+1;
            END LOOP;
        END IF;
    END LOOP;

    PERFORM execution.refresh_numeric_pnf_external_request_cache_state();
    RETURN affected;
END;
$$;

-- Claim a small provider microbatch.  Deduplication happens before this point,
-- so one leased request may serve many semantic demands/mentions.
CREATE OR REPLACE FUNCTION execution.claim_numeric_pnf_external_provider_batch(
    selected_provider_id SMALLINT,
    selected_worker_ref TEXT,
    selected_limit INTEGER DEFAULT 32,
    selected_lease_seconds INTEGER DEFAULT 300
) RETURNS TABLE(
    request_id BIGINT,
    request_kind SMALLINT,
    label_symbol_id BIGINT,
    world_entity_id BIGINT,
    provider_property_numeric_id BIGINT,
    axis_kind SMALLINT,
    request_revision BIGINT
) LANGUAGE plpgsql AS $$
BEGIN
    IF selected_limit < 1 OR selected_limit > 256 THEN
        RAISE EXCEPTION 'selected_limit must be in 1..256';
    END IF;
    IF selected_lease_seconds < 1 THEN
        RAISE EXCEPTION 'selected_lease_seconds must be positive';
    END IF;

    PERFORM execution.refresh_numeric_pnf_external_request_cache_state();

    RETURN QUERY
    WITH picked AS (
        SELECT request.request_id
          FROM execution.semantic_pnf_external_request AS request
         WHERE request.provider_id=selected_provider_id
           AND (
               request.request_state=3
               OR (request.request_state=4 AND request.lease_expires_at<CURRENT_TIMESTAMP)
           )
         ORDER BY request.priority,request.request_id
         FOR UPDATE SKIP LOCKED
         LIMIT selected_limit
    ), leased AS (
        UPDATE execution.semantic_pnf_external_request AS request
           SET request_state=4,
               lease_owner=selected_worker_ref,
               lease_expires_at=CURRENT_TIMESTAMP
                   + make_interval(secs => selected_lease_seconds),
               attempt_count=request.attempt_count+1,
               updated_at=CURRENT_TIMESTAMP
          FROM picked
         WHERE request.request_id=picked.request_id
        RETURNING request.*
    )
    SELECT leased.request_id,leased.request_kind,leased.label_symbol_id,
           leased.world_entity_id,leased.provider_property_numeric_id,
           leased.axis_kind,leased.request_revision
      FROM leased
     ORDER BY leased.priority,leased.request_id;
END;
$$;

CREATE OR REPLACE FUNCTION execution.record_numeric_pnf_external_evidence(
    selected_request_id BIGINT,
    selected_evidence_digest BYTEA,
    selected_subject_world_entity_id BIGINT,
    selected_provider_property_numeric_id BIGINT,
    selected_axis_kind SMALLINT,
    selected_value_kind SMALLINT,
    selected_value_world_entity_id BIGINT,
    selected_value_symbol_id BIGINT,
    selected_value_numeric BIGINT,
    selected_provider_revision BIGINT,
    selected_source_ref TEXT
) RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE provider_value SMALLINT; evidence_id_value BIGINT;
BEGIN
    SELECT provider_id INTO STRICT provider_value
      FROM execution.semantic_pnf_external_request
     WHERE request_id=selected_request_id;
    INSERT INTO execution.semantic_pnf_external_evidence
        (evidence_digest,request_id,provider_id,subject_world_entity_id,
         provider_property_numeric_id,axis_kind,value_kind,value_world_entity_id,
         value_symbol_id,value_numeric,provider_revision,source_ref)
    VALUES (selected_evidence_digest,selected_request_id,provider_value,
            selected_subject_world_entity_id,selected_provider_property_numeric_id,
            selected_axis_kind,selected_value_kind,selected_value_world_entity_id,
            selected_value_symbol_id,selected_value_numeric,selected_provider_revision,
            selected_source_ref)
    ON CONFLICT(evidence_digest) DO UPDATE SET request_id=EXCLUDED.request_id
    RETURNING external_evidence_id INTO evidence_id_value;

    UPDATE execution.semantic_pnf_external_request
       SET request_state=5,lease_owner=NULL,lease_expires_at=NULL,
           last_error_ref=NULL,updated_at=CURRENT_TIMESTAMP
     WHERE request_id=selected_request_id;
    RETURN evidence_id_value;
END;
$$;

CREATE OR REPLACE FUNCTION execution.complete_numeric_pnf_external_request(
    selected_request_id BIGINT
) RETURNS BOOLEAN LANGUAGE plpgsql AS $$
BEGIN
    UPDATE execution.semantic_pnf_external_request
       SET request_state=5,lease_owner=NULL,lease_expires_at=NULL,
           last_error_ref=NULL,updated_at=CURRENT_TIMESTAMP
     WHERE request_id=selected_request_id;
    RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION execution.fail_numeric_pnf_external_request(
    selected_request_id BIGINT,
    selected_error_ref TEXT
) RETURNS BOOLEAN LANGUAGE plpgsql AS $$
BEGIN
    UPDATE execution.semantic_pnf_external_request
       SET request_state=6,lease_owner=NULL,lease_expires_at=NULL,
           last_error_ref=selected_error_ref,updated_at=CURRENT_TIMESTAMP
     WHERE request_id=selected_request_id;
    RETURN FOUND;
END;
$$;

CREATE OR REPLACE VIEW execution.semantic_pnf_external_call_economy_v1 AS
SELECT request.provider_id,
       count(*)::BIGINT AS unique_external_requests,
       count(*) FILTER (WHERE request.request_state=2)::BIGINT AS cache_satisfied_requests,
       count(*) FILTER (WHERE request.request_state=3)::BIGINT AS provider_ready_requests,
       count(*) FILTER (WHERE request.request_state=4)::BIGINT AS leased_requests,
       count(*) FILTER (WHERE request.request_state=5)::BIGINT AS acquired_requests,
       COALESCE(sum(member.member_count),0)::BIGINT AS semantic_request_members,
       CASE WHEN count(*)=0 THEN NULL
            ELSE COALESCE(sum(member.member_count),0)::NUMERIC / count(*)::NUMERIC
       END AS semantic_members_per_unique_request
  FROM execution.semantic_pnf_external_request AS request
  LEFT JOIN (
      SELECT request_id,count(*)::BIGINT AS member_count
        FROM execution.semantic_pnf_external_request_member
       GROUP BY request_id
  ) AS member USING (request_id)
 GROUP BY request.provider_id;

COMMIT;
