BEGIN;

-- 098: harden external need identity/call economy after source audit.
-- Multiple property axes may be demanded by the same consumer/demand, expired
-- leases are cache-probed before retry, provider evidence remains immutable, and
-- empirical provider-call counts are persisted explicitly.

ALTER TABLE execution.semantic_pnf_consumer_external_need
    ADD COLUMN IF NOT EXISTS need_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE execution.semantic_pnf_consumer_external_need
    DROP CONSTRAINT IF EXISTS semantic_pnf_consumer_external_need_pkey;
ALTER TABLE execution.semantic_pnf_consumer_external_need
    ADD CONSTRAINT semantic_pnf_consumer_external_need_pkey PRIMARY KEY(need_id);

CREATE UNIQUE INDEX IF NOT EXISTS semantic_pnf_consumer_external_need_identity_idx
    ON execution.semantic_pnf_consumer_external_need (
        demand_id,consumer_ref,query_ref,policy_ref,need_kind,provider_id,
        COALESCE(axis_kind,0),COALESCE(provider_property_numeric_id,0),need_revision
    );

CREATE OR REPLACE FUNCTION execution.record_numeric_pnf_consumer_external_need(
    selected_demand_id BIGINT,
    selected_consumer_ref TEXT,
    selected_query_ref TEXT,
    selected_policy_ref TEXT,
    selected_need_kind SMALLINT,
    selected_provider_id SMALLINT,
    selected_axis_kind SMALLINT,
    selected_provider_property_numeric_id BIGINT,
    selected_priority SMALLINT,
    selected_need_revision BIGINT,
    selected_active BOOLEAN
) RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE resolved_need_id BIGINT;
BEGIN
    IF selected_need_kind NOT IN (1,2,3) THEN
        RAISE EXCEPTION 'external need kind must be discovery, property, or identity';
    END IF;
    IF selected_need_kind=2 AND (
        selected_axis_kind IS NULL
        OR selected_provider_property_numeric_id IS NULL
        OR selected_provider_property_numeric_id<=0
    ) THEN
        RAISE EXCEPTION 'property need requires positive property id and axis';
    END IF;
    IF selected_need_kind<>2 AND (
        selected_axis_kind IS NOT NULL OR selected_provider_property_numeric_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'discovery/identity need cannot carry property-axis coordinates';
    END IF;

    INSERT INTO execution.semantic_pnf_consumer_external_need
        (demand_id,consumer_ref,query_ref,policy_ref,need_kind,provider_id,
         axis_kind,provider_property_numeric_id,priority,need_revision,active)
    VALUES (selected_demand_id,selected_consumer_ref,selected_query_ref,
            selected_policy_ref,selected_need_kind,selected_provider_id,
            selected_axis_kind,selected_provider_property_numeric_id,
            selected_priority,selected_need_revision,selected_active)
    ON CONFLICT DO NOTHING;

    SELECT need_id INTO STRICT resolved_need_id
      FROM execution.semantic_pnf_consumer_external_need AS need
     WHERE need.demand_id=selected_demand_id
       AND need.consumer_ref=selected_consumer_ref
       AND need.query_ref=selected_query_ref
       AND need.policy_ref=selected_policy_ref
       AND need.need_kind=selected_need_kind
       AND need.provider_id=selected_provider_id
       AND COALESCE(need.axis_kind,0)=COALESCE(selected_axis_kind,0)
       AND COALESCE(need.provider_property_numeric_id,0)=
           COALESCE(selected_provider_property_numeric_id,0)
       AND need.need_revision=selected_need_revision;

    UPDATE execution.semantic_pnf_consumer_external_need
       SET priority=selected_priority,active=selected_active
     WHERE need_id=resolved_need_id;
    RETURN resolved_need_id;
END;
$$;

-- Re-probe expired leases before they are eligible to be re-leased.  If another
-- worker/corpus event populated the cache while a lease was outstanding, the
-- network request disappears instead of being retried.
CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_external_request_cache_state()
RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE affected BIGINT := 0; n BIGINT := 0;
BEGIN
    UPDATE execution.semantic_pnf_external_request AS request
       SET request_state=2,lease_owner=NULL,lease_expires_at=NULL,
           last_error_ref=NULL,updated_at=CURRENT_TIMESTAMP
     WHERE (
            request.request_state IN (1,3,6)
            OR (request.request_state=4 AND request.lease_expires_at<CURRENT_TIMESTAMP)
       )
       AND (
           (request.request_kind=1 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_label_world_candidate AS candidate
                WHERE candidate.label_symbol_id=request.label_symbol_id
           ))
           OR
           (request.request_kind=2 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_external_evidence AS evidence
                WHERE evidence.provider_id=request.provider_id
                  AND evidence.subject_world_entity_id=request.world_entity_id
                  AND evidence.provider_property_numeric_id=request.provider_property_numeric_id
           ))
           OR
           (request.request_kind=3 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_world_entity_numeric AS world
                WHERE world.world_entity_id=request.world_entity_id
                  AND world.canonical_entity_id IS NOT NULL
           ))
       );
    GET DIAGNOSTICS n=ROW_COUNT; affected:=affected+n;

    UPDATE execution.semantic_pnf_external_request AS request
       SET request_state=3,lease_owner=NULL,lease_expires_at=NULL,
           last_error_ref=NULL,updated_at=CURRENT_TIMESTAMP
     WHERE (
            request.request_state IN (1,2,6)
            OR (request.request_state=4 AND request.lease_expires_at<CURRENT_TIMESTAMP)
       )
       AND NOT (
           (request.request_kind=1 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_label_world_candidate AS candidate
                WHERE candidate.label_symbol_id=request.label_symbol_id
           ))
           OR
           (request.request_kind=2 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_external_evidence AS evidence
                WHERE evidence.provider_id=request.provider_id
                  AND evidence.subject_world_entity_id=request.world_entity_id
                  AND evidence.provider_property_numeric_id=request.provider_property_numeric_id
           ))
           OR
           (request.request_kind=3 AND EXISTS (
               SELECT 1 FROM execution.semantic_pnf_world_entity_numeric AS world
                WHERE world.world_entity_id=request.world_entity_id
                  AND world.canonical_entity_id IS NOT NULL
           ))
       );
    GET DIAGNOSTICS n=ROW_COUNT; affected:=affected+n;
    RETURN affected;
END;
$$;

-- External evidence is immutable. An idempotent repeated digest reuses the
-- existing evidence row and must not rewrite its original request/provenance.
CREATE OR REPLACE FUNCTION execution.record_numeric_pnf_external_evidence(
    selected_request_id BIGINT,
    selected_evidence_digest BYTEA,
    selected_subject_world_entity_id BIGINT,
    selected_provider_property_numeric_id BIGINT,
    selected_axis_kind SMALLINT,
    selected_value_kind SMALLINT,
    selected_value_world_entity_id BIGINT,
    selected_value_symbol_id BIGINT,
    selected_value_numeric BIGINT,
    selected_provider_revision BIGINT,
    selected_source_ref TEXT
) RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE provider_value SMALLINT; evidence_id_value BIGINT;
BEGIN
    SELECT provider_id INTO STRICT provider_value
      FROM execution.semantic_pnf_external_request
     WHERE request_id=selected_request_id;

    INSERT INTO execution.semantic_pnf_external_evidence
        (evidence_digest,request_id,provider_id,subject_world_entity_id,
         provider_property_numeric_id,axis_kind,value_kind,value_world_entity_id,
         value_symbol_id,value_numeric,provider_revision,source_ref)
    VALUES (selected_evidence_digest,selected_request_id,provider_value,
            selected_subject_world_entity_id,selected_provider_property_numeric_id,
            selected_axis_kind,selected_value_kind,selected_value_world_entity_id,
            selected_value_symbol_id,selected_value_numeric,selected_provider_revision,
            selected_source_ref)
    ON CONFLICT(evidence_digest) DO NOTHING
    RETURNING external_evidence_id INTO evidence_id_value;

    IF evidence_id_value IS NULL THEN
        SELECT external_evidence_id INTO STRICT evidence_id_value
          FROM execution.semantic_pnf_external_evidence
         WHERE evidence_digest=selected_evidence_digest;
    END IF;

    PERFORM execution.materialize_numeric_pnf_external_context_requirement(
        evidence_id_value,1
    );

    UPDATE execution.semantic_pnf_external_request
       SET request_state=5,lease_owner=NULL,lease_expires_at=NULL,
           last_error_ref=NULL,updated_at=CURRENT_TIMESTAMP
     WHERE request_id=selected_request_id;
    PERFORM execution.wake_numeric_pnf_external_request_members(selected_request_id);
    RETURN evidence_id_value;
END;
$$;

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_external_provider_batch_receipt (
    batch_receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id SMALLINT NOT NULL
        REFERENCES execution.semantic_pnf_world_provider(provider_id) ON DELETE RESTRICT,
    worker_ref TEXT NOT NULL,
    leased_request_count INTEGER NOT NULL CHECK (leased_request_count>=0),
    completed_request_count INTEGER NOT NULL CHECK (completed_request_count>=0),
    failed_request_count INTEGER NOT NULL CHECK (failed_request_count>=0),
    provider_call_count INTEGER NOT NULL CHECK (provider_call_count>=0),
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (completed_request_count+failed_request_count=leased_request_count),
    CHECK (leased_request_count=0 OR provider_call_count>0),
    CHECK (provider_call_count<=leased_request_count)
);
CREATE INDEX IF NOT EXISTS semantic_pnf_external_provider_batch_provider_idx
    ON execution.semantic_pnf_external_provider_batch_receipt
       (provider_id,batch_receipt_id);

CREATE OR REPLACE FUNCTION execution.record_numeric_pnf_external_provider_batch_receipt(
    selected_provider_id SMALLINT,
    selected_worker_ref TEXT,
    selected_leased_request_count INTEGER,
    selected_completed_request_count INTEGER,
    selected_failed_request_count INTEGER,
    selected_provider_call_count INTEGER
) RETURNS BIGINT LANGUAGE sql AS $$
INSERT INTO execution.semantic_pnf_external_provider_batch_receipt
    (provider_id,worker_ref,leased_request_count,completed_request_count,
     failed_request_count,provider_call_count)
VALUES (selected_provider_id,selected_worker_ref,selected_leased_request_count,
        selected_completed_request_count,selected_failed_request_count,
        selected_provider_call_count)
RETURNING batch_receipt_id;
$$;

DROP VIEW IF EXISTS execution.semantic_pnf_external_call_economy_v1;
CREATE OR REPLACE VIEW execution.semantic_pnf_external_call_economy_v1 AS
WITH member AS (
    SELECT request_id,count(*)::BIGINT AS member_count
      FROM execution.semantic_pnf_external_request_member
     GROUP BY request_id
), request_summary AS (
    SELECT request.provider_id,
           count(*)::BIGINT AS unique_external_requests,
           count(*) FILTER (WHERE request.request_state=2)::BIGINT AS cache_satisfied_requests,
           count(*) FILTER (WHERE request.request_state=3)::BIGINT AS provider_ready_requests,
           count(*) FILTER (WHERE request.request_state=4)::BIGINT AS leased_requests,
           count(*) FILTER (WHERE request.request_state=5)::BIGINT AS acquired_requests,
           COALESCE(sum(member.member_count),0)::BIGINT AS semantic_request_members
      FROM execution.semantic_pnf_external_request AS request
      LEFT JOIN member USING(request_id)
     GROUP BY request.provider_id
), calls AS (
    SELECT receipt.provider_id,
           COALESCE(sum(receipt.provider_call_count),0)::BIGINT AS fresh_provider_calls,
           COALESCE(sum(receipt.leased_request_count),0)::BIGINT AS leased_request_attempts
      FROM execution.semantic_pnf_external_provider_batch_receipt AS receipt
     GROUP BY receipt.provider_id
)
SELECT summary.provider_id,
       summary.unique_external_requests,
       summary.cache_satisfied_requests,
       summary.provider_ready_requests,
       summary.leased_requests,
       summary.acquired_requests,
       summary.semantic_request_members,
       COALESCE(calls.fresh_provider_calls,0) AS fresh_provider_calls,
       CASE WHEN summary.unique_external_requests=0 THEN NULL
            ELSE summary.semantic_request_members::NUMERIC
                 / summary.unique_external_requests::NUMERIC
       END AS semantic_members_per_unique_request,
       CASE WHEN COALESCE(calls.fresh_provider_calls,0)=0 THEN NULL
            ELSE COALESCE(calls.leased_request_attempts,0)::NUMERIC
                 / calls.fresh_provider_calls::NUMERIC
       END AS requests_per_provider_call
  FROM request_summary AS summary
  LEFT JOIN calls USING(provider_id);

COMMIT;
