BEGIN;

-- 112: compile explicit consumer-observed world axes into the H9 residual.
--
-- H9-ready is only permission to consider external evidence. It is not itself
-- an external need. A consumer/query/policy must declare the world coordinate it
-- can actually observe and a numeric structural selector over demands. Only the
-- intersection of that contract with the unresolved H9 fibre becomes provider
-- work.
--
-- Contract configuration is cold control-plane state. Runtime matching remains
-- integer/set based over the existing demand coordinates.

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_consumer_world_axis_contract (
    contract_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_ref TEXT NOT NULL,
    query_ref TEXT NOT NULL,
    policy_ref TEXT NOT NULL DEFAULT '',
    contract_ref TEXT NOT NULL,
    contract_revision BIGINT NOT NULL DEFAULT 1 CHECK (contract_revision > 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,

    need_kind SMALLINT NOT NULL CHECK (need_kind IN (1,2,3)),
    provider_id SMALLINT NOT NULL DEFAULT 1
        REFERENCES execution.semantic_pnf_world_provider(provider_id) ON DELETE RESTRICT,
    axis_kind SMALLINT,
    provider_property_numeric_id BIGINT,
    need_revision BIGINT NOT NULL DEFAULT 1 CHECK (need_revision > 0),
    priority SMALLINT NOT NULL DEFAULT 100 CHECK (priority > 0),
    minimum_source_epoch BIGINT
        CHECK (minimum_source_epoch IS NULL OR minimum_source_epoch > 0),

    -- Sparse numeric selectors. NULL means this dimension is not observed by
    -- this contract, but at least one selector is mandatory so a contract can
    -- never accidentally mean "all H9 demands".
    expected_target_kind SMALLINT
        REFERENCES execution.semantic_pnf_target_kind(kind_id) ON DELETE RESTRICT,
    expected_factor_type_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    expected_object_kind_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    lexical_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    role_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    residual_type_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(consumer_ref,query_ref,policy_ref,contract_ref,contract_revision),
    CHECK (
        expected_target_kind IS NOT NULL
        OR expected_factor_type_symbol_id IS NOT NULL
        OR expected_object_kind_symbol_id IS NOT NULL
        OR lexical_symbol_id IS NOT NULL
        OR role_symbol_id IS NOT NULL
        OR residual_type_symbol_id IS NOT NULL
    ),
    CHECK (
        (need_kind=2 AND axis_kind IS NOT NULL
                     AND provider_property_numeric_id IS NOT NULL
                     AND provider_property_numeric_id > 0)
        OR
        (need_kind IN (1,3) AND axis_kind IS NULL
                            AND provider_property_numeric_id IS NULL)
    )
);
CREATE INDEX IF NOT EXISTS semantic_pnf_consumer_world_axis_contract_current_idx
    ON execution.semantic_pnf_consumer_world_axis_contract
       (consumer_ref,query_ref,policy_ref,contract_ref,contract_revision DESC);

-- Latest revision is the current contract. Earlier rows remain durable control
-- history, but cannot continue generating work after a superseding revision.
CREATE OR REPLACE VIEW execution.semantic_pnf_consumer_world_axis_contract_current_v1 AS
SELECT DISTINCT ON (
           contract.consumer_ref,contract.query_ref,contract.policy_ref,
           contract.contract_ref
       )
       contract.*
  FROM execution.semantic_pnf_consumer_world_axis_contract AS contract
 ORDER BY contract.consumer_ref,contract.query_ref,contract.policy_ref,
          contract.contract_ref,contract.contract_revision DESC,contract.contract_id DESC;

-- External needs may have multiple explicit origins. This prevents a contract
-- refresh from disabling an independently registered need, and lets several
-- contracts share one semantic need while preserving exact freshness/priority.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_consumer_external_need_origin (
    origin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    need_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_consumer_external_need(need_id) ON DELETE CASCADE,
    origin_kind SMALLINT NOT NULL CHECK (origin_kind IN (1,2)),
    -- 1 explicit/manual registration; 2 consumer world-axis contract.
    contract_id BIGINT
        REFERENCES execution.semantic_pnf_consumer_world_axis_contract(contract_id)
        ON DELETE CASCADE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    priority SMALLINT NOT NULL DEFAULT 100 CHECK (priority > 0),
    minimum_source_epoch BIGINT
        CHECK (minimum_source_epoch IS NULL OR minimum_source_epoch > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (origin_kind=1 AND contract_id IS NULL)
        OR (origin_kind=2 AND contract_id IS NOT NULL)
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS semantic_pnf_external_need_explicit_origin_idx
    ON execution.semantic_pnf_consumer_external_need_origin(need_id)
    WHERE origin_kind=1;
CREATE UNIQUE INDEX IF NOT EXISTS semantic_pnf_external_need_contract_origin_idx
    ON execution.semantic_pnf_consumer_external_need_origin(need_id,contract_id)
    WHERE origin_kind=2;
CREATE INDEX IF NOT EXISTS semantic_pnf_external_need_origin_contract_idx
    ON execution.semantic_pnf_consumer_external_need_origin
       (contract_id,active,need_id)
    WHERE origin_kind=2;

-- Every pre-112 need was explicitly registered. Preserve it as an explicit
-- origin so introducing contracts cannot withdraw historical/manual intent.
INSERT INTO execution.semantic_pnf_consumer_external_need_origin
    (need_id,origin_kind,contract_id,active,priority,minimum_source_epoch)
SELECT need.need_id,1,NULL,need.active,need.priority,need.minimum_source_epoch
  FROM execution.semantic_pnf_consumer_external_need AS need
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION execution.recompute_numeric_pnf_external_need_from_origins(
    selected_need_id BIGINT
) RETURNS BOOLEAN LANGUAGE plpgsql AS $$
DECLARE any_active BOOLEAN := FALSE;
        min_priority SMALLINT;
        max_floor BIGINT;
BEGIN
    SELECT COALESCE(bool_or(origin.active),FALSE),
           min(origin.priority) FILTER (WHERE origin.active),
           max(origin.minimum_source_epoch) FILTER (WHERE origin.active)
      INTO any_active,min_priority,max_floor
      FROM execution.semantic_pnf_consumer_external_need_origin AS origin
     WHERE origin.need_id=selected_need_id;

    UPDATE execution.semantic_pnf_consumer_external_need AS need
       SET active=any_active,
           priority=COALESCE(min_priority,need.priority),
           minimum_source_epoch=max_floor
     WHERE need.need_id=selected_need_id;
    RETURN FOUND;
END;
$$;

-- Preserve the existing explicit registration API while recording its origin.
-- Contract compilation below does not call this function, so it cannot silently
-- turn contract-derived needs into permanent manual needs.
CREATE OR REPLACE FUNCTION execution.record_numeric_pnf_consumer_external_need(
    selected_demand_id BIGINT,
    selected_consumer_ref TEXT,
    selected_query_ref TEXT,
    selected_policy_ref TEXT,
    selected_need_kind SMALLINT,
    selected_provider_id SMALLINT,
    selected_axis_kind SMALLINT,
    selected_provider_property_numeric_id BIGINT,
    selected_priority SMALLINT,
    selected_need_revision BIGINT,
    selected_active BOOLEAN
) RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE resolved_need_id BIGINT;
BEGIN
    IF selected_need_kind NOT IN (1,2,3) THEN
        RAISE EXCEPTION 'external need kind must be discovery, property, or identity';
    END IF;
    IF selected_priority<=0 THEN
        RAISE EXCEPTION 'external need priority must be positive';
    END IF;
    IF selected_need_kind=2 AND (
        selected_axis_kind IS NULL
        OR selected_provider_property_numeric_id IS NULL
        OR selected_provider_property_numeric_id<=0
    ) THEN
        RAISE EXCEPTION 'property need requires positive property id and axis';
    END IF;
    IF selected_need_kind<>2 AND (
        selected_axis_kind IS NOT NULL OR selected_provider_property_numeric_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'discovery/identity need cannot carry property-axis coordinates';
    END IF;

    INSERT INTO execution.semantic_pnf_consumer_external_need
        (demand_id,consumer_ref,query_ref,policy_ref,need_kind,provider_id,
         axis_kind,provider_property_numeric_id,priority,need_revision,active)
    VALUES (selected_demand_id,selected_consumer_ref,selected_query_ref,
            selected_policy_ref,selected_need_kind,selected_provider_id,
            selected_axis_kind,selected_provider_property_numeric_id,
            selected_priority,selected_need_revision,selected_active)
    ON CONFLICT DO NOTHING;

    SELECT need.need_id INTO STRICT resolved_need_id
      FROM execution.semantic_pnf_consumer_external_need AS need
     WHERE need.demand_id=selected_demand_id
       AND need.consumer_ref=selected_consumer_ref
       AND need.query_ref=selected_query_ref
       AND need.policy_ref=selected_policy_ref
       AND need.need_kind=selected_need_kind
       AND need.provider_id=selected_provider_id
       AND COALESCE(need.axis_kind,0)=COALESCE(selected_axis_kind,0)
       AND COALESCE(need.provider_property_numeric_id,0)=
           COALESCE(selected_provider_property_numeric_id,0)
       AND need.need_revision=selected_need_revision;

    INSERT INTO execution.semantic_pnf_consumer_external_need_origin
        (need_id,origin_kind,contract_id,active,priority,minimum_source_epoch)
    VALUES (resolved_need_id,1,NULL,selected_active,selected_priority,NULL)
    ON CONFLICT(need_id) WHERE origin_kind=1
    DO UPDATE SET active=EXCLUDED.active,
                  priority=EXCLUDED.priority,
                  updated_at=CURRENT_TIMESTAMP;

    PERFORM execution.recompute_numeric_pnf_external_need_from_origins(resolved_need_id);
    RETURN resolved_need_id;
END;
$$;

-- Freshness set through the explicit API belongs to the explicit origin. The
-- need itself remains the exact max/min projection over all active origins.
CREATE OR REPLACE FUNCTION execution.set_numeric_pnf_external_need_minimum_source_epoch(
    selected_need_id BIGINT,
    selected_minimum_source_epoch BIGINT
) RETURNS BOOLEAN LANGUAGE plpgsql AS $$
BEGIN
    IF selected_minimum_source_epoch IS NOT NULL AND selected_minimum_source_epoch<=0 THEN
        RAISE EXCEPTION 'minimum source epoch must be positive';
    END IF;

    UPDATE execution.semantic_pnf_consumer_external_need_origin
       SET minimum_source_epoch=selected_minimum_source_epoch,
           updated_at=CURRENT_TIMESTAMP
     WHERE need_id=selected_need_id AND origin_kind=1;
    IF NOT FOUND THEN RETURN FALSE; END IF;

    RETURN execution.recompute_numeric_pnf_external_need_from_origins(selected_need_id);
END;
$$;

CREATE OR REPLACE FUNCTION execution.record_numeric_pnf_consumer_world_axis_contract(
    selected_consumer_ref TEXT,
    selected_query_ref TEXT,
    selected_policy_ref TEXT,
    selected_contract_ref TEXT,
    selected_contract_revision BIGINT,
    selected_active BOOLEAN,
    selected_need_kind SMALLINT,
    selected_provider_id SMALLINT,
    selected_axis_kind SMALLINT,
    selected_provider_property_numeric_id BIGINT,
    selected_need_revision BIGINT,
    selected_priority SMALLINT,
    selected_minimum_source_epoch BIGINT,
    selected_expected_target_kind SMALLINT,
    selected_expected_factor_type_symbol_id BIGINT,
    selected_expected_object_kind_symbol_id BIGINT,
    selected_lexical_symbol_id BIGINT,
    selected_role_symbol_id BIGINT,
    selected_residual_type_symbol_id BIGINT
) RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE resolved_contract_id BIGINT;
BEGIN
    IF selected_contract_ref='' THEN
        RAISE EXCEPTION 'contract_ref must be non-empty';
    END IF;
    IF selected_contract_revision<=0 OR selected_need_revision<=0 OR selected_priority<=0 THEN
        RAISE EXCEPTION 'contract/need revisions and priority must be positive';
    END IF;
    IF selected_minimum_source_epoch IS NOT NULL AND selected_minimum_source_epoch<=0 THEN
        RAISE EXCEPTION 'minimum source epoch must be positive';
    END IF;
    IF selected_expected_target_kind IS NULL
       AND selected_expected_factor_type_symbol_id IS NULL
       AND selected_expected_object_kind_symbol_id IS NULL
       AND selected_lexical_symbol_id IS NULL
       AND selected_role_symbol_id IS NULL
       AND selected_residual_type_symbol_id IS NULL THEN
        RAISE EXCEPTION 'consumer world-axis contract requires at least one numeric demand selector';
    END IF;
    IF selected_need_kind=2 AND (
        selected_axis_kind IS NULL OR selected_provider_property_numeric_id IS NULL
        OR selected_provider_property_numeric_id<=0
    ) THEN
        RAISE EXCEPTION 'property contract requires positive property id and axis';
    END IF;
    IF selected_need_kind IN (1,3) AND (
        selected_axis_kind IS NOT NULL OR selected_provider_property_numeric_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'discovery/identity contract cannot carry property-axis coordinates';
    END IF;

    INSERT INTO execution.semantic_pnf_consumer_world_axis_contract
        (consumer_ref,query_ref,policy_ref,contract_ref,contract_revision,active,
         need_kind,provider_id,axis_kind,provider_property_numeric_id,need_revision,
         priority,minimum_source_epoch,expected_target_kind,
         expected_factor_type_symbol_id,expected_object_kind_symbol_id,
         lexical_symbol_id,role_symbol_id,residual_type_symbol_id)
    VALUES (selected_consumer_ref,selected_query_ref,selected_policy_ref,
            selected_contract_ref,selected_contract_revision,selected_active,
            selected_need_kind,selected_provider_id,selected_axis_kind,
            selected_provider_property_numeric_id,selected_need_revision,
            selected_priority,selected_minimum_source_epoch,selected_expected_target_kind,
            selected_expected_factor_type_symbol_id,selected_expected_object_kind_symbol_id,
            selected_lexical_symbol_id,selected_role_symbol_id,
            selected_residual_type_symbol_id)
    ON CONFLICT(consumer_ref,query_ref,policy_ref,contract_ref,contract_revision)
    DO UPDATE SET active=EXCLUDED.active,
                  need_kind=EXCLUDED.need_kind,
                  provider_id=EXCLUDED.provider_id,
                  axis_kind=EXCLUDED.axis_kind,
                  provider_property_numeric_id=EXCLUDED.provider_property_numeric_id,
                  need_revision=EXCLUDED.need_revision,
                  priority=EXCLUDED.priority,
                  minimum_source_epoch=EXCLUDED.minimum_source_epoch,
                  expected_target_kind=EXCLUDED.expected_target_kind,
                  expected_factor_type_symbol_id=EXCLUDED.expected_factor_type_symbol_id,
                  expected_object_kind_symbol_id=EXCLUDED.expected_object_kind_symbol_id,
                  lexical_symbol_id=EXCLUDED.lexical_symbol_id,
                  role_symbol_id=EXCLUDED.role_symbol_id,
                  residual_type_symbol_id=EXCLUDED.residual_type_symbol_id
    RETURNING contract_id INTO resolved_contract_id;
    RETURN resolved_contract_id;
END;
$$;

-- Exact current compilation. The contract-origin projection for this document
-- is rebuilt transactionally: old contract origins are deactivated, current
-- matches are reactivated, then semantic need.active/priority/freshness is
-- recomputed as the union of all active origins.
CREATE OR REPLACE FUNCTION execution.compile_numeric_pnf_h9_external_needs_for_consumer(
    selected_run_id BIGINT,
    selected_document_id BIGINT,
    selected_consumer_ref TEXT,
    selected_query_ref TEXT,
    selected_policy_ref TEXT DEFAULT ''
) RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE affected BIGINT := 0;
BEGIN
    UPDATE execution.semantic_pnf_consumer_external_need_origin AS origin
       SET active=FALSE,updated_at=CURRENT_TIMESTAMP
      FROM execution.semantic_pnf_consumer_external_need AS need,
           execution.semantic_pnf_demand AS demand,
           execution.semantic_pnf_region AS region
     WHERE origin.need_id=need.need_id
       AND origin.origin_kind=2
       AND demand.demand_id=need.demand_id
       AND region.region_id=demand.source_region_id
       AND need.consumer_ref=selected_consumer_ref
       AND need.query_ref=selected_query_ref
       AND need.policy_ref=selected_policy_ref
       AND region.run_id=selected_run_id
       AND region.document_id=selected_document_id;

    WITH matched AS MATERIALIZED (
        SELECT DISTINCT current_contract.contract_id,demand.demand_id,
               current_contract.need_kind,current_contract.provider_id,
               current_contract.axis_kind,current_contract.provider_property_numeric_id,
               current_contract.need_revision,current_contract.priority,
               current_contract.minimum_source_epoch
          FROM execution.semantic_pnf_consumer_horizon_work_queue AS work
          JOIN execution.semantic_pnf_demand AS demand ON demand.demand_id=work.demand_id
          JOIN execution.semantic_pnf_region AS region ON region.region_id=demand.source_region_id
          JOIN execution.semantic_pnf_consumer_world_axis_contract_current_v1 AS current_contract
            ON current_contract.consumer_ref=work.consumer_ref
           AND current_contract.query_ref=work.query_ref
           AND current_contract.policy_ref=work.policy_ref
         WHERE work.consumer_ref=selected_consumer_ref
           AND work.query_ref=selected_query_ref
           AND work.policy_ref=selected_policy_ref
           AND work.horizon=9 AND work.work_state=1
           AND current_contract.active
           AND region.run_id=selected_run_id
           AND region.document_id=selected_document_id
           AND NOT execution.numeric_pnf_consumer_stop_at_horizon(
               demand.demand_id,selected_consumer_ref,selected_query_ref,
               selected_policy_ref,6
           )
           AND (current_contract.expected_target_kind IS NULL
                OR current_contract.expected_target_kind=demand.expected_target_kind)
           AND (current_contract.expected_factor_type_symbol_id IS NULL
                OR current_contract.expected_factor_type_symbol_id=demand.expected_factor_type_symbol_id)
           AND (current_contract.expected_object_kind_symbol_id IS NULL
                OR current_contract.expected_object_kind_symbol_id=demand.expected_object_kind_symbol_id)
           AND (current_contract.lexical_symbol_id IS NULL
                OR current_contract.lexical_symbol_id=demand.lexical_symbol_id)
           AND (current_contract.role_symbol_id IS NULL
                OR current_contract.role_symbol_id=demand.role_symbol_id)
           AND (current_contract.residual_type_symbol_id IS NULL
                OR current_contract.residual_type_symbol_id=demand.residual_type_symbol_id)
           AND (
               (current_contract.need_kind IN (1,2) AND demand.lexical_symbol_id IS NOT NULL)
               OR (current_contract.need_kind=3 AND demand.source_object_id IS NOT NULL)
           )
    )
    INSERT INTO execution.semantic_pnf_consumer_external_need
        (demand_id,consumer_ref,query_ref,policy_ref,need_kind,provider_id,
         axis_kind,provider_property_numeric_id,priority,need_revision,active,
         minimum_source_epoch)
    SELECT DISTINCT matched.demand_id,selected_consumer_ref,selected_query_ref,
           selected_policy_ref,matched.need_kind,matched.provider_id,
           matched.axis_kind,matched.provider_property_numeric_id,
           matched.priority,matched.need_revision,TRUE,matched.minimum_source_epoch
      FROM matched
    ON CONFLICT DO NOTHING;

    WITH matched AS MATERIALIZED (
        SELECT DISTINCT current_contract.contract_id,demand.demand_id,
               current_contract.need_kind,current_contract.provider_id,
               current_contract.axis_kind,current_contract.provider_property_numeric_id,
               current_contract.need_revision,current_contract.priority,
               current_contract.minimum_source_epoch
          FROM execution.semantic_pnf_consumer_horizon_work_queue AS work
          JOIN execution.semantic_pnf_demand AS demand ON demand.demand_id=work.demand_id
          JOIN execution.semantic_pnf_region AS region ON region.region_id=demand.source_region_id
          JOIN execution.semantic_pnf_consumer_world_axis_contract_current_v1 AS current_contract
            ON current_contract.consumer_ref=work.consumer_ref
           AND current_contract.query_ref=work.query_ref
           AND current_contract.policy_ref=work.policy_ref
         WHERE work.consumer_ref=selected_consumer_ref
           AND work.query_ref=selected_query_ref
           AND work.policy_ref=selected_policy_ref
           AND work.horizon=9 AND work.work_state=1
           AND current_contract.active
           AND region.run_id=selected_run_id
           AND region.document_id=selected_document_id
           AND NOT execution.numeric_pnf_consumer_stop_at_horizon(
               demand.demand_id,selected_consumer_ref,selected_query_ref,
               selected_policy_ref,6
           )
           AND (current_contract.expected_target_kind IS NULL
                OR current_contract.expected_target_kind=demand.expected_target_kind)
           AND (current_contract.expected_factor_type_symbol_id IS NULL
                OR current_contract.expected_factor_type_symbol_id=demand.expected_factor_type_symbol_id)
           AND (current_contract.expected_object_kind_symbol_id IS NULL
                OR current_contract.expected_object_kind_symbol_id=demand.expected_object_kind_symbol_id)
           AND (current_contract.lexical_symbol_id IS NULL
                OR current_contract.lexical_symbol_id=demand.lexical_symbol_id)
           AND (current_contract.role_symbol_id IS NULL
                OR current_contract.role_symbol_id=demand.role_symbol_id)
           AND (current_contract.residual_type_symbol_id IS NULL
                OR current_contract.residual_type_symbol_id=demand.residual_type_symbol_id)
           AND (
               (current_contract.need_kind IN (1,2) AND demand.lexical_symbol_id IS NOT NULL)
               OR (current_contract.need_kind=3 AND demand.source_object_id IS NOT NULL)
           )
    )
    INSERT INTO execution.semantic_pnf_consumer_external_need_origin
        (need_id,origin_kind,contract_id,active,priority,minimum_source_epoch)
    SELECT need.need_id,2,matched.contract_id,TRUE,matched.priority,
           matched.minimum_source_epoch
      FROM matched
      JOIN execution.semantic_pnf_consumer_external_need AS need
        ON need.demand_id=matched.demand_id
       AND need.consumer_ref=selected_consumer_ref
       AND need.query_ref=selected_query_ref
       AND need.policy_ref=selected_policy_ref
       AND need.need_kind=matched.need_kind
       AND need.provider_id=matched.provider_id
       AND COALESCE(need.axis_kind,0)=COALESCE(matched.axis_kind,0)
       AND COALESCE(need.provider_property_numeric_id,0)=
           COALESCE(matched.provider_property_numeric_id,0)
       AND need.need_revision=matched.need_revision
    ON CONFLICT(need_id,contract_id) WHERE origin_kind=2
    DO UPDATE SET active=TRUE,
                  priority=EXCLUDED.priority,
                  minimum_source_epoch=EXCLUDED.minimum_source_epoch,
                  updated_at=CURRENT_TIMESTAMP;

    -- Recompute only needs in this document/consumer fibre. Manual origins and
    -- other contracts remain independent contributors.
    WITH scoped_need AS MATERIALIZED (
        SELECT need.need_id,
               COALESCE(bool_or(origin.active),FALSE) AS any_active,
               min(origin.priority) FILTER (WHERE origin.active) AS min_priority,
               max(origin.minimum_source_epoch) FILTER (WHERE origin.active) AS max_floor
          FROM execution.semantic_pnf_consumer_external_need AS need
          JOIN execution.semantic_pnf_demand AS demand ON demand.demand_id=need.demand_id
          JOIN execution.semantic_pnf_region AS region ON region.region_id=demand.source_region_id
          LEFT JOIN execution.semantic_pnf_consumer_external_need_origin AS origin
            ON origin.need_id=need.need_id
         WHERE need.consumer_ref=selected_consumer_ref
           AND need.query_ref=selected_query_ref
           AND need.policy_ref=selected_policy_ref
           AND region.run_id=selected_run_id
           AND region.document_id=selected_document_id
         GROUP BY need.need_id
    )
    UPDATE execution.semantic_pnf_consumer_external_need AS need
       SET active=scoped_need.any_active,
           priority=COALESCE(scoped_need.min_priority,need.priority),
           minimum_source_epoch=scoped_need.max_floor
      FROM scoped_need
     WHERE need.need_id=scoped_need.need_id;

    SELECT count(DISTINCT need.need_id)::BIGINT INTO affected
      FROM execution.semantic_pnf_consumer_external_need AS need
      JOIN execution.semantic_pnf_consumer_external_need_origin AS origin
        ON origin.need_id=need.need_id AND origin.origin_kind=2 AND origin.active
      JOIN execution.semantic_pnf_demand AS demand ON demand.demand_id=need.demand_id
      JOIN execution.semantic_pnf_region AS region ON region.region_id=demand.source_region_id
     WHERE need.active
       AND need.consumer_ref=selected_consumer_ref
       AND need.query_ref=selected_query_ref
       AND need.policy_ref=selected_policy_ref
       AND region.run_id=selected_run_id
       AND region.document_id=selected_document_id;
    RETURN affected;
END;
$$;

-- Funnel visibility: H9 residual, explicit needs, and contract-derived needs are
-- separate quantities. This is intentionally observational and never creates a
-- contract or need by itself.
CREATE OR REPLACE VIEW execution.semantic_pnf_consumer_external_need_funnel_v1 AS
SELECT work.consumer_ref,work.query_ref,work.policy_ref,
       count(DISTINCT work.demand_id)::BIGINT AS h9_residual_demands,
       count(DISTINCT need.demand_id) FILTER (WHERE need.active)::BIGINT
           AS explicit_external_need_demands,
       count(DISTINCT need.demand_id) FILTER (
           WHERE need.active AND contract_origin.need_id IS NOT NULL
       )::BIGINT AS contract_external_need_demands,
       count(DISTINCT need.need_id) FILTER (WHERE need.active)::BIGINT
           AS active_external_need_rows
  FROM execution.semantic_pnf_consumer_horizon_work_queue AS work
  LEFT JOIN execution.semantic_pnf_consumer_external_need AS need
    ON need.demand_id=work.demand_id
   AND need.consumer_ref=work.consumer_ref
   AND need.query_ref=work.query_ref
   AND need.policy_ref=work.policy_ref
  LEFT JOIN (
      SELECT DISTINCT origin.need_id
        FROM execution.semantic_pnf_consumer_external_need_origin AS origin
       WHERE origin.origin_kind=2 AND origin.active
  ) AS contract_origin ON contract_origin.need_id=need.need_id
 WHERE work.horizon=9 AND work.work_state=1
 GROUP BY work.consumer_ref,work.query_ref,work.policy_ref;

COMMIT;
