BEGIN;

-- 122: canonical demand -> originating structural occurrence support.
--
-- semantic_pnf_demand.source_object_id (090a) is a useful optional fast-path
-- projection, but it is reconstructed from source-region + lexical uniqueness
-- and therefore cannot be authority for world-oriented occurrence semantics.
-- This carrier preserves the stronger structural relation explicitly and keeps
-- the old projection only as a weak audit witness.

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_demand_occurrence_support (
    support_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_demand(demand_id) ON DELETE CASCADE,
    support_kind SMALLINT NOT NULL CHECK (support_kind IN (1,2,9)),
    -- 1 exact interface/object export: interface + lexical key + role
    -- 2 exact typed factor slot: interface + factor type + role
    -- 9 legacy 090a source_object_id (audit/fast path only; not H9 authority)
    source_interface_id BIGINT
        REFERENCES execution.semantic_pnf_interface(interface_id) ON DELETE CASCADE,
    object_id BIGINT
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE CASCADE,
    factor_id BIGINT
        REFERENCES execution.semantic_pnf_factor(factor_id) ON DELETE CASCADE,
    slot_ordinal SMALLINT,
    role_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    lexical_symbol_id BIGINT
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    support_revision BIGINT NOT NULL DEFAULT 1 CHECK (support_revision > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (support_kind=1 AND source_interface_id IS NOT NULL
                        AND object_id IS NOT NULL
                        AND factor_id IS NULL
                        AND slot_ordinal IS NULL)
        OR
        (support_kind=2 AND source_interface_id IS NOT NULL
                        AND object_id IS NOT NULL
                        AND factor_id IS NOT NULL
                        AND slot_ordinal IS NOT NULL)
        OR
        (support_kind=9 AND object_id IS NOT NULL
                        AND factor_id IS NULL
                        AND slot_ordinal IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS semantic_pnf_demand_occurrence_support_identity_idx
    ON execution.semantic_pnf_demand_occurrence_support (
        demand_id,support_kind,
        COALESCE(source_interface_id,0),object_id,
        COALESCE(factor_id,0),COALESCE(slot_ordinal,-1),
        COALESCE(role_symbol_id,0),COALESCE(lexical_symbol_id,0)
    );
CREATE INDEX IF NOT EXISTS semantic_pnf_demand_occurrence_object_idx
    ON execution.semantic_pnf_demand_occurrence_support
       (object_id,support_kind,demand_id);
CREATE INDEX IF NOT EXISTS semantic_pnf_demand_occurrence_demand_idx
    ON execution.semantic_pnf_demand_occurrence_support
       (demand_id,support_kind,object_id);

-- Rebuild one demand from exact numeric structural coordinates already carried
-- by the PNF. No symbol_text, regex, capitalization, fuzzy, or co-scope rule is
-- permitted here.
CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_demand_occurrence_support(
    selected_demand_id BIGINT
) RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE affected BIGINT := 0; n BIGINT := 0;
BEGIN
    DELETE FROM execution.semantic_pnf_demand_occurrence_support
     WHERE demand_id=selected_demand_id;

    -- Exact object occurrence exported on the same interface under the same
    -- lexical key and grammatical role. Preserve every exact match; do not force
    -- an arbitrary single object when the structure itself is plural/ambiguous.
    INSERT INTO execution.semantic_pnf_demand_occurrence_support
        (demand_id,support_kind,source_interface_id,object_id,
         role_symbol_id,lexical_symbol_id)
    SELECT DISTINCT demand.demand_id,1::SMALLINT,demand.source_interface_id,
           export.target_id,demand.role_symbol_id,demand.lexical_symbol_id
      FROM execution.semantic_pnf_demand AS demand
      JOIN execution.semantic_pnf_interface_export AS export
        ON export.interface_id=demand.source_interface_id
       AND export.target_kind=1
       AND export.export_kind=1
       AND demand.lexical_symbol_id IS NOT NULL
       AND export.key_symbol_id=demand.lexical_symbol_id
       AND demand.role_symbol_id IS NOT NULL
       AND export.role_symbol_id=demand.role_symbol_id
      JOIN execution.semantic_pnf_object AS object
        ON object.object_id=export.target_id AND object.active
     WHERE demand.demand_id=selected_demand_id
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS n=ROW_COUNT; affected:=affected+n;

    -- A demand can also originate from an exact typed factor slot. The factor is
    -- first fixed by the same interface and expected factor type; the role fixes
    -- the slot, and that slot supplies the originating object occurrence.
    INSERT INTO execution.semantic_pnf_demand_occurrence_support
        (demand_id,support_kind,source_interface_id,object_id,factor_id,
         slot_ordinal,role_symbol_id,lexical_symbol_id)
    SELECT DISTINCT demand.demand_id,2::SMALLINT,demand.source_interface_id,
           edge.object_id,factor.factor_id,edge.slot_ordinal,
           edge.role_symbol_id,demand.lexical_symbol_id
      FROM execution.semantic_pnf_demand AS demand
      JOIN execution.semantic_pnf_interface_export AS export
        ON export.interface_id=demand.source_interface_id
       AND export.target_kind=2
      JOIN execution.semantic_pnf_factor AS factor
        ON factor.factor_id=export.target_id
       AND demand.expected_factor_type_symbol_id IS NOT NULL
       AND factor.factor_type_symbol_id=demand.expected_factor_type_symbol_id
      JOIN execution.semantic_pnf_hyperedge AS edge
        ON edge.factor_id=factor.factor_id
       AND demand.role_symbol_id IS NOT NULL
       AND edge.role_symbol_id=demand.role_symbol_id
      JOIN execution.semantic_pnf_object AS object
        ON object.object_id=edge.object_id AND object.active
     WHERE demand.demand_id=selected_demand_id
       AND (
           demand.lexical_symbol_id IS NULL
           OR object.head_symbol_id=demand.lexical_symbol_id
       )
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS n=ROW_COUNT; affected:=affected+n;

    -- Retain the historical unique-region lexical projection as an explicitly
    -- weak support witness for audit/performance comparison. H9 views below do
    -- not consume support_kind=9.
    INSERT INTO execution.semantic_pnf_demand_occurrence_support
        (demand_id,support_kind,source_interface_id,object_id,
         role_symbol_id,lexical_symbol_id)
    SELECT demand.demand_id,9::SMALLINT,demand.source_interface_id,
           demand.source_object_id,demand.role_symbol_id,demand.lexical_symbol_id
      FROM execution.semantic_pnf_demand AS demand
     WHERE demand.demand_id=selected_demand_id
       AND demand.source_object_id IS NOT NULL
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS n=ROW_COUNT; affected:=affected+n;

    RETURN affected;
END;
$$;

CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_demand_occurrence_support_scope(
    selected_run_id BIGINT,
    selected_document_id BIGINT
) RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE demand_row RECORD; affected BIGINT := 0;
BEGIN
    FOR demand_row IN
        SELECT demand.demand_id
          FROM execution.semantic_pnf_demand AS demand
          JOIN execution.semantic_pnf_region AS region
            ON region.region_id=demand.source_region_id
         WHERE region.run_id=selected_run_id
           AND region.document_id=selected_document_id
         ORDER BY demand.demand_id
    LOOP
        affected:=affected+
            execution.refresh_numeric_pnf_demand_occurrence_support(demand_row.demand_id);
    END LOOP;
    RETURN affected;
END;
$$;

-- Keep newly created/retargeted demands current. This is a small bounded lookup
-- over one interface and does not alter demand semantics or resolution state.
CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_demand_occurrence_support_on_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    PERFORM execution.refresh_numeric_pnf_demand_occurrence_support(NEW.demand_id);
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS semantic_pnf_demand_occurrence_support_refresh
    ON execution.semantic_pnf_demand;
CREATE TRIGGER semantic_pnf_demand_occurrence_support_refresh
AFTER INSERT OR UPDATE OF source_interface_id,expected_factor_type_symbol_id,
    lexical_symbol_id,role_symbol_id,source_object_id
ON execution.semantic_pnf_demand
FOR EACH ROW EXECUTE FUNCTION execution.refresh_numeric_pnf_demand_occurrence_support_on_change();

-- Interface exports can be created after their demand. Refresh only demands on
-- that interface whose structural coordinates could have changed support.
CREATE OR REPLACE FUNCTION execution.refresh_numeric_pnf_demand_occurrence_support_on_export()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE demand_row RECORD;
BEGIN
    FOR demand_row IN
        SELECT demand.demand_id
          FROM execution.semantic_pnf_demand AS demand
         WHERE demand.source_interface_id=NEW.interface_id
           AND (
               (NEW.target_kind=1 AND NEW.export_kind=1
                AND demand.lexical_symbol_id IS NOT NULL
                AND NEW.key_symbol_id=demand.lexical_symbol_id
                AND demand.role_symbol_id IS NOT NULL
                AND NEW.role_symbol_id=demand.role_symbol_id)
               OR
               NEW.target_kind=2
           )
    LOOP
        PERFORM execution.refresh_numeric_pnf_demand_occurrence_support(demand_row.demand_id);
    END LOOP;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS semantic_pnf_export_occurrence_support_refresh
    ON execution.semantic_pnf_interface_export;
CREATE TRIGGER semantic_pnf_export_occurrence_support_refresh
AFTER INSERT OR UPDATE OF key_symbol_id,role_symbol_id,target_kind,target_id
ON execution.semantic_pnf_interface_export
FOR EACH ROW EXECUTE FUNCTION execution.refresh_numeric_pnf_demand_occurrence_support_on_export();

-- Backfill the existing corpus from exact persisted structure.
SELECT execution.refresh_numeric_pnf_demand_occurrence_support(demand_id)
  FROM execution.semantic_pnf_demand;

-- Canonical strong support: only exact interface-object and typed factor-slot
-- witnesses. This is the carrier downstream consumers should use.
CREATE OR REPLACE VIEW execution.semantic_pnf_demand_strong_occurrence_support_v1 AS
SELECT support.*
  FROM execution.semantic_pnf_demand_occurrence_support AS support
 WHERE support.support_kind IN (1,2);

-- Audit how much provenance is exact versus available only through the old
-- lexical-region projection. Absence is an audit state, never negative evidence.
CREATE OR REPLACE VIEW execution.semantic_pnf_demand_occurrence_support_audit_v1 AS
SELECT demand.demand_id,
       count(*) FILTER (WHERE support.support_kind IN (1,2))::BIGINT
           AS strong_support_count,
       count(*) FILTER (WHERE support.support_kind=1)::BIGINT
           AS exact_interface_object_count,
       count(*) FILTER (WHERE support.support_kind=2)::BIGINT
           AS exact_factor_slot_count,
       count(*) FILTER (WHERE support.support_kind=9)::BIGINT
           AS legacy_source_object_count,
       EXISTS (
           SELECT 1
             FROM execution.semantic_pnf_demand_occurrence_support AS strong
             JOIN execution.semantic_pnf_object_mention_support AS object_mention
               ON object_mention.object_id=strong.object_id
             JOIN execution.semantic_pnf_mention AS mention
               ON mention.mention_id=object_mention.mention_id
              AND mention.mention_kind=1 AND mention.active
            WHERE strong.demand_id=demand.demand_id
              AND strong.support_kind IN (1,2)
       ) AS parser_entity_reachable
  FROM execution.semantic_pnf_demand AS demand
  LEFT JOIN execution.semantic_pnf_demand_occurrence_support AS support
    ON support.demand_id=demand.demand_id
 GROUP BY demand.demand_id;

COMMIT;
