BEGIN;

-- 135: preserve multiple entity-boundary candidates instead of treating one
-- spaCy doc.ents segmentation as the only possible mention carrier.
--
-- Raw primary parser spans remain immutable in semantic_parser_entity_span.
-- Secondary NER passes append independently-provenanced observations here.
-- A rebuildable provider-candidate projection then canonicalises identical
-- quality-valid spans without erasing which model(s) supported them.

CREATE TABLE IF NOT EXISTS execution.semantic_parser_secondary_entity_pass (
    pass_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pass_ref TEXT NOT NULL UNIQUE,
    model_name TEXT NOT NULL,
    model_version TEXT NOT NULL,
    consumer_ref TEXT NOT NULL,
    query_ref TEXT NOT NULL,
    policy_ref TEXT NOT NULL DEFAULT '',
    sentence_count BIGINT NOT NULL CHECK (sentence_count >= 0),
    entity_count BIGINT NOT NULL CHECK (entity_count >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS semantic_parser_secondary_entity_pass_current_idx
    ON execution.semantic_parser_secondary_entity_pass
       (model_name,consumer_ref,query_ref,policy_ref,active,pass_id);

CREATE TABLE IF NOT EXISTS execution.semantic_parser_secondary_entity_span (
    secondary_entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pass_id BIGINT NOT NULL
        REFERENCES execution.semantic_parser_secondary_entity_pass(pass_id)
        ON DELETE CASCADE,
    run_ref TEXT NOT NULL,
    document_ref TEXT NOT NULL,
    sentence_ref TEXT NOT NULL
        REFERENCES execution.semantic_parser_sentence(sentence_ref) ON DELETE CASCADE,
    start_char BIGINT NOT NULL CHECK (start_char >= 0),
    end_char BIGINT NOT NULL CHECK (end_char > start_char),
    entity_type_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    label_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(pass_id,run_ref,document_ref,sentence_ref,start_char,end_char,
           entity_type_symbol_id,label_symbol_id)
);

CREATE INDEX IF NOT EXISTS semantic_parser_secondary_entity_span_occurrence_idx
    ON execution.semantic_parser_secondary_entity_span
       (sentence_ref,start_char,end_char,entity_type_symbol_id);

-- Apply exactly the same provider-quality semantics used for primary doc.ents.
-- The secondary pass is additional parser evidence, not an exemption from the
-- boundary gate.
CREATE OR REPLACE VIEW execution.semantic_parser_secondary_entity_span_quality_v1 AS
WITH token_geometry AS MATERIALIZED (
    SELECT span.secondary_entity_id,span.pass_id,span.run_ref,span.document_ref,
           span.sentence_ref,span.start_char,span.end_char,
           span.entity_type_symbol_id,span.label_symbol_id,
           count(token.token_id)::BIGINT AS token_count,
           min(token.start_char) AS token_start,
           max(token.end_char) AS token_end,
           min(token.local_token_ordinal) AS first_ordinal,
           max(token.local_token_ordinal) AS last_ordinal,
           count(*) FILTER (
               WHERE EXISTS (
                   SELECT 1
                     FROM execution.semantic_parser_entity_quality_pos q
                    WHERE q.quality_role=1
                      AND q.pos_symbol_id=token.pos_symbol_id
               )
           )::BIGINT AS verbal_token_count,
           count(*) FILTER (
               WHERE EXISTS (
                   SELECT 1
                     FROM execution.semantic_parser_entity_quality_pos q
                    WHERE q.quality_role=2
                      AND q.pos_symbol_id=token.pos_symbol_id
               )
           )::BIGINT AS nominal_token_count
      FROM execution.semantic_parser_secondary_entity_span span
      JOIN execution.semantic_parser_secondary_entity_pass pass
        ON pass.pass_id=span.pass_id AND pass.active
      LEFT JOIN execution.semantic_parser_token token
        ON token.run_ref=span.run_ref
       AND token.document_ref=span.document_ref
       AND token.sentence_ref=span.sentence_ref
       AND token.representation_version=2
       AND token.start_char>=span.start_char
       AND token.end_char<=span.end_char
     GROUP BY span.secondary_entity_id,span.pass_id,span.run_ref,span.document_ref,
              span.sentence_ref,span.start_char,span.end_char,
              span.entity_type_symbol_id,span.label_symbol_id
), classified AS (
    SELECT geometry.*,
           CASE
             WHEN geometry.token_count=0 THEN 11
             WHEN geometry.token_start<>geometry.start_char
               OR geometry.token_end<>geometry.end_char THEN 12
             WHEN geometry.first_ordinal IS NULL OR geometry.last_ordinal IS NULL
               OR geometry.token_count<>(geometry.last_ordinal-geometry.first_ordinal+1)
               THEN 13
             WHEN geometry.verbal_token_count>0 THEN 14
             WHEN geometry.token_count>16
               OR geometry.end_char-geometry.start_char>256 THEN 15
             WHEN NOT EXISTS (
                 SELECT 1
                   FROM execution.semantic_parser_provider_entity_type allowed
                  WHERE allowed.entity_type_symbol_id=geometry.entity_type_symbol_id
                    AND allowed.provider_world_bearing
             ) THEN 16
             WHEN geometry.nominal_token_count=0 THEN 17
             WHEN EXISTS (
                 SELECT 1
                   FROM execution.semantic_parser_token terminal_token
                   JOIN execution.semantic_parser_entity_quality_terminal_pos terminal
                     ON terminal.pos_symbol_id=terminal_token.pos_symbol_id
                  WHERE terminal_token.representation_version=2
                    AND terminal_token.sentence_ref=geometry.sentence_ref
                    AND terminal_token.local_token_ordinal=geometry.last_ordinal
             ) THEN 18
             ELSE 1
           END::SMALLINT AS quality_state
      FROM token_geometry geometry
)
SELECT classified.*,(classified.quality_state=1) AS provider_admissible
  FROM classified;

-- Stable canonical provider candidate. This is a hot semantic coordinate over
-- one exact sentence/span/type/label; multiple parser producers may support it.
CREATE TABLE IF NOT EXISTS execution.semantic_parser_provider_entity_candidate (
    provider_entity_candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_ref TEXT NOT NULL,
    document_ref TEXT NOT NULL,
    sentence_ref TEXT NOT NULL
        REFERENCES execution.semantic_parser_sentence(sentence_ref) ON DELETE CASCADE,
    start_char BIGINT NOT NULL CHECK (start_char >= 0),
    end_char BIGINT NOT NULL CHECK (end_char > start_char),
    entity_type_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    label_symbol_id BIGINT NOT NULL
        REFERENCES execution.semantic_symbol(symbol_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(run_ref,document_ref,sentence_ref,start_char,end_char,
           entity_type_symbol_id,label_symbol_id)
);

CREATE TABLE IF NOT EXISTS execution.semantic_parser_provider_entity_candidate_support (
    provider_entity_candidate_id BIGINT NOT NULL
        REFERENCES execution.semantic_parser_provider_entity_candidate(provider_entity_candidate_id)
        ON DELETE CASCADE,
    support_kind SMALLINT NOT NULL CHECK (support_kind IN (1,2)),
    parser_entity_id BIGINT,
    secondary_entity_id BIGINT,
    producer_ref TEXT NOT NULL,
    producer_version TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (support_kind=1 AND parser_entity_id IS NOT NULL AND secondary_entity_id IS NULL)
        OR
        (support_kind=2 AND parser_entity_id IS NULL AND secondary_entity_id IS NOT NULL)
    ),
    UNIQUE(provider_entity_candidate_id,support_kind,producer_ref,producer_version,
           parser_entity_id,secondary_entity_id)
);

CREATE INDEX IF NOT EXISTS semantic_parser_provider_candidate_support_active_idx
    ON execution.semantic_parser_provider_entity_candidate_support
       (provider_entity_candidate_id,active,support_kind);

CREATE OR REPLACE FUNCTION execution.refresh_semantic_parser_provider_entity_candidates()
RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE affected BIGINT := 0; n BIGINT := 0;
BEGIN
    -- Candidate coordinates are stable; support is the rebuildable current layer.
    UPDATE execution.semantic_parser_provider_entity_candidate_support
       SET active=FALSE
     WHERE active;

    -- Primary quality-valid doc.ents.
    WITH inserted AS (
        INSERT INTO execution.semantic_parser_provider_entity_candidate
            (run_ref,document_ref,sentence_ref,start_char,end_char,
             entity_type_symbol_id,label_symbol_id)
        SELECT entity.run_ref,entity.document_ref,entity.sentence_ref,
               entity.start_char,entity.end_char,entity.entity_type_symbol_id,
               label.label_symbol_id
          FROM execution.semantic_parser_provider_entity_span_v1 entity
          JOIN execution.semantic_pnf_parser_entity_surface_label label
            ON label.entity_id=entity.entity_id
        ON CONFLICT(run_ref,document_ref,sentence_ref,start_char,end_char,
                    entity_type_symbol_id,label_symbol_id) DO NOTHING
        RETURNING 1
    ) SELECT count(*) INTO n FROM inserted;
    affected:=affected+n;

    INSERT INTO execution.semantic_parser_provider_entity_candidate_support
        (provider_entity_candidate_id,support_kind,parser_entity_id,
         producer_ref,producer_version,active)
    SELECT candidate.provider_entity_candidate_id,1::SMALLINT,entity.entity_id,
           'spacy-primary-doc-ents',COALESCE(receipt.model_version,'unknown'),TRUE
      FROM execution.semantic_parser_provider_entity_span_v1 entity
      JOIN execution.semantic_pnf_parser_entity_surface_label label
        ON label.entity_id=entity.entity_id
      JOIN execution.semantic_parser_provider_entity_candidate candidate
        ON candidate.run_ref=entity.run_ref
       AND candidate.document_ref=entity.document_ref
       AND candidate.sentence_ref=entity.sentence_ref
       AND candidate.start_char=entity.start_char
       AND candidate.end_char=entity.end_char
       AND candidate.entity_type_symbol_id=entity.entity_type_symbol_id
       AND candidate.label_symbol_id=label.label_symbol_id
      LEFT JOIN execution.semantic_parser_partition_receipt receipt
        ON receipt.partition_ref=entity.partition_ref
    ON CONFLICT(provider_entity_candidate_id,support_kind,producer_ref,producer_version,
                parser_entity_id,secondary_entity_id)
    DO UPDATE SET active=TRUE;

    -- Active secondary-model observations that pass the same gate.
    WITH inserted AS (
        INSERT INTO execution.semantic_parser_provider_entity_candidate
            (run_ref,document_ref,sentence_ref,start_char,end_char,
             entity_type_symbol_id,label_symbol_id)
        SELECT quality.run_ref,quality.document_ref,quality.sentence_ref,
               quality.start_char,quality.end_char,quality.entity_type_symbol_id,
               quality.label_symbol_id
          FROM execution.semantic_parser_secondary_entity_span_quality_v1 quality
         WHERE quality.provider_admissible
        ON CONFLICT(run_ref,document_ref,sentence_ref,start_char,end_char,
                    entity_type_symbol_id,label_symbol_id) DO NOTHING
        RETURNING 1
    ) SELECT count(*) INTO n FROM inserted;
    affected:=affected+n;

    INSERT INTO execution.semantic_parser_provider_entity_candidate_support
        (provider_entity_candidate_id,support_kind,secondary_entity_id,
         producer_ref,producer_version,active)
    SELECT candidate.provider_entity_candidate_id,2::SMALLINT,
           span.secondary_entity_id,pass.model_name,pass.model_version,TRUE
      FROM execution.semantic_parser_secondary_entity_span_quality_v1 quality
      JOIN execution.semantic_parser_secondary_entity_span span
        ON span.secondary_entity_id=quality.secondary_entity_id
      JOIN execution.semantic_parser_secondary_entity_pass pass
        ON pass.pass_id=span.pass_id AND pass.active
      JOIN execution.semantic_parser_provider_entity_candidate candidate
        ON candidate.run_ref=quality.run_ref
       AND candidate.document_ref=quality.document_ref
       AND candidate.sentence_ref=quality.sentence_ref
       AND candidate.start_char=quality.start_char
       AND candidate.end_char=quality.end_char
       AND candidate.entity_type_symbol_id=quality.entity_type_symbol_id
       AND candidate.label_symbol_id=quality.label_symbol_id
     WHERE quality.provider_admissible
    ON CONFLICT(provider_entity_candidate_id,support_kind,producer_ref,producer_version,
                parser_entity_id,secondary_entity_id)
    DO UPDATE SET active=TRUE;

    RETURN affected;
END;
$$;

CREATE OR REPLACE VIEW execution.semantic_parser_provider_entity_candidate_current_v1 AS
SELECT candidate.*,
       count(*) FILTER (WHERE support.active)::BIGINT AS active_support_count,
       count(*) FILTER (WHERE support.active AND support.support_kind=1)::BIGINT
           AS primary_support_count,
       count(*) FILTER (WHERE support.active AND support.support_kind=2)::BIGINT
           AS secondary_support_count
  FROM execution.semantic_parser_provider_entity_candidate candidate
  JOIN execution.semantic_parser_provider_entity_candidate_support support
    ON support.provider_entity_candidate_id=candidate.provider_entity_candidate_id
 GROUP BY candidate.provider_entity_candidate_id
HAVING count(*) FILTER (WHERE support.active)>0;

SELECT execution.refresh_semantic_parser_provider_entity_candidates();

COMMIT;
