BEGIN;

-- Stable source evidence for direct semantic publication --------------------------
--
-- This carrier is deliberately independent of execution.semantic_parser_token.
-- A parser observation is identified by immutable sentence/token digests and source
-- spans.  Numeric PNF rows may therefore retain proof-bearing source support after
-- the legacy parser-token projection is no longer materialised in production.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_source_evidence (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_digest BYTEA NOT NULL UNIQUE,
    sentence_digest BYTEA NOT NULL,
    token_digest BYTEA NOT NULL,
    start_char BIGINT NOT NULL CHECK (start_char >= 0),
    end_char BIGINT NOT NULL CHECK (end_char >= start_char),
    evidence_kind SMALLINT NOT NULL DEFAULT 1 CHECK (evidence_kind = 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (sentence_digest, token_digest, start_char, end_char, evidence_kind)
);
CREATE INDEX IF NOT EXISTS semantic_pnf_source_evidence_sentence_idx
    ON execution.semantic_pnf_source_evidence(sentence_digest, start_char, end_char);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_object_evidence_support (
    object_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_object(object_id) ON DELETE CASCADE,
    evidence_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_source_evidence(evidence_id) ON DELETE RESTRICT,
    ordinal SMALLINT NOT NULL CHECK (ordinal >= 0),
    PRIMARY KEY (object_id, evidence_id, ordinal)
);
CREATE INDEX IF NOT EXISTS semantic_pnf_object_evidence_support_evidence_idx
    ON execution.semantic_pnf_object_evidence_support(evidence_id, object_id);

CREATE TABLE IF NOT EXISTS execution.semantic_pnf_factor_evidence_support (
    factor_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_factor(factor_id) ON DELETE CASCADE,
    evidence_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_source_evidence(evidence_id) ON DELETE RESTRICT,
    ordinal SMALLINT NOT NULL CHECK (ordinal >= 0),
    PRIMARY KEY (factor_id, evidence_id, ordinal)
);
CREATE INDEX IF NOT EXISTS semantic_pnf_factor_evidence_support_evidence_idx
    ON execution.semantic_pnf_factor_evidence_support(evidence_id, factor_id);

-- Production G4 is a database-observable property, not a convention in Python.
-- This view gives validation and deployment code one exact surface on which to
-- assert that direct publication is backed only by stable evidence support.
CREATE OR REPLACE VIEW execution.semantic_pnf_stable_evidence_support_count AS
SELECT
    (SELECT count(*) FROM execution.semantic_pnf_source_evidence) AS evidence_rows,
    (SELECT count(*) FROM execution.semantic_pnf_object_evidence_support)
        AS object_support_rows,
    (SELECT count(*) FROM execution.semantic_pnf_factor_evidence_support)
        AS factor_support_rows;

COMMIT;
