BEGIN;

-- The summary receipt is intentionally one row per stage and therefore cannot
-- retain both hierarchy frontier invocations.  Keep that compatibility surface,
-- but append execution-only timing samples whenever it is inserted or updated.
CREATE TABLE IF NOT EXISTS execution.semantic_pnf_frontier_stage_sample (
    sample_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_run_identity(run_id) ON DELETE CASCADE,
    document_id BIGINT NOT NULL
        REFERENCES execution.semantic_pnf_document_identity(document_id)
        ON DELETE CASCADE,
    stage_name TEXT NOT NULL,
    row_count BIGINT NOT NULL CHECK (row_count >= 0),
    elapsed_ms DOUBLE PRECISION NOT NULL CHECK (elapsed_ms >= 0),
    observed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS semantic_pnf_frontier_stage_sample_lookup_idx
    ON execution.semantic_pnf_frontier_stage_sample
       (run_id, document_id, stage_name, sample_id);

CREATE OR REPLACE FUNCTION execution.capture_numeric_pnf_frontier_stage_sample()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO execution.semantic_pnf_frontier_stage_sample
        (run_id, document_id, stage_name, row_count, elapsed_ms)
    VALUES (
        NEW.run_id,
        NEW.document_id,
        NEW.stage_name,
        NEW.row_count,
        NEW.elapsed_ms
    );
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS semantic_pnf_frontier_stage_sample_capture
    ON execution.semantic_pnf_frontier_stage_receipt;
CREATE TRIGGER semantic_pnf_frontier_stage_sample_capture
AFTER INSERT OR UPDATE OF row_count, elapsed_ms
ON execution.semantic_pnf_frontier_stage_receipt
FOR EACH ROW
EXECUTE FUNCTION execution.capture_numeric_pnf_frontier_stage_sample();

COMMENT ON TABLE execution.semantic_pnf_frontier_stage_sample IS
    'Execution observability only: append-only invocation samples for frontier stages. Not semantic authority and not part of portable parity identity.';

COMMIT;
