BEGIN;

-- C3d/systemic: desired/current relation reconciliation ----------------------
--
-- This migration establishes a reusable receipt surface for keyed-relation
-- reconciliation and rewrites the hot demand-candidate planner so unchanged
-- rows are retained verbatim.  Candidate history now records actual execution
-- transitions rather than delete/reinsert churn from an unchanged replan.

CREATE TABLE IF NOT EXISTS execution.semantic_relation_reconciliation_receipt (
    receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_ref TEXT NOT NULL,
    scope_a BIGINT,
    scope_b BIGINT,
    desired_rows BIGINT NOT NULL CHECK (desired_rows >= 0),
    current_rows_before BIGINT NOT NULL CHECK (current_rows_before >= 0),
    added_rows BIGINT NOT NULL CHECK (added_rows >= 0),
    removed_rows BIGINT NOT NULL CHECK (removed_rows >= 0),
    replaced_rows BIGINT NOT NULL CHECK (replaced_rows >= 0),
    unchanged_rows_skipped BIGINT NOT NULL CHECK (unchanged_rows_skipped >= 0),
    physical_row_mutations BIGINT NOT NULL CHECK (physical_row_mutations >= 0),
    mutation_statements SMALLINT NOT NULL CHECK (mutation_statements BETWEEN 0 AND 3),
    semantic_authority_effect TEXT NOT NULL DEFAULT 'none',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        desired_rows = added_rows + replaced_rows + unchanged_rows_skipped
    ),
    CHECK (
        current_rows_before = removed_rows + replaced_rows + unchanged_rows_skipped
    ),
    CHECK (
        physical_row_mutations = added_rows + removed_rows + (2 * replaced_rows)
    )
);
CREATE INDEX IF NOT EXISTS semantic_relation_reconciliation_owner_scope_idx
    ON execution.semantic_relation_reconciliation_receipt
       (owner_ref, scope_a, scope_b, receipt_id DESC);

CREATE OR REPLACE FUNCTION execution.plan_numeric_pnf_demand_candidates_ids(
    selected_run_id BIGINT,
    selected_document_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    inserted_total BIGINT := 0;
    deleted_total BIGINT := 0;
    replaced_total BIGINT := 0;
    desired_total BIGINT := 0;
    current_before BIGINT := 0;
    unchanged_total BIGINT := 0;
    mutation_statements SMALLINT := 0;
    anaphor_residual_id BIGINT;
    pronoun_kind_id BIGINT;
BEGIN
    PERFORM set_config('work_mem', '256MB', true);

    SELECT symbol_id
      INTO anaphor_residual_id
      FROM execution.semantic_symbol
     WHERE kind_id = 13
       AND symbol_text = 'anaphor_unresolved';
    SELECT symbol_id
      INTO pronoun_kind_id
      FROM execution.semantic_symbol
     WHERE kind_id = 14
       AND symbol_text = 'mention.pronoun';

    CREATE TEMP TABLE IF NOT EXISTS pg_temp.semantic_pnf_desired_candidate (
        demand_id BIGINT NOT NULL,
        ordinal SMALLINT NOT NULL,
        target_kind SMALLINT NOT NULL,
        target_id BIGINT NOT NULL,
        source_interface_id BIGINT NOT NULL,
        ancestor_distance BIGINT NOT NULL,
        index_rank BIGINT NOT NULL,
        candidate_score DOUBLE PRECISION NOT NULL,
        PRIMARY KEY (demand_id, target_kind, target_id)
    ) ON COMMIT DROP;
    TRUNCATE pg_temp.semantic_pnf_desired_candidate;

    WITH selected_demand AS (
        SELECT demand.demand_id,
               demand.source_interface_id,
               demand.source_region_id,
               demand.expected_target_kind,
               demand.residual_type_symbol_id,
               demand.recency_class,
               demand.max_candidates,
               COALESCE(demand.source_start_char, source_region.end_char)
                   AS demand_position,
               source_region.parent_region_id AS source_parent_region_id,
               source_region.start_char AS source_region_start,
               source_region.end_char AS source_region_end
          FROM execution.semantic_pnf_demand AS demand
          JOIN execution.semantic_pnf_region AS source_region
            ON source_region.region_id = demand.source_region_id
         WHERE source_region.run_id = selected_run_id
           AND source_region.document_id = selected_document_id
           AND demand.source_interface_id IS NOT NULL
           AND demand.state IN (1, 2)
    ),
    exact_match AS (
        SELECT demand.demand_id,
               demand.source_interface_id,
               demand.source_region_id,
               demand.recency_class,
               demand.max_candidates,
               demand.demand_position,
               demand.source_parent_region_id,
               demand.source_region_start,
               demand.source_region_end,
               global.target_kind,
               global.target_id,
               COALESCE(origin_interface.interface_id, global.interface_id)
                   AS candidate_interface_id,
               origin_region.region_id AS candidate_region_id,
               origin_region.parent_region_id AS candidate_parent_region_id,
               origin_region.start_char AS candidate_region_start,
               origin_region.end_char AS candidate_region_end,
               abs(demand.demand_position - origin_region.end_char)
                   AS structural_distance,
               global.rank AS index_rank,
               COALESCE(object.promotion_score, factor.support_score, 0)
                   AS candidate_score,
               global.region_end_char - global.region_start_char
                   AS export_scope_width
          FROM selected_demand AS demand
          JOIN execution.semantic_pnf_demand_lookup_key AS demand_key
            ON demand_key.demand_id = demand.demand_id
          JOIN execution.semantic_pnf_global_lookup AS global
            ON global.run_id = selected_run_id
           AND global.document_id = selected_document_id
           AND global.key_kind = demand_key.key_kind
           AND global.key_a = demand_key.key_a
           AND global.key_b = demand_key.key_b
           AND global.target_kind = demand_key.target_kind
          LEFT JOIN execution.semantic_pnf_object AS object
            ON global.target_kind = 1
           AND object.object_id = global.target_id
          LEFT JOIN execution.semantic_pnf_factor AS factor
            ON global.target_kind = 2
           AND factor.factor_id = global.target_id
          JOIN execution.semantic_pnf_region AS origin_region
            ON origin_region.region_id = COALESCE(
                object.region_id,
                factor.region_id,
                global.region_id
            )
          LEFT JOIN execution.semantic_pnf_interface AS origin_interface
            ON origin_interface.region_id = origin_region.region_id
    ),
    anaphor_match AS (
        SELECT demand.demand_id,
               demand.source_interface_id,
               demand.source_region_id,
               demand.recency_class,
               demand.max_candidates,
               demand.demand_position,
               demand.source_parent_region_id,
               demand.source_region_start,
               demand.source_region_end,
               cand.target_kind,
               cand.target_id,
               cand.candidate_interface_id,
               cand.candidate_region_id,
               cand.candidate_parent_region_id,
               cand.candidate_region_start,
               cand.candidate_region_end,
               cand.structural_distance,
               cand.index_rank,
               cand.candidate_score,
               cand.export_scope_width
          FROM selected_demand AS demand
          CROSS JOIN LATERAL (
              SELECT global.target_kind,
                     global.target_id,
                     COALESCE(origin_interface.interface_id, global.interface_id)
                         AS candidate_interface_id,
                     origin_region.region_id AS candidate_region_id,
                     origin_region.parent_region_id AS candidate_parent_region_id,
                     origin_region.start_char AS candidate_region_start,
                     origin_region.end_char AS candidate_region_end,
                     (demand.demand_position - origin_region.end_char)
                         AS structural_distance,
                     global.rank AS index_rank,
                     object.promotion_score AS candidate_score,
                     global.region_end_char - global.region_start_char
                         AS export_scope_width
                FROM execution.semantic_pnf_global_lookup AS global
                JOIN execution.semantic_pnf_object AS object
                  ON object.object_id = global.target_id
                JOIN execution.semantic_pnf_region AS origin_region
                  ON origin_region.region_id = object.region_id
                LEFT JOIN execution.semantic_pnf_interface AS origin_interface
                  ON origin_interface.region_id = origin_region.region_id
               WHERE global.run_id = selected_run_id
                 AND global.document_id = selected_document_id
                 AND global.target_kind = 1
                 AND origin_region.region_id <> demand.source_region_id
                 AND origin_region.end_char <= demand.demand_position
                 AND (
                     pronoun_kind_id IS NULL
                     OR object.object_kind_symbol_id <> pronoun_kind_id
                 )
               ORDER BY origin_region.end_char DESC, global.rank
               LIMIT LEAST(demand.max_candidates, 10)
          ) AS cand
         WHERE demand.residual_type_symbol_id = anaphor_residual_id
    ),
    all_match AS (
        SELECT * FROM exact_match
        UNION ALL
        SELECT * FROM anaphor_match
    ),
    target_deduplicated AS (
        SELECT match.*,
               row_number() OVER (
                   PARTITION BY match.demand_id,
                                match.target_kind,
                                match.target_id
                   ORDER BY match.structural_distance,
                            match.export_scope_width,
                            match.index_rank,
                            match.candidate_interface_id
               ) AS target_occurrence
          FROM all_match AS match
    ),
    bounded AS (
        SELECT match.*,
               row_number() OVER (
                   PARTITION BY match.demand_id
                   ORDER BY match.structural_distance,
                            match.index_rank,
                            match.target_id
               ) - 1 AS candidate_ordinal
          FROM target_deduplicated AS match
         WHERE match.target_occurrence = 1
    ),
    bounded_top AS (
        SELECT *
          FROM bounded
         WHERE candidate_ordinal < max_candidates
    ),
    scoped AS (
        SELECT bounded.*,
               common_scope.interface_id AS common_scope_interface_id,
               common_scope.region_kind AS common_scope_region_kind
          FROM bounded_top AS bounded
          LEFT JOIN LATERAL (
              SELECT interface.interface_id,
                     common_region.region_kind
                FROM execution.semantic_pnf_region AS common_region
                JOIN execution.semantic_pnf_interface AS interface
                  ON interface.region_id = common_region.region_id
               WHERE common_region.run_id = selected_run_id
                 AND common_region.document_id = selected_document_id
                 AND common_region.start_char <= LEAST(
                     bounded.source_region_start,
                     bounded.candidate_region_start
                 )
                 AND common_region.end_char >= GREATEST(
                     bounded.source_region_end,
                     bounded.candidate_region_end
                 )
                 AND interface.closure_state IN (2, 3)
               ORDER BY common_region.end_char - common_region.start_char,
                        common_region.region_kind,
                        interface.interface_id
               LIMIT 1
          ) AS common_scope ON TRUE
    ),
    valid AS (
        SELECT scoped.*
          FROM scoped
         WHERE scoped.common_scope_interface_id IS NOT NULL
           AND CASE scoped.recency_class
               WHEN 1 THEN
                   scoped.source_region_id = scoped.candidate_region_id
               WHEN 2 THEN
                   scoped.source_parent_region_id IS NOT DISTINCT FROM
                       scoped.candidate_parent_region_id
                   AND scoped.candidate_region_end <= scoped.demand_position
               WHEN 3 THEN
                   scoped.source_region_id = scoped.candidate_region_id
                   OR scoped.candidate_region_end <= scoped.demand_position
               WHEN 4 THEN
                   scoped.common_scope_region_kind >= 3
               WHEN 5 THEN
                   scoped.common_scope_region_kind <= 10
               ELSE FALSE
           END
    )
    INSERT INTO pg_temp.semantic_pnf_desired_candidate
        (demand_id, ordinal, target_kind, target_id,
         source_interface_id, ancestor_distance, index_rank, candidate_score)
    SELECT valid.demand_id,
           (row_number() OVER (
               PARTITION BY valid.demand_id
               ORDER BY valid.candidate_ordinal
           ) - 1)::SMALLINT,
           valid.target_kind,
           valid.target_id,
           valid.common_scope_interface_id,
           valid.structural_distance,
           valid.index_rank,
           valid.candidate_score
      FROM valid;

    SELECT count(*) INTO desired_total
      FROM pg_temp.semantic_pnf_desired_candidate;

    SELECT count(*) INTO current_before
      FROM execution.semantic_pnf_demand_candidate AS candidate
      JOIN execution.semantic_pnf_demand AS demand
        ON demand.demand_id = candidate.demand_id
      JOIN execution.semantic_pnf_region AS source_region
        ON source_region.region_id = demand.source_region_id
     WHERE source_region.run_id = selected_run_id
       AND source_region.document_id = selected_document_id
       AND demand.state IN (1, 2);

    -- Remove only rows absent from desired OR whose execution payload changed.
    -- The existing statement-level delete observer now receives only true
    -- removals/replacements; unchanged candidates emit no superseded event.
    WITH deleted AS (
        DELETE FROM execution.semantic_pnf_demand_candidate AS candidate
        USING execution.semantic_pnf_demand AS demand,
              execution.semantic_pnf_region AS source_region
        WHERE candidate.demand_id = demand.demand_id
          AND source_region.region_id = demand.source_region_id
          AND source_region.run_id = selected_run_id
          AND source_region.document_id = selected_document_id
          AND demand.state IN (1, 2)
          AND NOT EXISTS (
              SELECT 1
                FROM pg_temp.semantic_pnf_desired_candidate AS desired
               WHERE desired.demand_id = candidate.demand_id
                 AND desired.target_kind = candidate.target_kind
                 AND desired.target_id = candidate.target_id
                 AND desired.ordinal = candidate.ordinal
                 AND desired.source_interface_id = candidate.source_interface_id
                 AND desired.ancestor_distance = candidate.ancestor_distance
                 AND desired.index_rank = candidate.index_rank
                 AND desired.candidate_score IS NOT DISTINCT FROM candidate.candidate_score
          )
        RETURNING candidate.demand_id, candidate.target_kind, candidate.target_id
    )
    SELECT count(*),
           count(*) FILTER (
               WHERE EXISTS (
                   SELECT 1
                     FROM pg_temp.semantic_pnf_desired_candidate AS desired
                    WHERE desired.demand_id = deleted.demand_id
                      AND desired.target_kind = deleted.target_kind
                      AND desired.target_id = deleted.target_id
               )
           )
      INTO deleted_total, replaced_total
      FROM deleted;
    IF deleted_total > 0 THEN
        mutation_statements := mutation_statements + 1;
    END IF;

    INSERT INTO execution.semantic_pnf_demand_candidate
        (demand_id, ordinal, target_kind, target_id,
         source_interface_id, ancestor_distance, index_rank, candidate_score)
    SELECT desired.demand_id,
           desired.ordinal,
           desired.target_kind,
           desired.target_id,
           desired.source_interface_id,
           desired.ancestor_distance,
           desired.index_rank,
           desired.candidate_score
      FROM pg_temp.semantic_pnf_desired_candidate AS desired
     WHERE NOT EXISTS (
         SELECT 1
           FROM execution.semantic_pnf_demand_candidate AS candidate
          WHERE candidate.demand_id = desired.demand_id
            AND candidate.target_kind = desired.target_kind
            AND candidate.target_id = desired.target_id
     );
    GET DIAGNOSTICS inserted_total = ROW_COUNT;
    IF inserted_total > 0 THEN
        mutation_statements := mutation_statements + 1;
    END IF;

    unchanged_total := desired_total - inserted_total;

    -- Update cardinality for the entire selected demand fibre, including zero.
    WITH selected AS (
        SELECT demand.demand_id
          FROM execution.semantic_pnf_demand AS demand
          JOIN execution.semantic_pnf_region AS source_region
            ON source_region.region_id = demand.source_region_id
         WHERE source_region.run_id = selected_run_id
           AND source_region.document_id = selected_document_id
           AND demand.source_interface_id IS NOT NULL
           AND demand.state IN (1, 2)
    ), counted AS (
        SELECT selected.demand_id,
               count(candidate.demand_id)::SMALLINT AS candidate_count
          FROM selected
          LEFT JOIN execution.semantic_pnf_demand_candidate AS candidate
            ON candidate.demand_id = selected.demand_id
         GROUP BY selected.demand_id
    )
    UPDATE execution.semantic_pnf_demand AS demand
       SET candidate_count = counted.candidate_count,
           state = CASE
               WHEN counted.candidate_count > 0 THEN 2
               ELSE demand.state
           END
      FROM counted
     WHERE demand.demand_id = counted.demand_id
       AND (
           demand.candidate_count IS DISTINCT FROM counted.candidate_count
           OR (counted.candidate_count > 0 AND demand.state <> 2)
       );
    IF FOUND THEN
        mutation_statements := mutation_statements + 1;
    END IF;

    INSERT INTO execution.semantic_relation_reconciliation_receipt
        (owner_ref, scope_a, scope_b,
         desired_rows, current_rows_before,
         added_rows, removed_rows, replaced_rows, unchanged_rows_skipped,
         physical_row_mutations, mutation_statements, semantic_authority_effect)
    VALUES (
        'execution.plan_numeric_pnf_demand_candidates_ids',
        selected_run_id,
        selected_document_id,
        desired_total,
        current_before,
        inserted_total - replaced_total,
        deleted_total - replaced_total,
        replaced_total,
        unchanged_total,
        inserted_total + deleted_total,
        mutation_statements,
        'none'
    );

    -- Historical return contract is number of candidate rows inserted.
    RETURN inserted_total;
END;
$$;

COMMIT;
