repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        files: ^(src|tests)/
        args: [--ignore=E402]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^(src|tests)/
        pass_filenames: false
        args: [--config-file, mypy.ini, src, tests]
