repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff
        args: ["--fix", "--config=pyproject.toml"]
        files: "^(src|tests|scripts)/"
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        args: ["--check"]
        files: "^(src|tests|scripts)/"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.0
    hooks:
      - id: mypy
        files: "^(src|tests)/"
        pass_filenames: false
        args: ["--config-file", "pyproject.toml", "--explicit-package-bases", "."]
