from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MIGRATION = ROOT / "database/postgres_migrations/198_frontier_stage_timing_samples.sql"


def test_frontier_stage_samples_are_append_only_execution_observability() -> None:
    sql = MIGRATION.read_text(encoding="utf-8")

    assert "CREATE TABLE IF NOT EXISTS execution.semantic_pnf_frontier_stage_sample" in sql
    assert "sample_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql
    assert "Execution observability only" in sql
    assert "Not semantic authority" in sql


def test_summary_receipt_updates_capture_each_invocation() -> None:
    sql = MIGRATION.read_text(encoding="utf-8")

    assert "AFTER INSERT OR UPDATE OF row_count, elapsed_ms" in sql
    assert "capture_numeric_pnf_frontier_stage_sample" in sql
    assert "INSERT INTO execution.semantic_pnf_frontier_stage_sample" in sql
