"""Text processing utilities."""

from .nlp import (
    FastTextLanguageDetector,
    LanguageDetector,
    SimpleDoc,
    SpacyNLP,
    TikaLanguageDetector,
)
from .shared_text_normalization import (
    split_semicolon_clauses,
    split_text_clauses,
    split_text_segments,
    strip_enumeration_prefix,
    tokenize_canonical_text,
)
from .phrase_cues import extract_text_cues
from .residual_lattice import (
    CandidateResidual,
    PredicateIndex,
    PredicatePNF,
    PredicateAtom,
    QualifierState,
    Residual,
    ResidualLevel,
    RoleState,
    TypedArg,
    WrapperState,
    build_predicate_index,
    build_predicate_ref_map,
    collect_candidate_predicate_refs,
    collect_candidate_residuals,
    coerce_predicate_atom,
    comparable,
    compute_indexed_residual,
    compute_residual,
    join_role_states,
    join_residual,
    join_typed_args,
    meet_atom,
)

__all__ = [
    "FastTextLanguageDetector",
    "LanguageDetector",
    "SimpleDoc",
    "SpacyNLP",
    "TikaLanguageDetector",
    "split_semicolon_clauses",
    "split_text_clauses",
    "split_text_segments",
    "strip_enumeration_prefix",
    "tokenize_canonical_text",
    "extract_text_cues",
    "PredicatePNF",
    "PredicateAtom",
    "PredicateIndex",
    "CandidateResidual",
    "QualifierState",
    "Residual",
    "ResidualLevel",
    "RoleState",
    "TypedArg",
    "WrapperState",
    "build_predicate_index",
    "build_predicate_ref_map",
    "collect_candidate_predicate_refs",
    "collect_candidate_residuals",
    "coerce_predicate_atom",
    "comparable",
    "compute_indexed_residual",
    "compute_residual",
    "join_role_states",
    "join_residual",
    "join_typed_args",
    "meet_atom",
]
