"""Factorized PNF graph and fibred semantic compiler primitives."""

from .binding_candidate_sets import (
    BindingAccessibilityDeclaration,
    BindingCandidateMember,
    BindingCandidateSet,
    BindingCompatibilityDeclaration,
    BindingExclusionSummary,
    FactorAnchor,
    compact_binding_artifacts,
)
from .closure import ClosureContract, assess_pnf_closure
from .demands import derive_resolution_demands
from .factor_proposals import (
    INTEGRATED_SEMANTIC_PRODUCER_CONTRACT,
    CompositionDeclaration,
    CrossDocumentRelation,
    FactorProposal,
    ProposalReduction,
    ReducedFactor,
    ReductionResidual,
    proposal_build_key,
    reduce_factor_proposals,
)
from .graph import PNFGraph
from .integrated_semantic_producer import (
    IntegratedProducerContract,
    IntegratedProducerReceipt,
    IntegratedSemanticProducer,
    ProducerCapability,
    SubExecutorReceipt,
)
from .operational_reference_binding import (
    REFERENCE_BINDING_CONTRACT_REF,
    REFERENCE_REDUCTION_DECLARATION_REF,
    build_operational_reference_binding_artifacts,
    build_set_valued_binding_artifacts,
)
from .reference_binding import project_pronominal_reference_arguments
from .review_coordinates import (
    SemanticReviewAssessment,
    SemanticReviewCoordinate,
    project_review_state,
)
from .revision_normalization import normalize_factor_revision_artifacts
from .semantic_fibres import (
    AxisObligation,
    FibreBoundaryObligation,
    FibreDerivation,
    FibreElement,
    FibreValidation,
    OntologyAxis,
    SemanticCoordinate,
    SemanticFibreLedger,
    SemanticTransport,
    evaluate_fibre,
    fibre_element_from_proposal_row,
)
from .stage_build_keys import StageBuildKeys, derive_stage_build_keys
from .streaming_fixed_point import (
    ClosureExecutor,
    ConvergentLedger,
    CoverageNotice,
    DocumentFixedPointCertificate,
    ObservationDelta,
    OwnerKey,
    PythonClosureExecutor,
    RegionBoundarySummary,
    SolverJob,
    SolverReceipt,
    StateDelta,
    StreamingDeclaration,
    StreamingSemanticOwner,
    assert_finalising_claim_allowed,
    execute_ready_jobs,
    owner_partition,
)

__all__ = [
    "INTEGRATED_SEMANTIC_PRODUCER_CONTRACT",
    "AxisObligation",
    "BindingAccessibilityDeclaration",
    "BindingCandidateMember",
    "BindingCandidateSet",
    "BindingCompatibilityDeclaration",
    "BindingExclusionSummary",
    "ClosureContract",
    "ClosureExecutor",
    "CompositionDeclaration",
    "ConvergentLedger",
    "CoverageNotice",
    "CrossDocumentRelation",
    "DocumentFixedPointCertificate",
    "FactorAnchor",
    "FactorProposal",
    "FibreBoundaryObligation",
    "FibreDerivation",
    "FibreElement",
    "FibreValidation",
    "IntegratedProducerContract",
    "IntegratedProducerReceipt",
    "IntegratedSemanticProducer",
    "ObservationDelta",
    "OntologyAxis",
    "OwnerKey",
    "PNFGraph",
    "ProducerCapability",
    "ProposalReduction",
    "PythonClosureExecutor",
    "REFERENCE_BINDING_CONTRACT_REF",
    "REFERENCE_REDUCTION_DECLARATION_REF",
    "ReducedFactor",
    "ReductionResidual",
    "RegionBoundarySummary",
    "SemanticCoordinate",
    "SemanticFibreLedger",
    "SemanticReviewAssessment",
    "SemanticReviewCoordinate",
    "SemanticTransport",
    "SolverJob",
    "SolverReceipt",
    "StageBuildKeys",
    "StateDelta",
    "StreamingDeclaration",
    "StreamingSemanticOwner",
    "SubExecutorReceipt",
    "assert_finalising_claim_allowed",
    "assess_pnf_closure",
    "build_operational_reference_binding_artifacts",
    "build_set_valued_binding_artifacts",
    "compact_binding_artifacts",
    "derive_resolution_demands",
    "derive_stage_build_keys",
    "evaluate_fibre",
    "execute_ready_jobs",
    "fibre_element_from_proposal_row",
    "normalize_factor_revision_artifacts",
    "owner_partition",
    "project_pronominal_reference_arguments",
    "project_review_state",
    "proposal_build_key",
    "reduce_factor_proposals",
]
