"""Factorized PNF graph and fibred semantic compiler primitives."""

from .binding_candidate_sets import (
    BindingAccessibilityDeclaration,
    BindingCandidateMember,
    BindingCandidateSet,
    BindingCompatibilityDeclaration,
    BindingExclusionSummary,
    FactorAnchor,
    compact_binding_artifacts,
)
from .closure import ClosureContract, assess_pnf_closure
from .demands import derive_resolution_demands
from .domain_ir import (
    DomainIRBuild,
    DomainIRProjection,
    DomainIRProjectionContract,
    DomainIRProjectionReceipt,
    ProjectionDemand,
    ProjectionLossReceipt,
)
from .domain_ir_applicability import (
    build_applicable_domain_ir,
    normalize_projection_applicability,
)
from .domain_ir_projection import (
    DEFAULT_DOMAIN_IR_CONTRACTS,
    LEGAL_IR_CONTRACT,
    RETRIEVAL_IR_CONTRACT,
    TIMELINE_IR_CONTRACT,
    build_domain_ir,
    project_resolved_factor,
)
from .factor_proposals import (
    INTEGRATED_SEMANTIC_PRODUCER_CONTRACT,
    CompositionDeclaration,
    CrossDocumentRelation,
    FactorProposal,
    ProposalReduction,
    ReducedFactor,
    ReductionResidual,
    proposal_build_key,
    reduce_factor_proposals,
)
from .graph import PNFGraph
from .integrated_semantic_producer import (
    IntegratedProducerContract,
    IntegratedProducerReceipt,
    IntegratedSemanticProducer,
    ProducerCapability,
    SubExecutorReceipt,
)
from .ir_execution import (
    IRExecutionReceipt,
    IRExecutionRequest,
    execute_ir_request,
    execute_ir_requests,
)
from .operational_reference_binding import (
    REFERENCE_BINDING_CONTRACT_REF,
    REFERENCE_REDUCTION_DECLARATION_REF,
    build_operational_reference_binding_artifacts,
    build_set_valued_binding_artifacts,
)
from .reference_binding import project_pronominal_reference_arguments
from .review_coordinates import (
    SemanticReviewAssessment,
    SemanticReviewCoordinate,
    project_review_state,
)
from .revision_normalization import normalize_factor_revision_artifacts
from .semantic_fibres import (
    AxisObligation,
    FibreBoundaryObligation,
    FibreDerivation,
    FibreElement,
    FibreValidation,
    OntologyAxis,
    SemanticCoordinate,
    SemanticFibreLedger,
    SemanticTransport,
    evaluate_fibre,
    fibre_element_from_proposal_row,
)
from .semantic_lifecycle import (
    AdmissibilityReceipt,
    CandidateAssessment,
    ResolutionReceipt,
    SemanticLifecycleResult,
    admit_factor_proposals,
    assess_factor_proposals,
    build_semantic_lifecycle,
    resolve_reduced_factors,
)
from .semantic_lifecycle_pipeline import (
    build_admission_aware_semantic_lifecycle,
)
from .stage_build_keys import StageBuildKeys, derive_stage_build_keys
from .streaming_fixed_point import (
    ClosureExecutor,
    ConvergentLedger,
    CoverageNotice,
    DocumentFixedPointCertificate,
    ObservationDelta,
    OwnerKey,
    PythonClosureExecutor,
    RegionBoundarySummary,
    SolverJob,
    SolverReceipt,
    StateDelta,
    StreamingDeclaration,
    StreamingSemanticOwner,
    assert_finalising_claim_allowed,
    execute_ready_jobs,
    owner_partition,
)
from .streaming_reduction_metrics import install_streaming_reduction_metrics

install_streaming_reduction_metrics()

__all__ = [
    "INTEGRATED_SEMANTIC_PRODUCER_CONTRACT",
    "DEFAULT_DOMAIN_IR_CONTRACTS",
    "LEGAL_IR_CONTRACT",
    "REFERENCE_BINDING_CONTRACT_REF",
    "REFERENCE_REDUCTION_DECLARATION_REF",
    "RETRIEVAL_IR_CONTRACT",
    "TIMELINE_IR_CONTRACT",
    "AdmissibilityReceipt",
    "AxisObligation",
    "BindingAccessibilityDeclaration",
    "BindingCandidateMember",
    "BindingCandidateSet",
    "BindingCompatibilityDeclaration",
    "BindingExclusionSummary",
    "CandidateAssessment",
    "ClosureContract",
    "ClosureExecutor",
    "CompositionDeclaration",
    "ConvergentLedger",
    "CoverageNotice",
    "CrossDocumentRelation",
    "DocumentFixedPointCertificate",
    "DomainIRBuild",
    "DomainIRProjection",
    "DomainIRProjectionContract",
    "DomainIRProjectionReceipt",
    "FactorAnchor",
    "FactorProposal",
    "FibreBoundaryObligation",
    "FibreDerivation",
    "FibreElement",
    "FibreValidation",
    "IRExecutionReceipt",
    "IRExecutionRequest",
    "IntegratedProducerContract",
    "IntegratedProducerReceipt",
    "IntegratedSemanticProducer",
    "ObservationDelta",
    "OntologyAxis",
    "OwnerKey",
    "PNFGraph",
    "ProducerCapability",
    "ProjectionDemand",
    "ProjectionLossReceipt",
    "ProposalReduction",
    "PythonClosureExecutor",
    "ReducedFactor",
    "ReductionResidual",
    "RegionBoundarySummary",
    "ResolutionReceipt",
    "SemanticCoordinate",
    "SemanticFibreLedger",
    "SemanticLifecycleResult",
    "SemanticReviewAssessment",
    "SemanticReviewCoordinate",
    "SemanticTransport",
    "SolverJob",
    "SolverReceipt",
    "StageBuildKeys",
    "StateDelta",
    "StreamingDeclaration",
    "StreamingSemanticOwner",
    "SubExecutorReceipt",
    "admit_factor_proposals",
    "assert_finalising_claim_allowed",
    "assess_factor_proposals",
    "assess_pnf_closure",
    "build_admission_aware_semantic_lifecycle",
    "build_applicable_domain_ir",
    "build_domain_ir",
    "build_operational_reference_binding_artifacts",
    "build_semantic_lifecycle",
    "build_set_valued_binding_artifacts",
    "compact_binding_artifacts",
    "derive_resolution_demands",
    "derive_stage_build_keys",
    "evaluate_fibre",
    "execute_ir_request",
    "execute_ir_requests",
    "execute_ready_jobs",
    "fibre_element_from_proposal_row",
    "install_streaming_reduction_metrics",
    "normalize_factor_revision_artifacts",
    "normalize_projection_applicability",
    "owner_partition",
    "project_pronominal_reference_arguments",
    "project_resolved_factor",
    "project_review_state",
    "proposal_build_key",
    "reduce_factor_proposals",
    "resolve_reduced_factors",
]
