name: Fuzz Section Parser

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install atheris
      - name: Run fuzzer
        run: |
          python scripts/fuzz_section_parser.py -max_total_time=60
